### ISSUE TITLE
Refactor image names

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#10]
The simulation makes uses of several images, some of which are closely related.
The name of the assets should be consistent and more descriptive.  

For each object representation, we need five images: , a logo and four images within a frame.
A good naming convention to follow is

object-logo.png
object-left-facing-upright.png
object-right-facing-upright.png
object-left-facing-inverted.png
object-right-facing-inverted.png

where object is the name of the object, e.g. "pencil" .

For reference, some of the javascript files can be generated from the images using the grunt task
```
grunt modulify
```

**Comment by veillette** [comment]
As part of this issue, we can also update the naming convention within the representation.

**Comment by sarchang** [comment]
Image names are refactored; ready for @veillette to review.

**Comment by veillette** [comment]
I have reviewed the commits. Well done. We can close this.
