### ISSUE TITLE
Lens/Mirror can be lost off screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#100]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/667.
When dragging the lens/mirror up and down, you can drag it bellow the nav bar or above the top of the page. If you then let go you won't be able to pick it up again. Depending on the circumstance you may be able to change the window size or lens/mirror diameter, but under other circumstances this may not work. In which case the entire sim must be reset.

**Visuals**
![loss](https://user-images.githubusercontent.com/41024075/125111698-73155100-e0a3-11eb-9836-880358090209.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by veillette** [comment]
This is related to #57 .

**Comment by sarchang** [comment]
Optic is constrained from top of control panel to bottom of toolbox panel

**Comment by sarchang** [comment]
Should the optic go over the control panel?

**Comment by sarchang** [comment]
From design meeting: add padding to the upper and lower drag bounds for the optic.

**Comment by pixelzoom** [comment]
The original problem has been addressed.  The issue of z-order is being discussed in https://github.com/phetsims/geometric-optics/issues/174.  So I'm going to close this issue.
