### ISSUE TITLE
Focal length is equal to object distance

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#101]
For https://github.com/phetsims/qa/issues/667. Seen on Win 10 Chrome while fuzz testing.
This notice came up when fuzz testing. It doesn't seem to be an error, but MV says on Slack:
>We have some vestigial console.log statements that should be erased.

<img width="359" alt="thesealerts" src="https://user-images.githubusercontent.com/41024075/125120595-e2913d80-e0af-11eb-9084-c9fda0415373.png">

**Comment by veillette** [comment]
The console.log statements in TargetImage have been removed. There are no more console.log statements in the sim.

**Comment by veillette** [comment]
Assigning to @sarchang  to review.

**Comment by sarchang** [comment]
Looks good; closing.
