### ISSUE TITLE
Light going behind lens leads to odd behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#102]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/667. 
On the lens screen, if you move the light source far to the right the light is starting behind the lens. The different rays have strange behavior and the image on the screen behaves as though it is passing through the lens somehow.

**Visuals**
![behindlens](https://user-images.githubusercontent.com/41024075/125126141-e3c66880-e0b7-11eb-980c-8cd46d00e9b3.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_all_phet_debug.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by brooklynlash** [comment]
Also seen on Win10 FF

**Comment by veillette** [comment]
The dragListener for the lightsource is the same as the dragListener for the object. The current assets are of different size and have been scaled up (or down), so what is correct for the pencil is wrong for the light source.  This should be corrected once we get the new assets, which should be of the same size.

**Comment by veillette** [comment]
As part of fixing our work on dragBound and model bounds, this problem has been addressed. CLosing
