### ISSUE TITLE
Rulers jump out of box far to the left

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#104]
**Device**
iPad
**OS**
iPadOS 14
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/667. Seen on iPad Safari, but not on Win 10 Chrome, even with touch.
When dragging the rulers out of their box, they pop out far to the left and not under the finger dragging them out.

https://user-images.githubusercontent.com/41024075/125137195-73284780-e0c9-11eb-8194-45161aca6df9.MOV

**Comment by KatieWoe** [comment]
Also did not happen on Safari 14.1 on a MacOS 10.15.7. This device does not have touch.

**Comment by stemilymill** [comment]
I noticed this on Win10 chrome 91.0.4472.124 a bit earlier, but only on the Mirror screen, and with a mouse. Doesn't seem to happen on master.

![should the ruler appear there](https://user-images.githubusercontent.com/85511101/125137678-2e0d1100-e0db-11eb-998b-31e192643b5e.gif)

also, in a lesser and different way, on the Lens screen (ignore the brown background) :

![ruler jumps when clicked](https://user-images.githubusercontent.com/85511101/125137756-5432b100-e0db-11eb-8dc7-daf863c1ce34.gif)

**Comment by KatieWoe** [comment]
I ended up seeing this with the second lamp on Win 10 Chrome
![secondlamp](https://user-images.githubusercontent.com/41024075/125138979-e4b5c500-e0cc-11eb-92bb-0dc9895a9bd3.gif)

**Comment by stemilymill** [comment]
I wasn't sure if that is what https://github.com/phetsims/geometric-optics/issues/82 is referring to?

**Comment by phet-steele** [comment]
I believe this is also #56

**Comment by veillette** [comment]
This is indeed related to #56.

**Comment by veillette** [comment]
Tracking this issue in #56. Closing.
