### ISSUE TITLE
Color-blind filter makes telling rays from different sources apart difficult

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#105]
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/667. Using the Chrome color blind extension "Let's get color blind" I saw that the green and red ray lines for the two different sources are difficult, if not impossible, to tell apart.
<img width="809" alt="colorblindrays" src="https://user-images.githubusercontent.com/41024075/125141220-98b94f00-e0d1-11eb-884e-8b4b5e1f9e3e.png">

**Comment by sarchang** [comment]
Related to #66

**Comment by veillette** [comment]
Assigning to @arouinfar . The colors can be changed in the GOcolorProfile

**Comment by arouinfar** [comment]
Color changes were discussed in the 9/9/21 design meeting and are nearly finalized. I'll report back soon.

**Comment by pixelzoom** [comment]
I was asked to evaluate this for https://github.com/phetsims/geometric-optics/milestone/1.  But it looks like there's nothing I can do here, it's in @arouinfar's court.

**Comment by arouinfar** [comment]
Color changes are being tracked in https://github.com/phetsims/geometric-optics/issues/182, so closing.
