### ISSUE TITLE
Second source dot can be hard to grab with touch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#106]
**Device**
iPad
**OS**
iPadOS 14
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/667. When trying to grab the second source on an object with touch, I often grabbed and dragged the object instead.

**Comment by veillette** [comment]
The touch and mouse bounds could be dilated. Assigning to @sarchang to implement.

**Comment by sarchang** [comment]
I expanded the touchArea bounds for the movable point (red circle). I didn't get the chance to figure out how to make the touch bounds a circle, so it's a square for now. Perhaps use `movableNode.setTouchArea()`? The argument for that expression has to be a `kite.Shape` and I was not able to figure out how to make a circle. Assigning @veillette for help.

![image](https://user-images.githubusercontent.com/29347882/125866722-770df41b-8396-483c-b309-1e219bc93e32.png)

**Comment by veillette** [comment]
@sarchang.: touchArea can take Bounds2 or Shape or null. If you would like to have the shape of a circle, then you can create a shape circle with a larger radius than the icon.

RoundButton and the ResetAllButton have approaches to deal with circular shape.

From RoundButton

````
    // Get the actual button radius after calling super, so that buttonAppearanceStrategy has applied the stroke.
    // This accounts for stroke + lineWidth, which is important when setting pointer areas and focus highlight.
    // See https://github.com/phetsims/sun/issues/660
    const buttonBackgroundRadius = buttonBackground.localBounds.width / 2;

    // Set pointer areas.
    this.touchArea = Shape.circle( options.touchAreaXShift, options.touchAreaYShift,
      buttonBackgroundRadius + options.touchAreaDilation );
    this.mouseArea = Shape.circle( options.mouseAreaXShift, options.mouseAreaYShift,
      buttonBackgroundRadius + options.mouseAreaDilation );
````
However, the approach you took works well too. The touch area are not directly visible to the user and there is no harm in having it to be square rather than circular. 

I think you can leave as is, but you can implement the circle shape.

**Comment by sarchang** [comment]
@KatieWoe I changed the touch area bounds to be a larger square (see above). Can you test this on the iPad and tell me if it would be better if I made the touch bounds a circle? Or is a larger square good enough?

**Comment by KatieWoe** [comment]
Feels much better on master. Only did a quick check, but this seems to be a good size. I don't think circle vs square will make too much of a difference that a user could tell.

**Comment by sarchang** [comment]
Resolved
