### ISSUE TITLE
Use font awesome 5 for icons in ShowHideToggleButton

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#107]
See https://github.com/phetsims/sherpa/issues/83#event-5010659616

**Comment by veillette** [comment]
It looks a tad different than before.
I assign the label meeting:design for review by the design team.

**Comment by sarchang** [comment]
From Amy: make eye toggle icon logo smaller so that the slash is further from the border of the button

**Comment by veillette** [comment]
Assigning to @sarchang to finish implementing

**Comment by sarchang** [comment]
Increased margin. Ready for review by @veillette

**Comment by veillette** [comment]
That looks  good. Closing
