### ISSUE TITLE
Create a prototype for half split images

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#109]
In order to give 3D perspective, it was suggested that the object and images be split in half vertically, where each half would be on a different z layer.  The optical axis and rays could then be allow to fit within the two z-layers to give a sense of depth.

The flash simulation uses a similar approach with the projector screen (but not the images).
![image](https://user-images.githubusercontent.com/7633344/125514657-33a6a86c-9f25-46e0-9d44-2c5ccc03a9e8.png)

**Comment by veillette** [comment]
Similar to #126

**Comment by pixelzoom** [comment]
Moved this to https://github.com/phetsims/geometric-optics/issues/125. Closing.
