### ISSUE TITLE
Incorrect number of marginal rays with concave lens at maximum diameter

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#111]
**Test device**
MacBook Air (M1 chip)

**Operating System**
MacOS version 11.4

**Browser**
Chrome--most recent version (91.0.4472.114)

**Problem description**

https://github.com/phetsims/qa/issues/667 

3 marginal rays aren't shown when the concave lens is at a diameter of 1.3 (max). 

**Steps to reproduce**

1. Go to lens screen
2. Choose the concave lens
3. Increase diameter to 1.3
4. Move pencil around the screen. 

**Visuals**
<img width="1172" alt="Screen Shot 2021-07-14 at 4 40 48 PM" src="https://user-images.githubusercontent.com/87318828/125690214-313a30dd-cd55-40ef-a66c-d344c1345fff.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1182x679
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by veillette** [comment]
Thanks @Nancy-Salpepi. 
We use an heuristic argument to determine the initial direction of the rays for the concave lens, which doesn't guaranteed that they will go through the front and back shape.

There is a mathematical way to guarantee that the initials rays will go through the two shapes.

**Comment by veillette** [comment]
IN the process of addressing this issue for marginal rays of a concave lens, I created a method to find the extremum point. This can be leverage to find the exact size of the spotlight if we wish to go in that direction.

**Comment by veillette** [comment]
The number of rays is set to be three even for marginal rays and concave lens. Closing
