### ISSUE TITLE
Rays, object and image move in front of bottom panel rather than behind

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#112]
**Test device**
MacBook Air (M1 chip)

**Operating System**
macOS version 11.4

**Browser**
chrome (Version 91.0.4472.114)

**Problem description**
For https://github.com/phetsims/qa/issues/667
The rays, object or image move in front of the bottom panel rather than behind (they move behind the zoom buttons, ruler and combo box). 

**Steps to reproduce**
1. Choose either the lens or mirror screen
2. Select any object and move it up and down.  

**Visuals**
<img width="1172" alt="Screen Shot 2021-07-15 at 11 08 23 AM" src="https://user-images.githubusercontent.com/87318828/125815946-76c9b147-b306-4a8d-ab90-06cedbb4360a.png">
<img width="1172" alt="Screen Shot 2021-07-15 at 11 37 06 AM" src="https://user-images.githubusercontent.com/87318828/125816062-f5b930cb-9db0-48e7-8dda-ede614119592.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1325x679
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by veillette** [comment]
Thanks @Nancy-Salpepi . 

The z-layering of the bottom of the screen is different than the top of the screen.

Some of these interactions will need to review by the design team. 

Tagging with meeting:design.

**Comment by sarchang** [comment]
From Amy: this is fine, we can have object and image on top of the control panel.
