### ISSUE TITLE
Convert slider units to cm

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#122]
Convert curvature radius, refractive index, and diameter displayed from meters to centimeters.
Remove units from refractive index.

**Comment by veillette** [comment]
There was a faulty logic about the way we were passing the options for the NumberDisplay. 
Tracking other possible merge problems in #128. Also tracking the changes of units in the simulation #123. 

Closing

**Comment by veillette** [comment]
Beyo

**Comment by veillette** [comment]
The sliders have been updated to take centimeters and the "delta" step values has been updated to 1.  Assigning to @sarchang  for review.

**Comment by sarchang** [comment]
Looks good so far. I did not find any weird behavior but will re-open this issue if anything comes up.
