### ISSUE TITLE
Rays that only pass through front and top sides of diverging lens should still bend

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#124]
Rays that only pass through the front and top sides of a diverging lens should bend at the front of the diverging lens and then leave through the top.
![image](https://user-images.githubusercontent.com/29347882/126384377-6576f7c8-05dd-43b2-a0fa-4455f10bd4a8.png)

**Comment by veillette** [comment]
I have handled the rays that do not go through the back of the lens.
However, there is still a dependence on "firstPoint" that is the ray must be able to go through halfway through the lens.
This may result is some odd effects.

@sarchang, can you tell me what you think?

**Comment by sarchang** [comment]
I think this is probably fine; maybe we should ask Amy just to confirm? I will also be on the lookout during the interviews to see if students notice this and are confused by it.

**Comment by veillette** [comment]
That sounds like a good approach.

**Comment by arouinfar** [comment]
I think this approach sounds good. Here's what the worst case looks like (topmost ray in the lens):

![ray](https://user-images.githubusercontent.com/8419308/126552417-12ffce98-c5d5-4cf6-b48e-d49569b3ebfb.gif)

I'll add a note to the Teacher Tips about it.
