### ISSUE TITLE
Icon for lamp/screen in combo box should be a larger head of the lamp

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#127]
Create an icon from the head of the lamp to use in the combo box menu.

**Comment by sarchang** [comment]
Current design of combo box: logos are all the same size
![image](https://user-images.githubusercontent.com/29347882/126555066-e2693787-263b-48fa-b8c5-f7131bb0d92f.png)
Maybe later we will create icons without backgrounds; maybe it will look cleaner and less crowded

**Comment by veillette** [comment]
@sarchang : You should note where you got the logo from, and their permission license. If not, you can put your name as the creator.

**Comment by sarchang** [comment]
Should we will create icons without backgrounds (like the lamp logo)? Maybe it will look cleaner and less crowded?

**Comment by veillette** [comment]
Our work is done. Closing
