### ISSUE TITLE
Rays should stop when they hit the screen, but they continue on.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#13]
![image](https://user-images.githubusercontent.com/7633344/119889997-464b1700-bf05-11eb-8a85-f41bbaa2e881.png)

The LightRays should be aware of the position of the screen.

**Comment by veillette** [comment]
One approach to address this is to create a shape ( or a vertical line) that cut vertically through the middle of the screen. A light ray that intercepts the vertical line would be stopped. 
This means that we need to augment the api of LightRay to take into consideration the shape of this vertical line.

**Comment by sarchang** [comment]
Rays stop at the x value of the screen, but there are many other behaviors that need to be resolved, like when the rays don't hit the screen, the rays should continue. Closing this issue but tracking other tasks related to the rays and the screen in #85
