### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#134]
From the CRC:
>  - [ ] Does model.md adequately describe the model, in terms appropriate for teachers?

See https://github.com/phetsims/geometric-optics/blob/master/doc/model.md

**Comment by veillette** [comment]
Duplicate of #36

**Comment by veillette** [comment]
@arouinfar : I took a stab at writing a draft of the model but you are in a better position to write it. 
Assigning to @arouinfar .

**Comment by zepumph** [comment]
Note some formatting done in https://github.com/phetsims/geometric-optics/commit/276d32bc0cf2f027811cbd869840d2eb6bb77d24

**Comment by pixelzoom** [comment]
@arouinfar Let's hold off on this review until we're closer to publication, in case I need to make any model changes.

**Comment by pixelzoom** [comment]
Reviewing model.md and implementation-notes.md... I would recommend adding a **Terminology** section to model.md, and moving the general terminology from implementation-notes.md to model.md.  Otherwise this files are looking pretty good.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.  If you'd like to modify, feel free to do so directly.

**Comment by pixelzoom** [comment]
@arouinfar ready for review. If you'd like to modify, feel free to do so directly.

This must be reviewed before code review can begin.

**Comment by arouinfar** [comment]
@pixelzoom this was really nicely done. I fixed a few small things in the commit above.

The last sentence in this section is a bit unclear, and I recommend re-wording it. In particular, I'm not sure what you meant by, "The light spots... are based on the size of the light spot."
> <b>Light sources:</b> Light sources can be projected onto a screen. The light spots that appear on the screen are based on the aperture of the lens (i.e. its diameter) and the size of the light spot.

**Comment by pixelzoom** [comment]
Thanks @arouinfar. I must give credit to @veillette.  Most of the stuff below the **Abbreviations** section was his work.  I reorganized it into sections, and did a little worksmithing. 

The last sentence you referred to has been modified to read:

> **Light sources**: Light sources can be projected onto a screen. Brightness of the light spots on the screen is based on the diameter of the lens and the diameter of the light spot.

If this makes sense, please close.

**Comment by arouinfar** [comment]
Looks good, thanks.
