### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#135]
From the CRC:
> - [ ] Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?

See https://github.com/phetsims/geometric-optics/blob/master/doc/implementation-notes.md

**Comment by veillette** [comment]
I added to the implementation node before the code review although there is surely more confusing aspect of the similation that could be fleshed out.

**Comment by zepumph** [comment]
Note some formatting done in https://github.com/phetsims/geometric-optics/commit/276d32bc0cf2f027811cbd869840d2eb6bb77d24

**Comment by zepumph** [comment]
> I added to the implementation node before the code review although there is surely more confusing aspect of the similation that could be fleshed out.

Honestly. I thought that was a very intelligently written implementation notes markdown. It helped get me up to speed quite well on the physics and code structure. Up to you how much more you would like to flesh out.

**Comment by pixelzoom** [comment]
I make another pass through this later, to note any changes that I make.

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/geometric-optics/issues/196#issuecomment-926250039 for terminology used in the code. This should be used to revise implementation-notes.md.

**Comment by pixelzoom** [comment]
[implementation-notes.md](https://github.com/phetsims/geometric-optics/blob/master/doc/implementation-notes.md) is ready for review by whoever does the sim code review.

**Comment by pixelzoom** [comment]
Please review as part of code review https://github.com/phetsims/geometric-optics/issues/402.

**Comment by jonathanolson** [comment]
Implementation and model notes are excellent! Thank you.
