### ISSUE TITLE
Change initial position of object

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#142]
Object should be a little more than 2F away from the optic so that the object and image are noticeably different sizes. The object should also be offset from the optical axis.

Maybe something like this? Not sure if the top marginal ray should look parallel to the optical axis or not.
![image](https://user-images.githubusercontent.com/29347882/127384386-b0404c8c-4720-4c19-b954-2b200e8c7c7c.png)
![image](https://user-images.githubusercontent.com/29347882/127384474-988d10c3-d6f6-499f-89b2-e240b480db00.png)

**Comment by veillette** [comment]
The initial position of the first source is within GeometricOpticsConstants

  DEFAULT_SOURCE_POINT_1: new Vector2( -150, 0.0 ), // centimeters

Currently there is only one position for Point_1 which is shared across the Mirror and Lens Screen. 
However we may want to promote it to separate initial positions if needed.

**Comment by veillette** [comment]
![Geometric Optics screenshot (11)](https://user-images.githubusercontent.com/7633344/127568381-58d411dc-3301-4eaf-944f-96c5f938547b.png)

for Mirror
![Geometric Optics screenshot (12)](https://user-images.githubusercontent.com/7633344/127568466-b0809dc4-8130-4254-b1c8-36e894ea793c.png)

**Comment by veillette** [comment]
The constant for the second source vertical offset has been hoisted to GeometricOpticsConstant which will make it easier to tweak in the future.

**Comment by veillette** [comment]
The value of the second source vertical offset has been changed to match the eraser. The so called
```
DEFAULT_SOURCE_POINT_1
```
has been updated. 


Assigning to @arouinfar  for review.

**Comment by pixelzoom** [comment]
9/30/21 design meeting:

The current positions of things (objects and light sources) looks good. Closing.
