### ISSUE TITLE
Ray should bend at the first surface of the diverging lens

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#144]
![image](https://user-images.githubusercontent.com/29347882/127385188-797e1237-766c-4048-81d4-3a2e3f6f1a11.png)
The ray should bend when it intersects the left surface of the diverging lens, unlike the image on the left. It should look like the image on the right.
Currently, the ray only bends when it intersects with a line going through the center of the diverging lens.

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/128105211-ceb98d77-7940-435a-a9d8-baa6c298b6ff.png)


The behavior was changed such that there is no longer a dependencies on the bisecting line. 
Instead, we have written a new method to find the intermediate point if we have first hit the first shape.

As a result, the ray will always be refracted at the front shape if the hit it.

**Comment by pixelzoom** [comment]
It looks like work was done here, and it's been labeled ready-to-review.  But it was not assigned to anyone to review.  Let's start with @arouinfar.  Is this something you asked for? If so, does it look OK?

**Comment by arouinfar** [comment]
This seems to be working fine in master, closing.
