### ISSUE TITLE
Inaccurate rendering with `shuffleListeners` query parameter

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#145]
While working on #129, I noticed that having the queryParameter ShuffleListeners , lead to  inaccurate rendering with the curveType button. The image position and scale as well as the rays position do not update correctly, when toggling between convex and concave optic.

**Comment by pixelzoom** [comment]
It would not be tragic if this sim did not support `?shuffleListeners`.  So I'm going to unassign this for now, and we can decide whether we want to spend time on it when we get closer to public deployment.

**Comment by pixelzoom** [comment]
This has sorted itself out after all the changes and refactoring.   I can no longer reproduce by switching between concave and convex lens types.  Closing.
