### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#146]

**Comment by arouinfar** [comment]
I took an initial pass at the credits. 

@chrisklus was a part of the brainstorming meetings and mentored Sarah and Martin, but I'm not sure which section to credit him in. @chrisklus would you prefer the design team or a development credit?

Developers are currently credited alphabetically which seems appropriate given the contributions, but I'll let @pixelzoom make the final call.

**Comment by pixelzoom** [comment]
That's for doing the intiial pass @arouinfar, we'll likely need that for the Prototype.

@KatieWoe anyone else to add to QA credits as a starting point?  So far, we have:

> qualityAssurance: 'Steele Dalton, Nancy Salpepi, Kathryn Woessner',

**Comment by chrisklus** [comment]
Oh, I forgot about this structure. I think team is much more appropriate.

**Comment by pixelzoom** [comment]
I've added @chrisklus to the team credits:

<img width="617" alt="screenshot_1325" src="https://user-images.githubusercontent.com/3046552/136108997-aea2cb74-6ad2-42e6-98ad-b0a160581453.png">

**Comment by KatieWoe** [comment]
Emily Miller might need to be added. @stemilymill please confirm.

**Comment by arouinfar** [comment]
I added her to the credits because she worked on the assets I just delivered. The assets currently checked in were all taken from the openstax sim and used as a stand-in. As far as I know, nothing came from the Flash version.

**Comment by stemilymill** [comment]
I worked on geometric optics back in summer so I should probably be added too

**Comment by pixelzoom** [comment]
Slack:

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [2:14 PM](https://phetsims.slack.com/archives/DBQK9V6LF/p1648498483355909)
Do you have anyone else to add to GO QA credits?

Kathryn Woessner  [2:15 PM](https://phetsims.slack.com/archives/DBQK9V6LF/p1648498554098749)
Clifford Hardin should be added. Thanks

**Comment by pixelzoom** [comment]
Slack:

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [8:03 AM](https://phetsims.slack.com/archives/DBQK9V6LF/p1649253813184089)
Any addition QA credits for https://github.com/phetsims/geometric-optics/issues/146?  The current credits are:
qualityAssurance: 'Steele Dalton, Clifford Hardin, Emily Miller, Nancy Salpepi, [Kathryn Woessner](https://app.slack.com/team/UBLN0PWJU)',

Kathryn Woessner  [8:29 AM](https://phetsims.slack.com/archives/DBQK9V6LF/p1649255366631329)
No new people I believe

**Comment by pixelzoom** [comment]
Publishing 1.1, closing.
