### ISSUE TITLE
review of pointer areas

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#147]

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/127424148-8b3c5972-366b-4449-8149-5763e998de78.png)
![image](https://user-images.githubusercontent.com/7633344/127424233-29a014df-c8a6-4ee7-b059-5b3265d01e71.png)

**Comment by veillette** [comment]
The show pointers do not overlap and seems large enough for most purposes.  
The object and the optic are large and do not need to have larger pointer areas.

The second source on the object and the ruler Icon bounds were dilated manually.
All the other ones are using the default values.

**Comment by veillette** [comment]
Assigning to @arouinfar to review.

**Comment by pixelzoom** [comment]
@arouinfar Let's hold off on this until we're closer to publication.

**Comment by pixelzoom** [comment]
All UI components are present in the sim, and pointer areas have been adjusted. Ready for review.

**Comment by arouinfar** [comment]
The pointer areas look good with `showPointerAreas` and I didn't have any issues with the touch areas on my phone, so I'll go ahead and close.
