### ISSUE TITLE
Memory testing

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#148]

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/127425710-6e4823f1-dcd4-4c69-b53b-55b3d8300e4e.png)


Each of the snapshots were collected with a 1 minute interval for a total of five minutes with ea, fuzz and brand=phet.

For the last snapshot (6), I forced a garbage collection before taking the snapshot

**Comment by veillette** [comment]
There is no obvious memory leakage of sim-specific classes. This looks like a very reasonable memory footprint

**Comment by pixelzoom** [comment]
We'll need to do memory testing again when the sim is feature complete.

**Comment by pixelzoom** [comment]
Since the sim is going to support `brands=phet,phet-io`, we'll need to do memory tests for both. So changing the title of this issue.

**Comment by pixelzoom** [comment]
Since this sim has changed so much, and since we now need to test both phet and phet-io brands, I'm going to close this issue, and resume testing in new issues.
