### ISSUE TITLE
Scene Buttons for Curve type

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#15]
![image](https://user-images.githubusercontent.com/7633344/119916559-bfad2e80-bf32-11eb-8ab1-33bdf5f3be1b.png)

As a starting point, we need to create two icons for the lens screen. 
They function as a radio button group. 

An example of scene buttons, one can look at PlinkoProbability, and the HistogramModeControl  https://github.com/phetsims/plinko-probability/blob/9cf9d797fcff38b8f6f1316bdcaceb867513e64b/js/common/view/HistogramModeControl.js

Since we will have similar buttons for the Mirror screen, we should  create this module with the Common View folder.

The control group can be instantiated with the screenView of each screen (like it is done in Plinko-Probability) or it can be created with the GeometricOpticsScreenView with a config parameter.

**Comment by veillette** [comment]
Before we move forward with this, we should get the green light from the design team, since there was some back and forth between keeping simple radio Buttons. I'll add the label design:meeting such that we ca bring it up next time before we move ahead with the implementation.

**Comment by sarchang** [comment]
Created scene buttons for mirror and lens
![image](https://user-images.githubusercontent.com/29347882/121214530-6d2a1700-c83c-11eb-9bcd-4fed8b070bdd.png)
![image](https://user-images.githubusercontent.com/29347882/121214562-761ae880-c83c-11eb-93b2-fd99b98d4440.png)

**Comment by sarchang** [comment]
Note: thickness of mirror is not uniform; this should be addressed by changing getFillAndOutlineShapes

**Comment by sarchang** [comment]
Removed the concave/convex radio buttons

**Comment by veillette** [comment]
The thickness of the mirrors was addressed in the previous commits.
Our work is done here.
