### ISSUE TITLE
No cursor change on hover

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#157]
I noticed for for https://github.com/phetsims/geometric-optics/issues/154, during my first time using this sim, that it seems a bit strange to me that the "pointer" cursor only appears once you begin dragging the elements in the sim. I would have expected a cursor change on hover to help cue what is draggable. For example, it wasn't immediately clear to me that only the left pencil was draggable, and not the right one (the refracted image).

**Comment by kathy-phet** [comment]
Fix this for prototype, if easy.

**Comment by pixelzoom** [comment]
@arouinfar please review in master.  All draggable objects now have `cursor: 'pointer'` (the hand) when you hover over them.  The exceptions are the lens and mirror.  Since they can only be moved up/down, they have `cursor: 'ns-resize'` (up/down arrows).

**Comment by pixelzoom** [comment]
9/23/21 design meeting: Looks good, closing.
