### ISSUE TITLE
Rulers jump away from mouse when dragged out of the toolbox

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#158]
It is possible that this is a feature, and not a bug, but I wanted to note that it is quite weird to me that the rulers jump into the play area, and don't come out of the toolbox underneath my mouse. The reason this is weird is because when I click and drag the ruler icon down, the mouse is ~80% of the screen away from the ruler it is dragging. I would recommend changing it to what I have found to be idiomatic PhET behavior. This is where the ruler is centered underneath the mouse (or perhaps with a bit of an offset) when dragged out of the toolbox.

**Comment by zepumph** [comment]
Not sure if you want a separate issue (let me know if I should make it), but this same bug occurs when trying to drag the second light source.

**Comment by veillette** [comment]
FYI @zepumph , the light source offset of the second source is another bug that is in fact not related. We are tracking it separately in #82.

**Comment by veillette** [comment]
Closing this, since we are tracking it in #56.
