### ISSUE TITLE
create chexboxes that support icons, i18,  and optional elements.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#16]
The design document for the Lens screen indicates the need for vertical checkboxes.

![image](https://user-images.githubusercontent.com/7633344/120006601-0b012480-bfa7-11eb-9e3e-6149b14305b1.png)

Currently there is already support for Vertical checkbox group on master. 
However, there are a few design elements that are currently missing:
-  The Focal Point checkbox has an icon 
-  There is currently no support for maxWidth for internalization.
-  The Mirror screen does not have a Guides checkbox.
-  The Mirror screen may need to have an additional checkbox.

The code review has a section on internalization (i18n)
https://github.com/phetsims/phet-info/blob/152347ec161f5780ba2cbcbcda2a6dfa6601b0ba/checklists/code_review_checklist.md

One of the criteria is to be able to handle gracefully strings that are longer than English strings.   This can be check by running the query parameters stringTest=double and stringTest=long.
The checkboxes should pass the test. This will most likely involved using the optional parameter maxWidth for text string.

In addition, the checkbox should support optional icon. There are many simulations that have checkboxes with optional icons, e.g. Vector-Addition that can be used as a starting point.

Since the vertical checkbox group is slightly different in the Lens and Mirror screen, we need to support it with a config parameters.

FYI, the checkboxes are built within the module ControlPanel. It may be worth considering creating a compete separate class that extends VerticalCheckBoxGroup since the ControlPanel is already quite lengthy.

**Comment by sarchang** [comment]
Checkbox for guides in the Control Panel only appears when on lens screen.

**Comment by sarchang** [comment]
Do we want the focal point icon next to the checkbox? Seems a bit redundant with the labels.
![image](https://user-images.githubusercontent.com/29347882/122823015-0ecd5180-d29c-11eb-94ed-37044c251996.png)

**Comment by sarchang** [comment]
Do we still want the focal point icon next to the checkbox? Seems a bit redundant with the labels since the focal point is labeled explicitly as well. Currently, we have a focal point icon always visible next to the focal point checkbox.

**Comment by sarchang** [comment]
keep as is

**Comment by sarchang** [comment]
work is done
