### ISSUE TITLE
Long strings layout problems

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#160]
There are two minor issues when I use `stringTest=long`. Note this isn't a problem when using `stringTest=double`, so likely this is low priority. Please note two things from the below picture, both based on the width of the control panel in the bottom center:

1. The width has pushed the lens radio buttons on the left out of the screen view layout bounds (most likely a code smell, but could be purposeful).
2. The hard coded layout of the reset all and show/hide buttons have cause an overlap with the panel, even though there is some space to push them out right.

![image](https://user-images.githubusercontent.com/6856943/128197998-3af081e3-8895-4788-9afe-adb547f60769.png)

I believe there could be an easy solution here by just containing these three horizontal composites in an HBox, and then setting the max width to be the layout bounds. The may not be ideal in the normal case though. Up to you how and if to proceed!

**Comment by pixelzoom** [comment]
Fixed in the commit above by adjusting maxWidth of NumberControl subcomponents. See screenshot below. Closing.

<img width="990" alt="screenshot_1261" src="https://user-images.githubusercontent.com/3046552/134411681-5af7f5dd-6867-477e-a69f-e1d5f91014d8.png">
