### ISSUE TITLE
More documentation needed for ?showGuides

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#162]
Looks like an unfinished doc:

https://github.com/phetsims/geometric-optics/blob/f530833f9dc37cbc15ac228cc61a7df2d13956d9/js/common/GeometricOpticsQueryParameters.js#L24-L30

**Comment by zepumph** [comment]
https://github.com/phetsims/geometric-optics/issues/154

**Comment by veillette** [comment]
The documentation was added to make it clear that show guides refer to the checkbox guides rather than guides themselves.

Assigning back to @zepumph for review.
