### ISSUE TITLE
Lots of hardcoding for "first" and "second" sources etc.

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#164]
I see that much of the model for the source/object seems to be based on if it is the first or second. I wonder if there is an abstraction to be made here. What if in the future we wanted to have three source points on the source object? I'm imagining a model class that embodies the "trifecta" of source, lens, and target. Then the rest model can utilize each of these as desired. Does this refactor make sense?

Part of my desire to recommend this is looking for usages of the regex `first.* =` and `second.* = `. Both of these yield seemingly related entities spread out throughout the whole model.

**Comment by zepumph** [comment]
I would also like to say that this part is quite confusing:

https://github.com/phetsims/geometric-optics/blob/1628f6fbd541261892e359e31ebc3652b4dee61b/js/common/model/GeometricOpticsModel.js#L100-L114


The "first" and "second" here seem related, due to the vicinity in the code and the parallelism in declaration, but there are very different duos that do not have anything to do with each other.

**Comment by zepumph** [comment]
https://github.com/phetsims/geometric-optics/issues/154

**Comment by pixelzoom** [comment]
@zepumph said:
> What if in the future we wanted to have three source points on the source object? ...

This is inherently a design question.

"First" and "Second" sources are deeply ingrained in this sim, and the implementation is definitely limited to 2 sources.  Generalizing to support N sources would be a huge change - a change that I'd prefer not to make in a sim that I'm potentially inheriting.

There's also the question of whether such a change would have any actual future value.  @arouinfar is there any possbility that this sim will need to accommodate more than 2 sources?  Or can we safely assume that it's OK for the model to be limited to 2 sources?

**Comment by pixelzoom** [comment]
@arouinfar and I discussed this on a Zoom call.  She said that there's zero chance that this sim will ever have more than 2 sources - it's not necessary, not a goal, and the model would just be too complictaed.  So I'm going to close this issue as "won't fix".
