### ISSUE TITLE
Thoughts about enableFirstTargetProperty 

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#166]
This seems like a good candidate for being refacted into `Target.js`. The it would be something like `this.firstTarget.enabledProperty`. 

With a patch as simple as this, you can use the benefits of `EnabledComponent.js`:

```diff
Index: js/common/model/Target.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Target.js b/js/common/model/Target.js
--- a/js/common/model/Target.js	(revision 6bce3b0532bddd2856e571a27bd8d3342217c216)
+++ b/js/common/model/Target.js	(date 1628095386137)
@@ -9,6 +9,7 @@
  */
 
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
+import EnabledComponent from '../../../../axon/js/EnabledComponent.js';
 import Bounds2 from '../../../../dot/js/Bounds2.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
 import geometricOptics from '../../geometricOptics.js';
@@ -16,7 +17,7 @@
 
 const OBJECT_SCALE_FACTOR = GeometricOpticsConstants.OBJECT_SCALE_FACTOR;
 
-class Target {
+class Target extends EnabledComponent {
 
   /**
    * @param {Property.<Vector2>} objectPositionProperty - position of the object/source
@@ -30,6 +31,8 @@
                tandem ) {
     assert && assert( tandem instanceof Tandem, 'invalid tandem' );
 
+    super();
+
     // @private {Property.<Vector2>} position of the object/source
     this.objectPositionProperty = objectPositionProperty;
 

```

Then `Target` will automatically get an `enabledProperty` which is a `BooleanProperty`. 

I feel like there would have to be a pretty good reason to keep this separated, but let me know if you want to discuss further.

**Comment by zepumph** [comment]
And of course this would apply to the `second` too.

**Comment by zepumph** [comment]
Also, as an aside, I think in general we name based on adjectives, as opposed to verbs, so the current name (which is likely to removed anyways), should be `firstTargetEnabledProperty`.

**Comment by zepumph** [comment]
https://github.com/phetsims/geometric-optics/issues/154

**Comment by veillette** [comment]
This seems like a very sensible idea.

**Comment by veillette** [comment]
A side benefit is to simplify the constructor of LightRays and TargetNode.

**Comment by veillette** [comment]
The target is now extending enabledComponent. 
Assigning back to @zepumph for review.

**Comment by pixelzoom** [comment]
@zepumph can you please review, to see if this is what you had in mind?   High priority, since we're trying to get a prototype published, and I'd like this issue to be closed before that happens.

**Comment by zepumph** [comment]
Yes thanks. It got lost in my issues without the review label. This looks really good. Exactly what I expected.

**Comment by pixelzoom** [comment]
Note that I ended up replacing `enabledProperty` with `visibleProperty` in Target.  This seems to be a better fit semantically, since everyplace it's used it has to do with visibility.
