### ISSUE TITLE
Create a small data class for the return type of Optic.get*Shapes()

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#167]
I think it would be a bit more clear if instead of returning an object literal of shape keys, there was a private class that was a data type that stored those fields, and then the return type could be that class.

Something like `OpticShapeCollection` or `OpticShapeStorage` or `ShapesForOptic`. Up to you if you want to do this.

**Comment by zepumph** [comment]
https://github.com/phetsims/geometric-optics/issues/154

**Comment by veillette** [comment]
I agree.

**Comment by veillette** [comment]
I created an OpticShapeCollection class that hosts all the shapes for rendering and ray hitting. In the process, I realized that the middleShape  was unused and was therefore removed (see #171). 
 
Overall, that is a nice improvement, that simplifies the optic class.
Assigning back to @zepumph  for review.

**Comment by zepumph** [comment]
This is really excellent. I wasn't even thinking of being able to factor out the shape creation functions. This is a great divide of responsibility! Nice work.

* I would recommend setting all instance variables to null in the constructor, and documenting which of them may actually be set to null (not have a shape) after construction, and for which optic type that may occur. 
* Optic.shapesProperty could be optionally renamed to `Optic.shapeCollectionProperty`. A bit clearer to go with the rename.


Thanks!

**Comment by pixelzoom** [comment]
Looks like these still a bit of work to be done here, as suggested in https://github.com/phetsims/geometric-optics/issues/167#issuecomment-893620670.

**Comment by pixelzoom** [comment]
All recommendations have been implemented. Closing.
