### ISSUE TITLE
Do we need both verticalOffsetProperty and lightSourcePositionProperty?

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#169]
It seems like verticalOffsetProperty is just a subset of unconstrainedSecondSourcePositionProperty. It feels a bit more clear if you just had a single Property, perhaps `secondSourcePositionProperty`, which is clamped into the "track" if there is an object, and is allowed to be free if the "light" source/object is selected. I think that would save a bunch of code that splits on if the representation `isObject`.

#154

**Comment by veillette** [comment]
One more successful approach would be to have a class SourceObject that is responsible for one source position and two instatiations for the first and second source.  The constraint between the two positions would then be imposed outside of this class.

**Comment by veillette** [comment]
Also @zepumph  noted in SourceObject that this is very hard wired and tie to the representation. 
````
 * REVIEW: In general this type seems like it serves its purpose, but it feels really hard coded to the current, specific
 * REVIEW: implementation of this sim. There is only room for two sources, and only room for the second one moving (and that
 * REVIEW: is very tied to its representation). The source/object is a pretty general part of an optics model, so it would be neat
 * REVIEW: if this could have a bit more flexibility, but I understand why we may not want to go back to implement that
 * REVIEW: at this time. Basically this comment is an extension of https://github.com/phetsims/geometric-optics/issues/164
````

**Comment by pixelzoom** [comment]
Both of these Properties have been factored out into SecondSource.js. `unconstrainedSecondSourcePositionProperty` was renamed `lightSourcePositionProperty`.

**Comment by pixelzoom** [comment]
The reason why we need both `lightSourcePositionProperty` and `verticalOffsetProperty` is that SecondSource is overloaded to handle both the second light source and the second point of interest on the Object.   I've improved documentation to indicate that.  

In the longterm, I think it would be better to break "light source" and "second point of interest on object" into separate things.  Having to check `representation.isObject` to do separate things is not very object-oriented, and it's made inheriting and modifying this sim unnecessary complicated.   But that's not the topic for this issue - yes, both Properties are currently necessary.  So closing.
