### ISSUE TITLE
Add query parameters

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#17]
This issue will collect information about query parameters that are useful for the simulation.

**Comment by veillette** [comment]
Useful query parameters would be:
 - showTargetPoints- show the target points
 - showObjectPoints- show the sources of light or objects
 - showCenterPoint - similar to focalPointNode but for the center of curvature of the mirror
 - showImageLeftTop - show (with a circle) the position of the left top of the images.
 - showOpticalVertical - show a vertical line through the center of the optic

These parameters would all be for internal use.

**Comment by veillette** [comment]
I created a query parameter called showDebugPoints, that shows
- the optic position
- the object position
- the image position

**Comment by veillette** [comment]
I added a query parameter named "show2fPoints" that put two disks at a distance 2f from each side of the optic.

**Comment by pixelzoom** [comment]
NOTE: All of these query parameters have been renamed, combined, and/or deleted.  See GeometricOpticsQueryParameters for the ground truth.
