### ISSUE TITLE
Shouldn't rays go behind the control panel?

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#174]
From https://github.com/phetsims/geometric-optics/issues/154

![image](https://user-images.githubusercontent.com/6856943/128413688-7054543e-9304-44fc-bce8-e6406d53a778.png)

**Comment by zepumph** [comment]
Even with all this important stuff, I still feel like it should be behind:

![image](https://user-images.githubusercontent.com/6856943/128423573-ee2d6594-d524-40e0-9456-29f76d63eb7c.png)

**Comment by kathy-phet** [comment]
@arouinfar and @kathy-phet decided to revisit the constraints of the lens to make its up down motion less.

**Comment by pixelzoom** [comment]
I was asked to evaluate this for https://github.com/phetsims/geometric-optics/milestone/1.  But in the previous comment, I see that design decisions have not been made, so there's nothing I can do.

**Comment by pixelzoom** [comment]
Also worth noting:

* It's not just the rays that go in front of the control panel.  Many other things are in front of the control panel. The virtual image, the lens, the mirror, ...

* The things that are in front of the control panel are BEHIND the controls at the top of the screen (combo box, etc.)

**Comment by pixelzoom** [comment]
9/23/21 design meeting: Move play area behind everything else. Closing.
