### ISSUE TITLE
Provide estimate to finish this sim.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#176]
@kathy-phet asked me to review open issues and provide an estimate on finishing this sim.

**Comment by pixelzoom** [comment]
@zepumph identified these issues as the "larger items":

https://github.com/phetsims/geometric-optics/issues/173
https://github.com/phetsims/geometric-optics/issues/164
https://github.com/phetsims/geometric-optics/issues/169

**Comment by pixelzoom** [comment]
In 8/28/2021 Slack, @kathy-phet asked for 2 specific estimates:

> 1) publish 1.0 Geometric Optics (with minimal clean up) and 
> 2) then refactor (address code review comments) on Geometric Optics

**Comment by pixelzoom** [comment]
Re the estimates requested in https://github.com/phetsims/geometric-optics/issues/176#issuecomment-907852595...

These requests seem to assume that the sim is ready to publish with minimal cleanup, and that’s not the case.  @arouinfar and I met on Zoom to discuss the status of the sim. The sim is not feature complete, and there is significant work to be done. Code review was definitely premature — I’m guessing it was a non-standard code review, done to evaluate the state of the code at the point when Martin and Sarah had to stop working.

So I don’t think it makes sense for me to spend time on these estimates. What I think needs to be done is:

* Identify work that needs to be completed for 1.0.  Create new GitHub issues for any remaining work that doesn’t have an issue.  Mark GiHub issues as deferred that don’t need to be included in 1.0.
* Estimate how long it will take to make the sim feature complete.
* Then estimate how long it will take to do minimal cleanup vs a more thorough cleanup.

**Comment by pixelzoom** [comment]
@kathy-phet will followup with @arouinfar on how to proceed.

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet When you have reviewed the open issues and summarized what work needs to be completed, feel free to assign this back to me with instructions on how to proceed.

**Comment by kathy-phet** [comment]
Chris, Amy and I reviewed the issues in Geometric Optics and binned them into "Prototype", "Feature Complete" and "1.0 Publication".
Can you take a look at the "prototype" issues?
https://github.com/phetsims/geometric-optics/milestone/1
And see what you think. Feel free to take action on any prototype issues you see you can.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar  I reviewed the issues in https://github.com/phetsims/geometric-optics/milestone/1. Very few of them were in a state where I could do anything.  I did make progress on a couple, and assigned them to @arouinfar for review.

I can't say that I recommend the progression that's implied by the milestones: "Prototype" to "Feature Complete" to "1.0 Publication".   Yes, some things could be addressed quickly to get a prototype out. But you'll end up having to redo some of those things to move to the next milestone.  https://github.com/phetsims/geometric-optics/issues/120 is a good example. 

Now that I've spent a little time in the code, my WAG is that this sim would take me ~200 hours to complete, to PhET standards.

**Comment by pixelzoom** [comment]
9/1/21 design meeting @arouinfar @kathy-phet @ariel-phet 

The 200 hours seems reasonable. Next steps:
* @pixelzoom and @ariel-phet to discuss terminology next week
* @arouinfar and @kathy-phet to work on their issues for the Prototype milestone
* @pixelzoom to keep chipping away at issue, with focus on Prototype milestone
* publish prototype sometime in the next couple of weeks

**Comment by pixelzoom** [comment]
Next steps have been moved to https://github.com/phetsims/geometric-optics/issues/195 and https://github.com/phetsims/geometric-optics/issues/196.

Closing.
