### ISSUE TITLE
refactor Screen to ProjectorScreen

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#18]
The word Screen is already used extensively within PhET. We should try to avoid overloading it. We can refactor it to ProjectorScreen instead.

Therefore, the modules Screen and ScreenNode should become ProjectorScreen and ProjectorScreenNode. 

There are instances and methods  with the word Screen in them. They should also be refactored.

**Comment by sarchang** [comment]
Refactored image names, module names, instances to ProjectorScreen and ProjectorScreenNode

**Comment by veillette** [comment]
The work has been reviewed. Well done
