### ISSUE TITLE
Difficult to see blue lamp on blue background.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#181]
The blue lamp on the dark blue background is really difficult to see, a poor color choice imo.

<img width="406" alt="screenshot_1235" src="https://user-images.githubusercontent.com/3046552/133324638-6aedc239-6218-4fea-9f60-bd73e113f299.png">

**Comment by arouinfar** [comment]
Artwork is being tracked in #14. The lamp will not be blue, so closing.
