### ISSUE TITLE
Verify information in images/license.json.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#186]
Related to https://github.com/phetsims/geometric-optics/issues/14 ...

When artwork has been revised, please review [images/license.json](https://github.com/phetsims/geometric-optics/blob/master/images/license.json) to verify that all of the information is correct.

**Comment by arouinfar** [comment]
@pixelzoom asked about this in https://github.com/phetsims/geometric-optics/issues/14#issuecomment-935249335 and I responded in https://github.com/phetsims/geometric-optics/issues/14#issuecomment-936838484. 

Can we close this issue @pixelzoom?

**Comment by pixelzoom** [comment]
Yes, we can close this issue, and verify new license.json info over in #14.
