### ISSUE TITLE
Revise terminology in the code.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#196]
Terminology and naming in the code is generally good, but could use some polishing. I'll read through model.md and implementation-notes.md again.  Then @ariel-phet and I will discuss terminology (probably early in the week of 9/20).

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet via Zoom.  Here's what he recommended. 

| Exiting terms in code | Recommended term in code |
| :--- | :--- |
| object, source object, source/object, first source/object | Optical Object | 
| second object, second source, second source/object | Second Point |
| target, image, virtual image | Optical Image |
| light source, source of Light, light | Light Source |
| ray, light ray | Ray |
| axis, optic axis, optical axis | Optical Axis |
| projection screen, projector, projector screen | Projection Screen |
| spotlight | Light Spot |

@arouinfar if you disagree with any of the above, please let me know ASAP. I plan to start changing the code on Monday 9/27.

**Comment by pixelzoom** [comment]
At 9/23/21 design meeting, @kathy-phet noted that PhET-iO support for this sim will likely be desired in the not-too-distant future.  PhET-iO exposes the internals of simulations, particular the names that are used. So another important reason for adjusting terminology is the eventual need to PhET-iO instrument this sim. Terms like "target" will not cut it when we expose these names via the PhET-iO API.  They must be aligned with standard terminology for the geometric optics domain.

**Comment by pixelzoom** [comment]
@arouinfar The one term in the above table that causes a UI change is "Second Point".   There is currently a checkbox labeled "Second Source".  That is correct terminology for a light source, but incorrect for an object. For an object, we are showing a second "point of interest" on the object, not a second source of light.  For a light source, "second point" can mean the second point from which light originates.  "Second Point" is admittedly still a little wonky for a light source, but less wrong overall than "Second Source".

**Comment by pixelzoom** [comment]
@arouinfar after reviewing, please assign this issue back to me so I can begin work.

**Comment by pixelzoom** [comment]
9/30/21 design meeting:

* Let's use SourceObject instead of OpticalObject.
* Maybe use ResultingImage instead of OpticalImage (@pixelzoom wants to poke around a bit for other options.) @arouinfar said she could live with OpticalImage.

**Comment by pixelzoom** [comment]
The more I read the literature for this domain, the less concerned I am with our choice of "Second Point".  The light source is frequently referred to as a _point light source_, and that's in fact how it appears in PhET's sim - the light originates from a single point.

**Comment by pixelzoom** [comment]
I'm back to preferring "Optical Image". From Encyclopedia Britanica,  https://www.britannica.com/technology/optical-image:

> **Optical image**, the apparent reproduction of an object, formed by a lens or mirror system from reflected, refracted, or diffracted light waves. There are two kinds of images, real and virtual.  ...

@arouinfar @ariel-phet thoughts?

**Comment by pixelzoom** [comment]
In the code, "optic" is used to refer to the lens or mirror.  Should it be "objective"?  From https://en.wikipedia.org/wiki/Objective_(optics): 

> In optical engineering, the **objective** is the optical element that gathers light from the object being observed and focuses the light rays to produce a real image. Objectives can be a single lens or mirror, or combinations of several optical elements.

**Comment by pixelzoom** [comment]
In the code, "optic" is used to refer to the lens or mirror.  Should it be "objective"?  From https://en.wikipedia.org/wiki/Objective_(optics): 

> In optical engineering, the **objective** is the optical element that gathers light from the object being observed and focuses the light rays to produce a real image. Objectives can be a single lens or mirror, or combinations of several optical elements.

Or maybe "optic" is OK.  Google defines it as:

> a lens or other optical component in an optical instrument.

This term will be exposed by PhET-iO, so what do we want to see?

**Comment by pixelzoom** [comment]
I see the object often referred to as the "observed object".  Would that be better than "source object"?

**Comment by ariel-phet** [comment]
@pixelzoom in my experience "objective" tends to be used in microscopy and objectives often contain multiple optics, so I think optic is the better term here. The lenses and mirrors in the sim would generally be called "optical elements" or "optics" so I don't think changing to "objective" would be preferable. 

I personally think "OpticalImage" is pretty clear, but "VisualImage" might be more interpretable by someone who has less expertise in the field. If you don't mind a longer name "ImageOfSourceObject" might be the clearest and then is self referential to the code.

**Comment by arouinfar** [comment]
@pixelzoom I'm fine with using "OpticalImage" but would prefer to stick with "Optic" for the lens/mirror since it's the more common term in this context.

**Comment by pixelzoom** [comment]
Notes to self... Since we're adding an Arrow representation, we'll now have different types of Objects and their associated Images.  So the names I'm now considering using are `FramedObject` and `ArrowObject` (for the Objects) and `FramedImage` and `ArrowImage` (for their associated Images).  I like this much better than "Source Object" and "Optical Image", because it's closer to the correct domain terminology, and (I think) disambiguates sufficiently from JavaScript Object and Scenery Image.

**Comment by pixelzoom** [comment]
Terminology has been revised in the code.  The table in https://github.com/phetsims/geometric-optics/issues/196#issuecomment-926250039 is up-to-date.  I'll close this issue, and refer to it in https://github.com/phetsims/geometric-optics/issues/135 when I update implementation-notes.md.
