### ISSUE TITLE
Reset All Button does not reset the location of Second Source

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#212]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
chrome

**Problem description**
In the Lens Screen, after the Reset All button is pressed, if the Second Source checkbox is rechecked, the Second Source will appear in its last position instead of at the bottom of the object. 

**Steps to reproduce**
1. In the Lens Screen, check the Second Source checkbox
2. Move the Second Source to either the middle or top of the pencil
3. Press Reset
4. Check the Second Source checkbox

**Visuals**

<img width="651" alt="Screen Shot 2021-09-24 at 11 31 59 AM" src="https://user-images.githubusercontent.com/87318828/134701627-5ef9dc83-0e72-4a0a-ba6d-908b29e899be.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Geometric Optics
URL: https://bayes.colorado.edu/dev/phettest/geometric-optics/geometric-optics_en.html?ea&brand=phet
Version: 1.0.0-dev.12 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Language: en-US
Window: 1440x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.  This regression crept in when I factored out SecondSource.js.  Fixed in the above commit, and closing.
