### ISSUE TITLE
Control panel and buttons move when object is dragged across top of panel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#213]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
chrome

**Problem description**
When an object is dragged back and forth across the top of the control panel, the panel and buttons next to it will move up/down slightly. 

**Steps to reproduce**
Drag the object back and forth across the top of the control panel. 

**Visuals**
![panelshift](https://user-images.githubusercontent.com/87318828/134918324-99db080d-c74a-4ade-9cf4-10d8234f7aee.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.12/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.12 2021-09-24 00:22:17 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Language: en-US
Window: 1496x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
There's nothing the sim is doing to cause this, it's a scenery problem.  It has been reported previously for multiple sims, so I've created https://github.com/phetsims/scenery/issues/1289.   There is a workaround (`layerSplit: true`, used in https://github.com/phetsims/ph-scale/issues/226), but I don't think that it's a great idea to keep propagating that workaround to multiple sims - that's building unnessary technincal debt.   The workaround can also negtively impact performance, which makes me nervous in sim like Fourier that is performance-critical.

@arouinfar please advise on how to proceed.

**Comment by kathy-phet** [comment]
Note that this jumping is also happening on Windows 10, Chrome Version 94.0.4606.61. It's pretty subtle so I probably wouldn't have noticed it., but I see it if I look closely. It only happens when the object gets closer to the control panel, rather than where it starts and more typical moves from its starting location. 

I think its good to track down if we fix the source issue, but I would not let this block a prototype publication.

**Comment by pixelzoom** [comment]
If PhET doesn't have the resources to address this generally in phetsims/scenery#1289, then perhaps I should add the `layerSplit: true` workaround in yet-another sim.   We'll have to check for potential performance impact.

**Comment by pixelzoom** [comment]
Slack conversation with @jessegreenberg 


Chris Malley  3:13 PM
Why is it necessary to do this:
``js
        if ( infoButton.isPDOMClicking() ) {
          infoDialog.focusCloseButton();
        }
```
… instead of simply calling `focusCloseButton`.

Jesse Greenberg  3:16 PM
It was historically necessary but isn't anymore. I tried to describe in https://github.com/phetsims/fourier-making-waves/issues/194#issuecomment-929620651 - it used to be that the focus highlight would appear as soon as focus() was called so we wanted to prevent that for mouse and touch input. But that is not the case anymore so isPDOMClicking checks shouldn't be needed either.

Chris Malley  3:18 PM
OK thanks, I think I’ll remove them then. Trying to pare it down to only what’s necessary, which seems to be calling `dialog.focusCloseButton()`.

**Comment by pixelzoom** [comment]
@jonathanolson and I worked on this via Zoom.  We're both on MacBook Pros, macOS 11.5, Chrome 94.  I see the problem, he doesn't.  The only difference we could identify is graphics card -- mine Intel, is Radeon.

@jonathanolson suggested using `preventFit: true` on the ScreenView.  This is a better alternative to `layerSplit: true` because it won't cause performance problems.  I verified that `preventFit: true` resolved the problem (at least on my system) so I'll proceed with that solution.

**Comment by pixelzoom** [comment]
Workaround applied in the above commit. @Nancy-Salpepi could you please confirm that this looks OK on your system?

**Comment by Nancy-Salpepi** [comment]
This looks fixed on the MacBook Air (OS 11.6 + chrome). @kathy-phet also mentioned that is occurred on Windows 10, but I do not have a Windows device to test.

**Comment by kathy-phet** [comment]
Fixed on my Windows device too!

**Comment by pixelzoom** [comment]
Great - thanks everyone! Closing.
