### ISSUE TITLE
For light sources, always hide virtual rays and disable the "Virtual Image" checkbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#216]
For light sources, always hide virtual rays and disable the "Virtual Image" checkbox.

This might make https://github.com/phetsims/geometric-optics/issues/209 a non-issue.

**Comment by pixelzoom** [comment]
Done, @arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom.
