### ISSUE TITLE
Optic dragging behavior

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#22]
Currently, different objects have different drag listener behaviors. The drag listener of the object has no offset when it is dragged, whereas the drag listener of the optic centers the optic on the cursor when it is dragged.

**Comment by sarchang** [comment]
optic behavior should match object

**Comment by sarchang** [comment]
I tried looking at how it was done for the source object, and based on what I read about the drag listener, I think the applyOffset in the options object of dragListener of the optic should be true, but that somehow makes the offset worse when dragging. I am also not sure what OFFSET_VECTOR is for in SourceObjectNode. @veillette

**Comment by veillette** [comment]
In the case of the opticNode, we need to find the offset between the position of the start press and the center of the optic. Once we have this information, we can offset the model position appropriately.

One way to resolve it is to change the dragListener in OpticNode to  

```
    // create a drag listener on the fill of the opticalElement
    let clickOffset;
    const dragListener = new DragListener( {
      start: event => {

        // click offset in model coordinate between the press drag and the center of the optic
        clickOffset = modelViewTransform.viewToModelPosition(
          this.globalToParentPoint( event.pointer.point ) ).minus( optic.positionProperty.value );
      },
      drag: event => {

        // position of the cursor in model coordinates
        const cursorModelPosition = modelViewTransform.viewToModelPosition(
          this.globalToParentPoint( event.pointer.point ) );

        const unconstrainedModelPosition = cursorModelPosition.minus( clickOffset );

        // constrained optic to merely move vertically
        optic.setVerticalCoordinate( unconstrainedModelPosition.y );
      }
    } );

```

**Comment by veillette** [comment]
there is no more offset on a drag. Closing
