### ISSUE TITLE
Leave "Optical Axis" label in same "screen coordinate" position when zooming out

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/geometric-optics#223]
The Optical Axis label started encroaching on other parts when I zoom out. It seems like it could basically stay where it is in screen coordinates and not have to move ever in the zoom in/out, and would look better. It would be less crowded by the lens, as the label would stay over to the left of the screen. The others have to really follow what they label: 
![image](https://user-images.githubusercontent.com/5096804/137249113-ab583b8f-b0db-4475-94a0-7cf2ce32fae5.png)

This suggestion is not for the prototype. 

@arouinfar - Thoughts?

**Comment by pixelzoom** [comment]
That not curently possible with the current implementation of labels.  I'm planning to reimplement labels to address a range of problems in https://github.com/phetsims/geometric-optics/issues/214.  I'll add this to that issue, and close this issue.

**Comment by pixelzoom** [comment]
Actually.... I'll just leave this issue open, but note that it's related to #214.

**Comment by pixelzoom** [comment]
Done in the above commit. Screenshots below showing each zoom level. Closing.

<img width="1122" alt="screenshot_1538" src="https://user-images.githubusercontent.com/3046552/151619119-551fa0af-3b6d-4750-9b8e-b094f86e0ed1.png">
<img width="1121" alt="screenshot_1539" src="https://user-images.githubusercontent.com/3046552/151619143-dbfd5889-8764-4fd2-9d56-bdb6af47a97f.png">
<img width="1121" alt="screenshot_1540" src="https://user-images.githubusercontent.com/3046552/151619150-9d7e56cf-246e-47e3-8bf5-3d7298e45a72.png">
