### ISSUE TITLE
To do: Check Projector Mode in the lecture hall

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/geometric-optics#225]
I would like to check to see how projector mode is working in a real classroom. So this is an issue to self-assign to me for when I'm on campus to check in the big lecture halls and see how the contrast is working. 

Not needed for the prototype.

**Comment by arouinfar** [comment]
For https://github.com/phetsims/qa/issues/723

**Comment by pixelzoom** [comment]
https://github.com/phetsims/geometric-optics/issues/275 is a prerequisite to this.
