### ISSUE TITLE
Convert to TypeScript.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#229]
At 10/14/21 quarterly planning meeting, @kathy-phet said that I should use this sim for coming up to speed on TypeScript.   That will involve converting the existing implementation to TypeScript, and is deferred until after we publish the prototype.

**Comment by pixelzoom** [comment]
All files have been converted to .ts, with these exceptions:

* geometric-optics-phet-io-overrides.js
* geometricOptics.js (see https://github.com/phetsims/chipper/issues/1138)
* geometricOpticsStrings.js (see https://github.com/phetsims/joist/issues/764)

There were a fair number of places where I had to use `any` and `// @ts-ignore`:

* I used `options?: any` until we settle on a pattern for options
* Most of the `// @ts-ignore` was for subclasses of Node that TS doesn't identify as subclasses of Node.

I added 86 comments of the form "TODO-TS" for things that still need to be completed.

**Comment by pixelzoom** [comment]
Here's a summary of the problems that I worked around using `any` and `// @ts-ignore`.

- [ ] `any` was used exclusively for `options` and `config`, as in `options?: any`.  I did this until we settle on a new pattern options and config.

- [ ] TS doesn't know that Image and Path are subclasses of Node. So attempting to access just about any field, or use an Image or Path were a Node is allowed (e.g. `addChild`) results in an error of the form `Property 'blah' does not exist on type 'Image'` or `Argument of type 'Image' is not assignable to parameter of type 'Node'`.  This required may `@ts-ignore` comments and could likely be addressed by adding Image to phet-types.d.ts.

- [ ] TS doesn't know about Node `pdomOrder`, `getPDOMOrder`, etc. This required a `@ts-ignore` comment and could likely be addressed in phet-types.d.ts.

- [ ] NumberProperty has `rangeProperty`, which is of type `{Property.<Range>|null}`. So doing something like `numberProperty.rangeProperty.value.min` results in the TS error "Object is possibly null".   This required many `@ts-ignore` comments, and can probably be addressed by confirming that `rangeProperty` exists in the client code.

**Comment by pixelzoom** [comment]
[1.1.0-dev.2]( https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.2/phet/geometric-optics_en_phet.html) was published shortly before the conversion to TS was started.

[1.1.0-dev.3]( https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.3/phet/geometric-optics_en_phet.html) was published after all of the above conversions were committed.

**Comment by samreid** [comment]
> So doing something like `numberProperty.rangeProperty.value.min` results in the TS error "Object is possibly null". 

The two solutions to this problem are:

a) if you are certain from other logic that the value is defined and you are OK with a runtime error if that assumption isn't met, you can use the `!` non-null assertion operator like: `numberProperty.rangeProperty.value!.min`.  I used that, for example, in https://github.com/phetsims/gravity-and-orbits/blob/086ee91dea720a536883d5010474d5d5e555800d/js/common/view/DraggableVectorNode.ts#L94

b) add conditional logic to handle the `Range` case separately from the `null` case.

**Comment by pixelzoom** [comment]
Thanks @samreid.  The general pattern that I used for NumberProperty's `rangeProperty` is:

```js
assert && assert( numberProperty.rangeProperty.value ), // {Range|null}
const range: Range = numberProperty.rangeProperty.value!;
// ... then use range
```

**Comment by pixelzoom** [comment]
A few another problem that I've encountered in LabelNode.js:

- [ ] `textNode.boundsProperty` is flagged with "TS2740: Type 'TinyStaticProperty' is missing the following properties from type 'Property ': id, units, _initialValue, validValues, and 58 more."

```js
const textNode = new Text( text, options.textOptions );
Property.multilink( [ textNode.boundsProperty, ... ], ... );
```

**Comment by zepumph** [comment]
Everything I see above seems like an accurate use of workarounds until we add typescript into common code. Good work. Thanks for keeping track of these.

**Comment by pixelzoom** [comment]
I decided to replace a few dozen `@ts-ignore` comments with one workaround. For example in SourceObjectNode.js:

```js
    const sourceObjectImage = new Image(...);

    //TODO-TS workaround, because of class Image extends Imageable( Node )
    const sourceObjectImageAsNode = sourceObjectImage as unknown as Node;
```

Then use `sourceObjectImageAsNode` wherever a Node is expected.

**Comment by pixelzoom** [comment]
TODO:

- [ ] `options` pattern throughout
- [ ] Should callbacks have a return type?
- [ ] Address `//TYPESCRIPT` comments

**Comment by pixelzoom** [comment]
In the above commits, I addressed `options` and `config`.  All `config` were converted to `options`, per https://github.com/phetsims/chipper/issues/1128#issuecomment-991033186. I'm fairly certain that these options will need more work, since I don't think the TS options pattern has fully matured yet.

**Comment by pixelzoom** [comment]
This is essentially done, so I'm going to close.

The last issue is a general one, https://github.com/phetsims/scenery/issues/1332, and has associated TODO comments in the code.
