### ISSUE TITLE
Toolbox for rulers

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#23]
Rulers should be draggable out of a toolbox in the top right corner of the sim.  The toolbox shows a miniature version of the horizontal and vertical rulers.  There will be a maximum of 1 horizontal and 1 vertical ruler in the sim at a time.  Rulers can be removed by dragging them back to the toolbox or by clicking the reset button.

See Energy Skate Park for an example with the measuring tape.
A more detailed description of the software design pattern: https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#creator-with-drag-forwarding

Remove checkbox for rulers in the control panel.

**Comment by sarchang** [comment]
@veillette I probably didn't do this correctly, but I was able to add a grey box/panel at the centerRight of the screen. I know it's supposed to be at the top right corner, but I didn't have time to look into offsets, since we already have the combo box at the top right. I also am pretty sure my use of Circle is incorrect. This commit is very bare bones and minimal, but I didn't have time to figure out more details. Looking forward to learning more and working on it further tomorrow!

**Comment by veillette** [comment]
FYI, you can see how a ruler icon is generated in https://github.com/phetsims/masses-and-springs/blob/2a19d39e1df86e4ca42e7e7044d951c1402819b4/js/common/view/ToolboxPanel.js#L83 

I dont know if we will need to mimap the image as well, but here is the issue for it: https://github.com/phetsims/masses-and-springs/issues/199

**Comment by veillette** [comment]
Here is a screenshot for reference:
![image](https://user-images.githubusercontent.com/7633344/121730432-a9b87580-cabd-11eb-9ea8-dd1223a5f0f1.png)

The width of the panel should match the box

**Comment by sarchang** [comment]
Need to consider the case where the user drags the ruler while changing the zoom level.

**Comment by veillette** [comment]
Our work is done here. CLosing
