### ISSUE TITLE
Issues with guides

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#230]
As I use the sim, I find the "guides" to be problematic. I am still not convinced this visualization adds much value to the sim, and now I am seeing the representation as confusing in several instances.

Even in the case of "marginal rays" scenarios occur where the guides do not seem to match up with anything and their meaning is neither clear or helpful to me

![guides1](https://user-images.githubusercontent.com/4051174/137379366-58aff075-cd19-4e71-a23b-b2e71884119d.PNG)

When not using the "marginal rays" the guides do not really line up with any particular ray, so again their meaning is unclear

![guides2](https://user-images.githubusercontent.com/4051174/137379451-71904834-12a8-4535-b3de-cfbbcb04000c.PNG)

I would recommend at minimum only having this representation available when in "marginal rays" mode, and figuring out how the guides can always at least line up with the rays. Personally, if it were solely my call I would remove this representation altogether, I do not see the guides being particularly helpful towards the learning goals, and being a PhET-specific representation I would guess the vast majority of educators would not notice their absence.

**Comment by pixelzoom** [comment]
I don't know the history of this feature, but understand that guides are a representation invented by PhET.   There does not seem to be a consensus on whether they are useful.  

There are definitely open issues related to the implementation, like https://github.com/phetsims/geometric-optics/issues/175.  So a potential cost savings would be to remove them.
 
Perhaps a compromise would be to make `?showGuides` default to `false`.  Teacher Tips could explain how to enable them, and teachers who find them to be useful could do so.

**Comment by KatieWoe** [comment]
I was a bit confused by this feature myself. It seemed to mostly line up with the marginal rays, but not exactly. It wasn't until I was told it was independent of object position that it made sense. It may help with concepts relating to how object position changes the image, but it isn't really clear right now that it is showing that.
