### ISSUE TITLE
Optic can be moved beyond vertical bounds when zooming

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#233]
@pixelzoom the optic can be moved beyond the vertical bounds at the default zoom by the following steps:

1. Zoom all the way out
2. Move the optic to a vertical extreme (downward in this case)
3. Zoom back in to the default zoom

You should see the following

![lens displaced](https://user-images.githubusercontent.com/4051174/137386289-dad27247-17e2-428b-abb0-d32651689d79.PNG)

Although this is a bug, it is easily recovered from by moving the optic. I think it is not necessary to fix for the prototype

**Comment by pixelzoom** [comment]
This does not happen for the objects or light sources, so I should do what is done there. Something like:

```js
    dragBoundsProperty.link( dragBounds => {
      sourceObject.leftTopProperty.value = dragBounds.closestPointTo( sourceObject.leftTopProperty.value );
    } );
```
