### ISSUE TITLE
Cueing arrows

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#234]
It might be useful to provide cueing arrows on the screen (or some other suggestion) to indicate the screen is moveable. Since usually images appear in the spot the screen appears, students may not quickly realize the screen is moveable (and for instance, placing the screen at the focal length can be useful for seeing things like near parallel rays will converge at the focal point).

**Comment by pixelzoom** [comment]
I would like to change the cueing arrows for objects, light source, and projector screen to this:

<img width="258" alt="screenshot_1353" src="https://user-images.githubusercontent.com/3046552/137389731-fc16487a-9f7c-44fc-aeea-c3689aa2dede.png">

**Comment by pixelzoom** [comment]
Since we seem to be adding cueing arrows to everything that can dragged...  Do we also need up/down cueing arrows for the optic?  I'm unclear on why we need cueing arrows for some things and not for others. 

My general preference is avoid cueing arrows.  I think they are appropriate for the second point, but would avoid using them for other things, and let the user discover that they are draggable.

**Comment by sarchang** [comment]
5 out of the 8 students that I interviewed did not discover that the object was draggable until considerably late in their exploration (or until I prompted them). In some cases, this hindered their progress in understanding what was going on (ex. if you don't move the object, it can be difficult to figure out the difference between marginal rays and principal rays). Dragging was much more intuitive with the lamp representation, though. Students also didn't really drag the optic much, but that didn't hinder their understanding for the most part. I think cueing arrows on the object, second source, and projection screen would be helpful.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed these items:

> - [ ] PhET-iO: Cueing arrows should be hidden if inputEnabledProperty is false
> - [ ] PhET-iO: needs to be able to disable cueing arrows feature (individually or all?)

There will be on `cueingArrowsEnabledProperty` (default `true`) that can be used to enabled/disable the cueing arrows _feature_ for the entire sim.  

If `cueingArrowsEnabledProperty` is set this to `false`, you will see no cueing arrows.

If `cueingArrowsEnabledProperty` is set to `true`, then cueing arrows will be visible (at the appropriate time) for any Nodes whose `inputEnabledProperty` is `true`.  If you set a Node's `inputEnabledProperty` to `false`, you'll never see cueing arrows for that Node.

**Comment by pixelzoom** [comment]
- [ ] Cueing arrows do not currently disappear when using the keyboard to drag.  I'll need to address that.

**Comment by pixelzoom** [comment]
The remaining work on cueing arrows is related to the Arrow objects.  #228 is a prerequisite for that work.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I like the consistency of using the same cueing arrows for all representations, so the behavior in master looks good to me. Closing.
