### ISSUE TITLE
Add support for alternative input.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#235]
Added at 10/14/21 quarterly planning meeting.

**Comment by pixelzoom** [comment]
In the above commits, I added keyboard support for the Object and first light source.  I also fixed the Projection Screen so that its cueing arrows are not included in the focus rectangle.

I have not done the second point of interest and the second light source. They are unfortunately combined in SecondPointNode.js, and I'm planning to address that elsewhere.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics/issues/235#issuecomment-944798294, @arouinfar has said:
> Because of the toolbox interaction of putting in/taking out, I think we'll need to use the grab/drag interaction for rulers. While the grab/drag interaction has been done in several sims (e.g. balloons in BASE, magnet in Faraday's Law, ruler in GFL) it's never been done in a context with a toolbox. The full-sized item appears when a toolbox icon is clicked and it must then be dragged away from the toolbox to stay in the play area. Similarly, to put the ruler away, it will need to be released over the toolbox. I don't see how this could work with the Fourier pattern.

After reviewing the toolbox implementation, https://github.com/phetsims/geometric-optics/issues/258#issuecomment-1000003519 revised this requirement, and said:
> ... I don't think this sim needs to use the GrabDragInteraction since we aren't supporting description/voicing. Grabbing items will add an extra keypress, and the benefit is a better screen reader experience, which isn't yet relevant.

So the current plan (as I understand it) is to use focus traversal to "select" all draggable UI elements. When descriptions are added to a future release, then we'll also change to GrabDragInteraction.

**Comment by arouinfar** [comment]
> In https://github.com/phetsims/geometric-optics/issues/235#issuecomment-944798294, @arouinfar said that we'd need GrabDragInteraction for the rulers:

To be clear, the quoted statement predates the pattern that @zepumph came up with which negates the need for GrabDragInteraction in the absence of description. 

> So the current plan (as I understand it) is to use focus traversal to "select" all draggable UI elements, including rulers. When descriptions are added to a future release, then we'll also change to GrabDragInteraction.

Yes, sounds good.

**Comment by pixelzoom** [comment]
Alt input support is complete. @arouinfar please review.

**Comment by arouinfar** [comment]
Alt input is working nicely in master, but there are few things that should be fine-tuned:

* Moving the elements in the play area is probably the most important thing for users to do, so I would start the focus order in there and, keeping the relative order the same as it is now. Roughly, the order would go:
  * Draggable elements in the play area (keeping same relative order)
  * Controls along the top of the screen (keeping same relative order)
  * Controls along the bottom of the screen moving top-down, left-to-right. This is mostly correct, but the toggle button's position isn't yet settled in #188 but we can adjust there.
  
* We should add support for the page up/down steps to the NumberControls. For Diameter and ROC, let's use 10 cm. For IOR, let's use 0.1.

Back to @pixelzoom.

**Comment by pixelzoom** [comment]
Traversal order has been adjusted as requested, including lightPropagationToggleButton.  Ready for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Traversal order looks good, all that's left is to add page up/down steps to IOR (0.1) and Diameter (10 cm).

**Comment by pixelzoom** [comment]
Sorry I missed the keyboard steps.  In addition to Page steps, we should also add Shift steps, and they should be the same as the spinner (arrow button) intervals.   Here's what is now implemented, ready for review:

```js
  RADIUS_OF_CURVATURE_DECIMAL_PLACES: 0,
  RADIUS_OF_CURVATURE_SPINNER_STEP: 1, // cm
  RADIUS_OF_CURVATURE_SLIDER_STEP: 5, // cm
  RADIUS_OF_CURVATURE_KEYBOARD_STEP: 5, // cm
  RADIUS_OF_CURVATURE_SHIFT_KEYBOARD_STEP: 1, // cm
  RADIUS_OF_CURVATURE_PAGE_KEYBOARD_STEP: 10, // cm

  INDEX_OF_REFRACTION_DECIMAL_PLACES: 2,
  INDEX_OF_REFRACTION_SPINNER_STEP: 0.01,
  INDEX_OF_REFRACTION_SLIDER_STEP: 0.05,
  INDEX_OF_REFRACTION_KEYBOARD_STEP: 0.05,
  INDEX_OF_REFRACTION_SHIFT_KEYBOARD_STEP: 0.01,
  INDEX_OF_REFRACTION_PAGE_KEYBOARD_STEP: 0.1,

  DIAMETER_DECIMAL_PLACES: 0,
  DIAMETER_SPINNER_STEP: 1, // cm
  DIAMETER_SLIDER_STEP: 5, // cm
  DIAMETER_KEYBOARD_STEP: 5, // cm
  DIAMETER_SHIFT_KEYBOARD_STEP: 1, // cm
  DIAMETER_PAGE_KEYBOARD_STEP: 10, // cm
```
