### ISSUE TITLE
Add support for UI sound.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#236]
Added at 10/14/21 quarterly planning meeting.

The plan is to add support for standard (common-code) UI components.  There is no plan to add sound (or do sound design) for sim-specific components or actions (like dragging the lens, object, light source, or projection screen).

**Comment by arouinfar** [comment]
@pixelzoom the sim sounds good in master. The only thing that is potentially missing is a sound related to the tools and toolbox. In Waves Intro, there is a sound whenever a tool is picked up and released (including when removing from/returning to toolbox). I doubt this sound has been generalized, but it sounds very similar to the toggle button sound so perhaps we could use that instead.

@kathy-phet @ariel-phet what do you think? Should there be a sound related to picking up/releasing the tools? If so, what do you recommend we use?

**Comment by pixelzoom** [comment]
I recall an earlier discussion where we said we were not going to add sounds (or do sound design) for custom draggable things that were not part of common code.  But if you want to go revist that...

* Do we need a sound when a tool is released?
* Does there need to be a sound when you press on an Object or the Projection Screen?  Is there also a sound when you release?

**Comment by pixelzoom** [comment]
From the first comment in this issue:
> There is no plan to add sound (or do sound design) for sim-specific components or actions (like dragging the lens, object, light source, or projection screen).

But if you want to go revist that decision...

* Do we need a sound when a tool is released?
* Do we need to be a sound for press (and release?) on an Object?
* Do we need to be a sound for press (and release?) on the Projection Screen?

**Comment by arouinfar** [comment]
Thanks for the reminder @pixelzoom! I'm comfortable with sticking with our earlier decision -- I just couldn't remember if it had been discussed or not. In that case, I think this issue is safe to close.
