### ISSUE TITLE
PhET-iO design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#237]
At 10/14/21 quarterly planning meeting, PhET-iO support was added for this sim.  Immediately after publishing the prototype, we should do an initial pass at PhET-iO design.  This will inform what needs to be changed as the sim is refactored and converted to TypeScript.

**Comment by pixelzoom** [comment]
This is now a duplicate of #278. Closing.

**Comment by pixelzoom** [comment]
Reopening, I closed the wrong issue.

**Comment by pixelzoom** [comment]
The sim is now feature complete, ready for PhET-iO design and review.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/geometric-optics/issues/348#issuecomment-1054978135:
> > I know we don't spend a bunch of time on the data stream these days, but this is quite obnoxious.
> ...
> There has been no time spent on it so far for this sim. I'm waiting for feedback on PhET-iO instrumentation for https://github.com/phetsims/geometric-optics/issues/237 from @arouinfar and @kathy-phet. That feedback should include data stream and the State Wrapper.

I get the impression that most of the design time is being spent on Studio and "features".  So a reminder that, while we're not spending a lot of time on the data stream, designers need to include some level of data-stream testing and feedback in the iO design process.

**Comment by arouinfar** [comment]
I don't have any remaining PhET-iO design comments for Geometric Optics, so I think we can go ahead and close this issue. 

The only remaining design work is phetioFeatured overrides, but I've opened a separate issue for that.
