### ISSUE TITLE
Representation for focal points.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#238]
I'm wondering about the representation that we're using for the focal points.  We're currently placing a yellow '×' at the focal points:

<img width="482" alt="screenshot_1364" src="https://user-images.githubusercontent.com/3046552/137405165-aefd94bd-77b6-493d-a055-929c59f09488.png">

All of the representations that I've encountered place a point at the focal point (it's a point!)  I have never seen '×' used. Also, the focal point is typically labeled "F", while the focal length is labeled "f".   For example, see the diagrams at https://en.wikipedia.org/wiki/Focal_length.  

Should we use a more standard representation?  Would showing the symbols "F" (and "f"?) support learning about the fundamental equations involved in optics? And understanding the difference between "F" and "f"?

@arouinfar @ariel-phet thoughts?

**Comment by ariel-phet** [comment]
I would certainly be fine having the focal points be points, a bright yellow dot there might be just fine (and as you "point" out a point is a more standard representation).

As for labels, I think having the full words is actually appropriate in this case. I have seen a fair number of labels for focal length, so I don't think that is particularly standard. The full words work and so no need to disambiguate here.

**Comment by pixelzoom** [comment]
I've implemented the "point" representation that we discussed for focal points.  See screenshots below comparing the new and old representations.  I like the new representation quite a bit, and it feels easier to measure focal length with the ruler.

@arouinfar @kathy-phet @ariel-phet please weight in.

<img width="1184" alt="screenshot_1419" src="https://user-images.githubusercontent.com/3046552/140844755-b117ae24-0ef8-4a5a-8204-404a7d712fc4.png">

<img width="1184" alt="screenshot_1420" src="https://user-images.githubusercontent.com/3046552/140844767-a62154f8-d0d0-400d-b3a9-d25a4dea5d04.png">

**Comment by ariel-phet** [comment]
@pixelzoom I definitely prefer the new representation. If we go with it, I think we might want to reduce the diameter a bit. I think the ideal would be to make the outer diameter of the yellow annulus as small as we are comfortable with (we might already be at that limit, although I think it could be a bit smaller, but might be something we just "tune" live quickly).

**Comment by kathy-phet** [comment]
I am OK with the points, but one thing that seemed a bit better with the X is seeing the ray pass through the dead center of the mark. With the points, its' harder to see that. I think it might help to have the ray pass on top of the point, so you can see it passes right over the black center spot, and to have the black spot just 1-2 pixels wider than the ray itself so it peaks through from the background.

**Comment by pixelzoom** [comment]
@kathy-phet Good idea, I've move the focal points behind the rays. Rays currently have `lineWidth: 2`, while black center of a focal point has a diameter of 4.  My preference would be a tad larger for the black center.

@ariel-phet Current size of the focal points was based on the size of the 'x' representation, which felt about right to me. The yellow part of the focal point has diameter 14, black center has diameter 4.  Smaller for either of these felt too small to me. Let me know how how you'd like to change these.

**Comment by ariel-phet** [comment]
@pixelzoom sounds good regarding the size if you already did some optimization.

**Comment by pixelzoom** [comment]
Here are some screenshots showing various diameters, showing how it looks when rays do (and do not) intersect the focal points.  

Diameter 4 actually looks best to me. It's just a bit wider than the ray lineWidth, so you can see where the center of the point is.  But it's not large enoung that the point starts to look like a donut/ring instead of a point - which is the problem that I have with diameter > 4. 

@kathy-phet thoughts? And still waiting to hear from @arouinfar.

Diameter = 4:

<img width="1182" alt="screenshot_1430" src="https://user-images.githubusercontent.com/3046552/140964346-5bbc9899-c10d-433c-a0f9-3e4ba10ee661.png">
<img width="1182" alt="screenshot_1431" src="https://user-images.githubusercontent.com/3046552/140964352-378b3739-f925-483b-abe8-f4da90115004.png">

Diameter = 5:

<img width="1184" alt="screenshot_1428" src="https://user-images.githubusercontent.com/3046552/140964128-3ddced57-6830-4abe-8ac6-c79e25504bef.png">
<img width="1183" alt="screenshot_1429" src="https://user-images.githubusercontent.com/3046552/140964135-2aadea02-34ec-49f1-9c44-ea6897999e23.png">


Diameter = 6:

<img width="1185" alt="screenshot_1426" src="https://user-images.githubusercontent.com/3046552/140963826-b125fdcd-6659-4aa3-93b0-f4432ff96a40.png">
<img width="1181" alt="screenshot_1427" src="https://user-images.githubusercontent.com/3046552/140963840-ed16c212-c145-4feb-a409-dcd9ee102a81.png">

**Comment by kathy-phet** [comment]
Thanks for the screenshots. I agree, 4 looks better than 6.
