### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#24]
We need text labels for:
- object
- image
- focal point
- type of optic (convex/concave, lens/mirror)

Checkbox for labels in control panel.
Labels should be centered beneath the object being labeled.  White-colored text on label should have a semi-transparent background so that it is visible on top of white rays.  Labeled should not scale with zoom options.  Font size should remain the same throughout all zoom levels, but position of label should move as the objects scale.

See Vector Addition for example for how to do the label backgrounds.

**Comment by veillette** [comment]
Let's try to break down how to start oing this.
- [ ] create a boolean property in visibleProperties
- [ ] Add a checkbox for labels in control panel.
- [ ]  create a scenery Node for the labels in GeometricOptics view folder
- [ ]  attach it to GeometricOpticsScreenView 

The constructor for the scenery node will need
 - [ ] the appropriate boolean visible property
 - [ ]  the modelviewTransform
 - [ ]  the zoomLevelProperty
 - [ ]  the position property of  all the "objects"
 - [ ]  options
 
As a first pass, we should try to make it work for the current zoomLevel, and then we can comeback to it later, and address the positioning of the labels with zoom.

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/122081659-497f4780-cdcd-11eb-8cc5-cdafef278abf.png)

**Comment by veillette** [comment]
Our approach to create labels within the playArea layer failed. It turns out to be impractical to counteract the effect of the zoom. There are too many parameters to update: margin, fontsize, corner radius.

It will be more practical to attach the labelsNode directly to the GeometricOpticsScreenView and find a way to position the labels accurately.

**Comment by veillette** [comment]
One thing we have not discussed is what to do with labels with a light source and a projector screen. 
Label for discussion to the design meeting.

**Comment by veillette** [comment]
As part of the work in #39, we have created a modelview transform that maps easily between the coordinates of different zoom level . The previous commits allows us to reposition the labels based on the modelviewTransform

**Comment by sarchang** [comment]
1. what to do with labels with a light source and a projector screen
2. background color/size of labels

**Comment by sarchang** [comment]
No labels needed for light source/projector screen (test during interviews)

- [ ] Hoist background color to color profile
- [ ] Label text size should be bigger

**Comment by sarchang** [comment]
Still need to adjust position of object label

**Comment by sarchang** [comment]
I think we're finally done with the labels. Ready for review by @veillette

**Comment by sarchang** [comment]
Actually the image label should be attached to the TargetNode instead of the target model position so that it is always below the picture frame

**Comment by veillette** [comment]
Adding bounds to the target model should allow the positioning of the label.

**Comment by veillette** [comment]
Both target and sourceObject have model bounds that can be used to position the label accurately without ad hoc values. Closing
