### ISSUE TITLE
Low intensity light spot is difficult to see on white projection screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#240]
For phetsims/qa#723

A low intensity light spot is difficult to see on white projector screen. @arouinfar and I discussed this on Zoom, and came up with a solution which should (hopefully) be non-controversial. 

We'll add a thin, gray, dashed line around the spot. The opacity of this line will be inversely related to the intensity of spot, so it will fade out as the spot becomes more pronounced.  This dashed line will have its own color in the color profile.

We'd like to do this for the prototype.

Here's an example of how it will look, for default and projector color profiles:

<img width="1272" alt="screenshot_1369" src="https://user-images.githubusercontent.com/3046552/137559576-23f3f612-1cec-49ec-9596-3f9a9d758c21.png">

<img width="1271" alt="screenshot_1367" src="https://user-images.githubusercontent.com/3046552/137559582-ed880b97-31a7-4bfc-b69c-370e70ae4822.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I think this looks really nice in master and is good for the prototype.
