### ISSUE TITLE
Index of refraction and Diameter are normalized differently.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#242]
Optic.js is the base class that implements the model for the lens and mirror. It has methods for converting index of refraction and diameter to normalized values, in the range [0,1].

Normalized index of refraction (IOR) is used to set the opacity of the fill used for the lens/mirror. For lens, it's computed like this:

```
range = [1.2,1.9]
normalizedValue = ( value - range.min ) / ( range.max - range.min )
```

... so we will get opacity values across the full range [0,1].

Normalized diameter is used to set the opacity of the Image (real or virtual). It's computation is totally different than index of refraction. For lens:

```
range = [30,130]
normalizedValue = value / range.max
```

So the opacity of the Image ranges from [0.23,1], not [0,1].

So 2 questions:

(1) Is this difference in normalization computations indeed desired? 

(2) These are both scaling to a unit vector, but in very different ways. Should I rename one of these to something other than "get normalized..." ?

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet.  

Normalization of diameter is fine, because we do not want the image to disappear (opacity=0).  

Normalization of IOR is not OK - the lens should not be fully transparent at min value. It does not match the IOR of air, so it should have some blue tint to it at 1.2.

Naming the methods differently might be a good idea, but is an internal code thing, not public facing.

**Comment by ariel-phet** [comment]
@pixelzoom I checked on master, looks good. It looks to be the right opacity on projector mode. It is a bit harder to tell there is a tint when not in projector mode, but it is there, and I do not think it is worth trying to tune more than the current behavior for the prototype.
