### ISSUE TITLE
Use a different term than "play area".

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#243]
This sim uses the term "play area" for something that doesn't equate to the a11y "play area".  And in fact, it creates a Node named `playAreaNode` in its ScreenView, confusing because every ScreenView has (by default) an instanceof `PlayAreaNode`, which is something entirely different.    

Things that are in this sim's notion of "play area" are all of the things that scale when you press the zoom in/out buttons.

Suggestions for a different name for this?

**Comment by pixelzoom** [comment]
> Things that are in this sim's notion of "play area" are all of the things that scale when you press the zoom in/out buttons.

How about "zoom area"?

**Comment by arouinfar** [comment]
Maybe "Experiment Area"? Though "Zoom Area" is also works and might make more sense in this context.
