### ISSUE TITLE
Enable PhET-iO validation and state testing.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#248]
Remove this from package.json:

```js
    "phet-io": {
      "validation": false
    },
```

And remove geometric-optics from perennial/data/phet-io-state-unsupported.

**Comment by pixelzoom** [comment]
As of right now, the sim is passing `?phetioValidation`, and I’m not seeing any problems in the State Wrapper.  After I knock off a couple of more gnarly features, I'll probably turn these back on.

**Comment by zepumph** [comment]
I think that makes sense for phetioState. As for phetioValidation, I think it will only help you implement the gnarly features. Whatever you think is best.

**Comment by pixelzoom** [comment]
PhET-iO validation and state testing have been enabled. I'll leave this issue open until I've verified that there are no major CT problems.

**Comment by pixelzoom** [comment]
CT looks happy after a couple of cycles, so closing.
