### ISSUE TITLE
Add an Intro screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#253]
Related to #231 ...

10/21/2021 design meeting: @arouinfar @kathy-phet @ariel-phet

Design a new Intro screen, where the user can directly set focal length.  This screen features a couple of objects, a lens, and a NumberControl for focal length.  Other controls will be sparse. 

We'll also need a screen icon.

**Comment by pixelzoom** [comment]
As I started to implemented this screen, I realized that's it has very minor differences from the Lens screen.  It makes me wonder what we're "introducing" and what the goals are. When the option to set focal length directly is enabled for the Lens screen, the only things different about the Intro screen are: no concave lens, no second point.  If that's indeed enough of a difference, that's fine.  But I think we should circle back to the design process, identify learning goals for the Intro screen, and then reevaluate our design.

@arouinfar thoughts?

**Comment by arouinfar** [comment]
Looking at various [science education standards](https://docs.google.com/document/d/1hVxM-ax2UyxctbclAhutrRad5A0eeLWKFQNB4U7ls4o/edit#heading=h.wpvsqzwyqiy5), I think this sim could be used in middle school. Rather than a somewhat-redundant Intro screen, we should perhaps instead consider a Basics version of the sim. I'll tag for discussion at design meeting.

**Comment by pixelzoom** [comment]
Discussed at 11/11/21 design meeting:

* Remove Intro screen from this sim.
* @arouinfar will work on design of a Basics sim, with the goal of reusing this sim.
* @pixelzoom will revise the language for the Focal Length control in the Options dialog, now that it applies to all screen.

**Comment by pixelzoom** [comment]
I have remove the Intro screen and revised the Focal Length option in the Options dialog (screenshot below).

Design for the Basics version is being tracked in https://github.com/phetsims/geometric-optics/issues/270.

Closing.

![screenshot_279](https://user-images.githubusercontent.com/3046552/141377432-cb373e28-2279-4b0e-b9c8-1f3b13e9b354.png)
