### ISSUE TITLE
Make focal length settable via the UI.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#255]
Related to https://github.com/phetsims/geometric-optics/issues/231 ...

10/21/2021 design meeting: @arouinfar @kathy-phet @ariel-phet

Change the model so that Optic focalLengthProperty can be changed. 

When changing focalLengthProperty, use a fixed IOR (1.5, glass) and vary the ROC.

**Comment by pixelzoom** [comment]
Brainstorming notes for myself... Here's a sketch of an idea for implementing this feature.

Create different models for direct vs indirect methods of setting focal length:

```ts
interface FocalLengthModel {
  readonly radiusOfCurvatureProperty: IReadOnlyProperty<number>;
  readonly indexOfRefractionCurvatureProperty: IReadOnlyProperty<number>;
  readonly focalLengthProperty: IReadOnlyProperty<number>;
}

class DirectFocalLengthModel {
  readonly radiusOfCurvatureProperty: IReadOnlyProperty<number>;
  readonly indexOfRefractionCurvatureProperty: IReadOnlyProperty<number>;
  readonly focalLengthProperty: IProperty<number>;
  constructor(...) {
    this.focalLengthProperty = new NumberProperty(...);
    this.indexOfRefractionCurvatureProperty = new DerivedProperty( [this.focalLengthProperty ], ... );
    this.radiusOfCurvatureProperty = new DerivedProperty( [this.focalLengthProperty ], ... );
  }
}

class IndirectFocalLengthModel {
  readonly radiusOfCurvatureProperty: IProperty<number>;
  readonly indexOfRefractionCurvatureProperty: IProperty<number>;
  readonly focalLengthProperty: IReadOnlyProperty<number>;
  constructor(...) {
    this.indexOfRefractionCurvatureProperty = new NumberProperty(... );
    this.radiusOfCurvatureProperty = new NumberProperty(... );
    this.focalLengthProperty = new DerivedProperty( [ this.indexOfRefractionCurvatureProperty, this.radiusOfCurvatureProperty ], ... );
  }
}
```

Optic is wired up to an instance of either DirectFocalLengthModel or IndirectFocalLengthModel, and can be mutated via `setFocalLengthModel( focalLengthModel : FocalLengthModel )`. 

There is a difference control sub panel for DirectFocalLengthModel vs IndirectFocalLengthModel, and we should whichever one is currently being used by Optic.

The challenges with supporting a flat mirror in #227 could likely be addressed by creating `FlatMirroFocalLengthModel`, which has infinite focal length and infinite ROC.  (IOR is irrelevant for the mirror.)

These extra models and control panels would certainly appear in PhET-iO, but I think that OK, and maybe even superior.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

Support for 'direct' vs 'indirect' methods of setting focal length was added in the above commit.   This work went relatively smoothly, using the design that I outlined in https://github.com/phetsims/geometric-optics/issues/255#issuecomment-1043890392. I did hit one major snag: I discovered that a sign was baked into `focalLengthProperty`, and the sign was used to indicate where the optical image was formed.  That made it impossible to set `focalLengthProperty` directly.  So I factored the sign out into `signedFocalLengthProperty` (currently not PhET-iO instrumented) and used that wherever the sign was significant (in OpticalImage.js and the ray tracer).

Describing this feature at a high level... The sim switches between 2 different focal-length models, based on the setting of the associated radio buttons in _PhET Menu > Options_.    The 2 focal-length models behave as follows:

`directFocalLengthModel`:  focal length is settable, IOR is fixed, ROC is derived
`indirectFocalLengthModel`: ROC and IOR are settable, focal length is derived

Since these models have state, they are PhET-iO instrumented, and therefore appear in the Studio tree. Here's what the tree looks like for `model.lens`; `model.mirror` is similar:

<img width="291" alt="screenshot_1563" src="https://user-images.githubusercontent.com/3046552/155008230-694e2395-075b-4618-8fcd-57c63548f78a.png">

Note that `lens.radiusOfCurvatureProperty`, `lens.indexOfRefractionProperty`, and `lens.focalLengthProperty` are derived Properties, and they are simply synchronized with the corresponding Properties in whichever focal-length model is currently selected.

One deviation from the specification... For the direct model, we had previously decided to use a fixed IOR of 1.5.  That seemed problematic for the Mirror, where IOR was fixed at 2.0 for the indirect model.  In Mirror.js:

```ts
// Although a mirror does not have an index of refraction, its focal length is equivalent to a lens
// with an index of refraction of 2.
const INDEX_OF_REFRACTION = 2;
```

So unless I hear otherwise, the lens uses a fixed IOR of 1.5 for the direct model, while mirror uses a fixed IOR of 2.0 for _both_ direct and indirect models.   @arouinfar let me know if that's OK.

Focal-length range is currently [30,130] for lens, [75,125] for mirrors, as requested.  That will need to change based on the 2.0 IOR for mirrors, and the adjustments to be made in https://github.com/phetsims/geometric-optics/issues/311.

**Comment by pixelzoom** [comment]
@ariel-phet it would also be nice if you could review this feature.

**Comment by pixelzoom** [comment]
Another issue I just recalled that came up...  Opacity of the lens is determined by IOR.  When we switch to 'direct' model, IOR  is fixed at 1.5, so it's opacity does not change as focal length is adjusted.  Is this OK, or do we need to change how lens opacity is computed?

**Comment by pixelzoom** [comment]
> So unless I hear otherwise, the lens uses a fixed IOR of 1.5 for the direct model, while mirror uses a fixed IOR of 2.0 for both direct and indirect models. @arouinfar let me know if that's OK.

Discussed with @arouinfar, 2.0 is fine for Mirror. But will need to be considered when adjusting ranges in #311.

> ... Is this OK, or do we need to change how lens opacity is computed?

This is OK. We're not changing the material of the lens.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar a couple of quick comments

1. I agree, the IOR should be fixed when adjust the focal length, that seems like a good assumption and more related to potential learning goals associated with how the lens of the eye works.

2. For the diverging lens (and I believe diverging mirror) we probably should display the numbers as negative numbers, since that is the convention for such optics.

**Comment by pixelzoom** [comment]
>  For the diverging lens (and I believe diverging mirror) we probably should display the numbers as negative numbers, since that is the convention for such optics.

That's not at all possible with the current implementation -- I would have need to know that up front, and it would have been a different implementation.  @arouinfar and I did discuss this, and noted that we not using the negative-number convention for Focal Length or ROC.

**Comment by pixelzoom** [comment]
Discussed the previous comment with @arouinfar and @ariel-phet.  Change requests:

* Add + and - to "Focal Length" and "Radius of Curvature" labels, like "Focal Length (+)"
* Instrument `signedFocalLengthProperty`
* Create and instrument `signedRadiusOfCurvatureProperty`
* Add generous `phetioDocumentation` to focal length and ROC Properties, to distinguish between magnitudes and signed values.

**Comment by pixelzoom** [comment]
Change requests completed in the above commits. 

The labels on the Focal Length and ROC controls now have (+) and (-) suffixes, as requested.

But as I got into this, I found a better way to organize the Properties.  The focal-length models now have "magnitude" Properties `focalLengthMagnitudeProperty` and `radiusOfCurvatureMagnitudeProperty`, documented like this:

<img width="768" alt="screenshot_1564" src="https://user-images.githubusercontent.com/3046552/155038830-1abbcd4b-b2c8-4e9c-90e3-409f864c6621.png">

<img width="768" alt="screenshot_1565" src="https://user-images.githubusercontent.com/3046552/155038841-b4608b19-5e25-4351-bd61-e432a524ed65.png">

The optics (`model.lens` and `model.mirror`) then have `focalLengthProperty` and `radiusOfCurvatureProperty`, which are signed values, and are documented like this:

<img width="764" alt="screenshot_1566" src="https://user-images.githubusercontent.com/3046552/155038941-a9caebe4-3241-43f4-83f9-679eb88de055.png">

<img width="761" alt="screenshot_1567" src="https://user-images.githubusercontent.com/3046552/155038947-c76e0f42-c3d8-4b9a-aee9-da7b0ac21eb4.png">

@arouinfar @ariel-phet ready for review.

**Comment by ariel-phet** [comment]
@pixelzoom the changes look good and I think that will avoid any complaints about the signs of the values.

I also think the PhET-iO changes make sense, that should allow someone to easily retrieve the signed value if needed for a data table or such.

**Comment by arouinfar** [comment]
@pixelzoom @ariel-phet I really like the `(+)` and `(-)` in the NumberControl titles and the updated properties look brilliant.
