### ISSUE TITLE
Add a parallel light source.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#256]
10/21/2021 design meeting: @arouinfar @kathy-phet @ariel-phet

This feature was suggested by @ariel-phet.

We decided not to do this because:

* Some of the Rays modes do not work
* Bending Light has a similar feature
* This feature should probably be in Optics Lab

**Comment by oliver-phet** [comment]
Just documenting a user request (if this happens in "Optics Lab", we should let this user know):

> I'm a huge PhAN of PhET, and I would really appreciate a tweak to the lens lab. It would help so much to have an object representing the sun, an infinite distance away.  That's the best way to demonstrate how parallel rays go through a focus. You could even light a little virtual fire at the focus point.

**Comment by kathy-phet** [comment]
@oliver-phet - It's possible to get to this idea by using the zoom out button to zoom way out and then move the point source far away... it's great for showing the trend that the lines get closer to parallel, and get closer to passing through the focus. This is why we made the zoom out possible. 
![image](https://user-images.githubusercontent.com/5096804/235487402-461a9d4d-8f44-47e0-bb70-19042ed7aec5.png)

**Comment by oliver-phet** [comment]
Nice, I'll send that to the user!
