### ISSUE TITLE
Sound support for sliders.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#259]
Similar to https://github.com/phetsims/fourier-making-waves/issues/56, we're adding UI sounds to this sim.
Many of the important controls in this sim are sliders. And `Slider` currently does not have a sound API, see https://github.com/phetsims/sun/issues/697. 

Assigning to @kathy-phet and @arouinfar to decide whether to prioritize sound for sliders, or to publish this sim without slider sounds.

**Comment by jbphet** [comment]
Generalized support for sound in sliders has been initially implemented, see https://github.com/phetsims/sun/issues/697.  In this particular sim, the default sound generation seemed a little suboptimal because the clicks didn't always occur in conjunction with the quantized slider jumps, so I did some customizations to make them match, see https://github.com/phetsims/geometric-optics/commit/eb0e48814419fd8b4dbb36597f25e04963030503.

Assigning to @arouinfar and @pixelzoom to try this out and see if they are comfortable with how this behaves and provide me with feedback if not.

**Comment by arouinfar** [comment]
Thanks @jbphet. Things generally sound pretty good. Connecting the clicks to `constrainValue` seems reasonable, but the result is that sliders with a larger range (like Radius of Curvature on the Mirror screen) may sound a bit clickier than others. I don't know that it's something we need to specifically change, but it was noticeable to me.

There does seem to be a bug with keyboard nav. Adjusting the slider with the keyboard does not generate any sounds.

**Comment by pixelzoom** [comment]
> * With the Focal Length slider, the slider moves in increments of 5, but I'm only hearing sound when the value is a multiple of 10. 

Fixed in the above commit. `soundGeneratorOptions.numberOfMiddleThresholds` was missing for FocalLengthControl.ts.  That's understandable because it's only visible in the UI if you switch to "direct" in PhET>Options.

**Comment by pixelzoom** [comment]
Instead of loading up this sim-specific issue with general comments... I'm adding more general comments to https://github.com/phetsims/sun/issues/697.

**Comment by jbphet** [comment]
> There does seem to be a bug with keyboard nav. Adjusting the slider with the keyboard does not generate any sounds.

It worked when I assigned this issue to you, but `Slider.js` was changes to TypeScript in the mean time, and it broke this functionality.  I've committed a fix, and will review it with the developer who did the conversion.

**Comment by jbphet** [comment]
@pixelzoom asked above:
> Will the implementation for alt input make use of options `keyboardStep`, `shiftKeyboardStep`, `pageKeyboardStep`?

Not at this time.  In our previous custom implementations of sound for sliders, the sound has *always* been generated for a keyboard-based change, so these values are irrelevant.  The code just produced a sound every time the user did a keyboard-based drag that caused a value change.  I've gone with that same approach in the generalized code.

He also asked:
> Will `soundGeneratorOptions` apply to both mouse/touch and keyboard input?

Yes.

**Comment by pixelzoom** [comment]
I verified that alt input is working nicely with slider sound.

@jbphet and I paired on slider sound for awhile today.  It's looking very nice.  While there are certainly additional features and issues to address, what's there now is enough to support the release of Geometric Optics.

**Comment by pixelzoom** [comment]
Since sound support for sliders is now sufficient for the needs of this sim, I'm going to close this issue.  Overall review of UI sound for this sim is being tracked in https://github.com/phetsims/geometric-optics/issues/236.  And general work on slider sound will continue in https://github.com/phetsims/sun/issues/697.
