### ISSUE TITLE
Adjust ranges of ROC and Diameter for Mirror Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#261]
Discovered in #255 

The range of focal lengths for the mirror screen is currently ±75-125 cm which is quite a bit smaller than the range on the Lens screen. The diameter ranges are also different across the two screens. 

I'll experiment locally.

**Comment by arouinfar** [comment]
@pixelzoom let's go with these values for the mirrors.

```js
radiusOfCurvatureRange: new RangeWithValue( 150, 300, 200 ),
diameterRange: new RangeWithValue( 30, 130, 80 ),
```

The diameter range will now be the same for lenses and mirrors. I've increased the ROC range a bit so that it'll be possible to double the focal length of a mirror.

**Comment by pixelzoom** [comment]
Mirror ranges were adjusted in the about commit. @arouinfar please review in master, feel free to close.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom
