### ISSUE TITLE
Optic should have a fixed position of (0,0).

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#262]
@arouinfar mentioned that she had a design discussion with @ariel-phet and @kathy-phet (related to #237 PhET-iO design?).  There is a proposal to make the optic have a fixed postion.

High priority to make a decision about this.  I've already spent a considerable amount of time rewriting the DragListener for the optic, and adding alt input.   If it's position is fixed, that work can be deleted.

**Comment by pixelzoom** [comment]
The optic now has a fixed position of (0,0).    The straightforward approach would have been to delete `{Property<Vector2>} positionProperty` and replace it with `{Vector2} postion`.    But I chose to keep `positionProperty`, make it `phetioReadOnly: true`, and limit it to the single value `(0,0)`.  My reasons for doing this are:

(1) The current implementation supports a movable optic, and I don't see value in ripping that out.
(2) My intuition tells me that a movable optic may be desired in the future. 
(3) Implementing position as a Property encourages other parts of the sim implementation to treat it as mutable, and not make bad assumptions that it's at (0,0).
(4) It is useful for PhET-iO, as a means of documenting that the optic is located at (0,0).

Discussed with @arouinfar and she agreed that this sounds like a good approach. 

@arouinfar please review in master, and be sure to have a look at `lens.positionProperty` and `mirror.positionProperty` in Studio.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Everything looks good in Studio.
