### ISSUE TITLE
"Mask" that can remove some of the rays

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#264]
Originally mentioned in https://github.com/phetsims/geometric-optics/issues/4, but I don't find the info there useful, so opening a new issue.

Slack conversation on 11/3/21:

Kathy Perkins  3:12 PM
I was showing off the Geometric Optics sim to Carl today - he was saying very nice. He had a feature request that he really wanted ... and it was on our initial feature wish list during summer discussions that somehow fell off the radar when we reviewed the remaining features and I hadn't remembered it.
@arouinfar - It was have the "mask" that can remove some of the rays. If we do it, I think it would need to be highly constrained and that you can move just up and down in front of the lens? Can we talk through that one at a future meeting?

Amy Rouinfar  3:15 PM
We considered a mask at one point, but decided that it was better-suited to Optics Lab.
We can certainly talk through it for Geometric Optics since the scope of that sim has expanded a great deal, but it probably depends on publication timeline, budget, and CM’s next project.

Kathy Perkins  3:36 PM
Yes, and the difficulty given the model.

Ariel Paul  3:50 PM
It would only work with Many Rays
+1 @arouinfar 

Chris Malley  9:12 PM
GitHub issue https://github.com/phetsims/geometric-optics/issues/4 mentions “As part of the design discussion, a mask has been considered as an addition to the simulation” but doesn’t adequately (for me, anyway) describe the feature, or the design discussion.  I’ll create a new issue to discuss — if you’re at all interested in having the sim support this feature (now, or in the future) it’s important that I understand it.

**Comment by pixelzoom** [comment]
Assigned to @arouinfar.  Let's start by scheduling some time when you and I can meeting on Zoom, so that you can explain this feature to me.

**Comment by arouinfar** [comment]
@pixelzoom the quick version is that a mask blocks the light rays. If we introduce a mask in front of the optic, it would dim the image (somewhat similar to reducing its diameter). If the mask fully blocks the optic there won't be an image. You can see a rough implementation of a mask in optics-lab. Here's a fan source with a mask: 
![image](https://user-images.githubusercontent.com/8419308/140397094-380c20b2-3e51-4e7e-abcb-50aab6afb745.png)

I don't think the mask will work with the Principal or Marginal ray representations. For example, if a mask covers the lower half of this lens, only the top ray would appear to go through the lens. A single ray is not sufficient to identify the image location.
![image](https://user-images.githubusercontent.com/8419308/140399562-128ea99c-6056-495f-a178-b7a22f028429.png)

We can also run into similar situations for Many rays. If we suppose the lens is 75% occluded by the mask, only one ray will appear to travel through the lens. It will definitely take some design work to figure out the necessary constraints to support this feature.
![image](https://user-images.githubusercontent.com/8419308/140399925-e76b99ab-4ee2-4a35-89de-10eaf8a4c9c1.png)

**Comment by pixelzoom** [comment]
@arouinfar thanks for the explanation.

Does Geometric Optics need to support this feature (now or in the future), or will this be handled in another sim (like Optics Lab) ?  It's not clear to me from the Slack discussion in https://github.com/phetsims/geometric-optics/issues/264#issue-1044321614.

**Comment by pixelzoom** [comment]
11/11/21 design meeting: @arouinfar @kathy-phet @arouinfar @markgammon @KatieWoe 

We discussed this feature, did some brainstorming, and ultimately concluded that it can't be included in this sim.   The sim is too far along, and it presents too many complications and challenges.

@arouinfar Would you like to add any additional notes?

**Comment by arouinfar** [comment]
Here are some reasons why we decided against including a mask:

* The mask can create problems with the ray representations, as it can block many/most of the incoming rays. There should be at least two intersecting rays to form the image. For Marginal and Principal rays, occluding 50% of the optic could block 2/3 of the rays. Furthermore, the Principal rays for an off-axis object may not even intersect the optic, creating additional complications.
* The mask poses design challenges with the mirrors. How should we handle rays that are reflected onto the back of the mask?
