### ISSUE TITLE
Specify type parameters to AquaRadioButtonGroups

### ISSUE THREAD

**Issue by samreid** [phetsims/geometric-optics#265]
In https://github.com/phetsims/sun/issues/728, I converted AquaRadioButtonGroup and its sun subtypes to be parametric.  This means we can supply the types in geometric optics, and get type checking.  I'll update that shortly.

**Comment by samreid** [comment]
Fixed in the commit.  I used `as unknown as Node` so the `Text` labels would type check.  I used `new VerticalAquaRadioButtonGroup<'direct' | 'indirect'>` because I didn't see an enumeration for direct vs indirect.  I added `as const` so it would know those strings could match as members of that enum (this workaround was the most sketchy of the batch).  @pixelzoom can you please review?  Any of these workarounds can be converted to ` // @ts-ignore` at your discretion.  Close if all is well.

**Comment by pixelzoom** [comment]
@samreid said:
> I used as unknown as `Node` so the `Text` labels would type check. 

`class Text extends Node` so there should be no need to do this.  And the `Node` that you're referring to in `as Node` is not scenery.Node, it is the built-in Node.  This problem is more generally described in https://github.com/phetsims/chipper/issues/1142.  I'm also wondering if you introduded this error in other places.

**Comment by pixelzoom** [comment]
I've replaced `as unknown as Node` with:

`// @ts-ignore TODO https://github.com/phetsims/sun/issues/728`

so that these can be cleaned up when https://github.com/phetsims/sun/issues/728 has been addressed.

**Comment by pixelzoom** [comment]
> I used new VerticalAquaRadioButtonGroup<'direct' | 'indirect'> because I didn't see an enumeration for direct vs indirect. I added as const so it would know those strings could match as members of that enum (this workaround was the most sketchy of the batch).

Adding an enum was on my TODO list, so I did that in https://github.com/phetsims/geometric-optics/commit/9fa821d472005b1b1ad6968baf8fbd48967e459f.  And in https://github.com/phetsims/geometric-optics/commit/ed4d7560ce9318c2d5dee12017a31261d54c7402, I replaced `as const` with `as FocalLengthControlEnum`.

**Comment by pixelzoom** [comment]
Done, closing.
