### ISSUE TITLE
Remove redundant type annotations and update a few type mismatches

### ISSUE THREAD

**Issue by samreid** [phetsims/geometric-optics#266]
From https://github.com/phetsims/axon/issues/366, now that (e.g.) NumberProperty extends `Property<number>`, the type annotations in the link callbacks can now be inferred by the compiler.  I updated these and saw 2 or so type inconsistencies.  I'll commit shortly and ask for review.

The first type mismatch is `readonly opticShapeProperty: StringProperty;` should be `readonly opticShapeProperty: Property<OpticShapeEnum>;`.  The other problem was an incorrect DerivedProperty type parameter.

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by pixelzoom** [comment]
👍🏻 closing
