### ISSUE TITLE
PhET-iO design for "light spots"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#269]
Related to #237 (PhET-iO Design) ...

A "light spot" is where the rays from a light source hit the projection screen. It's implemented as LightSpot (model) and LightSpotNode (view).  I have completed cleanup and PhET-iO instrumentation of the current implementation, so it's time to take a look and tell me what is needed/desired for PhET-iO.  

I'll warn you in advance... There is very little available for PhET-iO instrumentation in the current implementation. Adding additional Properties/features is going to involve major changes, or possibly a very expensive rewrite.  And if they are PhET-iO Properties/features, PhET still has no process for documenting, testing, etc.

In the model, there are 2 LightSpot instances, and their tandems are:
* `geometricOptics.lensScreen.model.firstLightSpot`
* `geometricOptics.lensScreen.model.secondLightSpot`

A  LightSpot has these Properties, both derived (so cannot be set):
* `intensityProperty` - intensity of the light hitting the screen, range [0,1], 0 if not hitting the screen
* `shapeProperty` - the shape used to draw the intersection between the light spot and the projection screen - not currently instrumented, because I don't know why this would be interesting/useful to clients

In the view, there are 2 LightSpotNode instances, and their tandems are:
* `geometricOptics.lensScreen.view.firstLightSpotNode`
* `geometricOptics.lensScreen.view.secondLightSpotNode`

A LightSpotNode has no sim-specific Properties, so perhaps we don't even need to instrument them.

Let me know what is needed/desired here. High priority please, since I'm working in this section of code now.

**Comment by pixelzoom** [comment]
11/11/21 design meeting:

model:
* make `intensityProperty` value `null` when there is no light spot on the screen
* add `positionProperty`, the position of the center of the light spot (which may not be one the screen), `null` if there is no light spot on the screen
* add `diameterProperty`, the y height of the ellipse, `null` if there is no light spot on the screen
(These model changes will require a significant rewrite of LightSpot.ts.)

view:
* un-instrument `firstLightSpotNode` and `secondLightSpotNode`

**Comment by pixelzoom** [comment]
Done, @arouinfar please review in master.

**Comment by arouinfar** [comment]
@pixelzoom this all looks good in master, closing.
