### ISSUE TITLE
Show/hide button: animated ray tracing and image appearance

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#27]
Create a show/hide button above the reset button. Use EyeToggleButton in scenery-phet.

When on 'show', rays should emerge from the object, pass through the optic, and once they converge, the image appears.  In the case when rays diverge, virtual rays should also be animated and the virtual image should appear.

'Hide' should make rays and image disappear.

**Comment by veillette** [comment]
ScreenShot: 
![image](https://user-images.githubusercontent.com/7633344/121895308-12863480-ccee-11eb-9abb-165892171ee2.png)

**Comment by sarchang** [comment]
Does show/hide button have to be circular? The one in scenery-phet is rectangular.

**Comment by sarchang** [comment]
see second screen of Proportions Playground: round toggle button to find round version

**Comment by veillette** [comment]
Well done. Closing
