### ISSUE TITLE
Allow both guides to be visible at the same time.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#276]
In the current implementation, only 1 pair of guides can be visible at a time.  I suspect that this odd behavior was ported from the Flash version.

To demonstrate:

1. Run the sim with `?showGuides`
2. Go to the Lens screen
3. Check the "Guides" checkbox. You'll see the guides associates with the source object, as in Screenshot 1 below.
4. Check the "Second Point" checkbox.   The guides associated with the second point become visibile.  But the guides associated with the source object are now hidden, as in Screenshot 2 below.
5. Things get even more odd when you select "Light" from the combo box, as in the Screenshot 3 below. 

Should be show both sets of guides? And if tell what they are associated with is a problem, should we color code them? 

Screenshot 1:
<img width="1125" alt="screenshot_1453" src="https://user-images.githubusercontent.com/3046552/145481478-3d471d98-8afd-4c42-8627-ea191017111e.png">

Screenshot 2:
<img width="1127" alt="screenshot_1454" src="https://user-images.githubusercontent.com/3046552/145481487-e6cc44b1-ff5f-4e76-9d08-3c4c528ae081.png">

Screenshot 3:
<img width="1125" alt="screenshot_1455" src="https://user-images.githubusercontent.com/3046552/145481496-0f10a6d7-6e46-419c-9aca-bde8bc198396.png">

**Comment by pixelzoom** [comment]
At 12/16/21 check-in, @ariel-phet said that he can imagine something related to this being included in the Basics version, but perhaps not in the full version.

**Comment by pixelzoom** [comment]
In the above commits, both pair of guides are visible, and they are color coded.  The first pair are white (unchanged). The second pair are color-coded to match the second set of light rays.  See screenshots below. 

While a little busy with "Second Point" checked, I think this is preferable to the first pair of guides mysteriously disappearing.  Yes, it's possible for the second pair of guides to fully covers the first pair.  But since the user will see that happen (and cause it to happen by moving an Object or Light), I doubt that will cause confusion.

@arouinfar please review. Reminder to run with `?enableGuides`.

![screenshot_308](https://user-images.githubusercontent.com/3046552/149217925-d316315e-5438-4210-807b-e941ece8da12.png)
![screenshot_309](https://user-images.githubusercontent.com/3046552/149217935-e815ccce-9edd-4a6a-b23a-2e29b2c9f9b7.png)

**Comment by arouinfar** [comment]
@pixelzoom thanks for making this change. I think the behavior in master is really clear and is worth making the view a bit busier. After all, the user elected to turn on both the Second Point and the Guides. Color-coding the 2nd guide to the accompanying rays is the way to go. Any further tweaks to colors can be handled in #275.
