### ISSUE TITLE
Geometric Optics - Publish 1.3 with PhET-iO

### ISSUE THREAD

**Issue by markgammon** [phetsims/geometric-optics#278]

**Comment by pixelzoom** [comment]
This is going to be 1.1, because branch 1.0 was already used for the Geometric Optics prototype that was published in https://github.com/phetsims/geometric-optics/issues/195.   So changing the title of this issue to reflect that.

**Comment by pixelzoom** [comment]
2/17/2022 design meeting, planning notes:

* interviews to be done again after the sim is feature complete and "team tested"
* prototype refresh to be published after the sim is feature complete and "team tested"
* code review to be done before dev testing, notify @kathy-phet ~2 weeks before

**Comment by pixelzoom** [comment]
3/3/2022 design meeting, we discussed some process questions.

* Dev-lite or "team" testing in a couple of weeks, to get a version ready for interviews and possible prototype publication

* Code review in Q2. No devs available in Q1, so we may do this later than where it usually occurs in the PhET process.

**Comment by pixelzoom** [comment]
Sicne we're doing a 1.1.0 prototype refresh in https://github.com/phetsims/geometric-optics/issues/387, this version number bumps to 1.2.0.

**Comment by pixelzoom** [comment]
1.1 was actually a public release for `brand=phet`, see #387.   

1.2 will include `brands=phet,phet-io`, and is schedule to be included with the batch release https://github.com/orgs/phetsims/projects/44.

**Comment by pixelzoom** [comment]
Dev testing started on 4/15/2022, with a focus on PhET-iO:

* https://github.com/phetsims/qa/issues/798
* https://github.com/phetsims/qa/issues/799

**Comment by pixelzoom** [comment]
Further progress is on-hold until PhET-iO issues are cleared for the "PhET-iO batch release" milestone, https://github.com/orgs/phetsims/projects/44.

**Comment by pixelzoom** [comment]
Status as of 7/5/2022 quarterly-planning meeting:

Progress on this issue is still on-hold, pending "PhET-iO batch release" milestone.

**Comment by kathy-phet** [comment]
Create dev test issue and move into QA ~8/17/2022

**Comment by pixelzoom** [comment]
8/17/2022 has come and gone, so I'm assuming that priorities have changed.

**Comment by pixelzoom** [comment]
Per https://github.com/phetsims/geometric-optics-basics/issues/27#issuecomment-1295331012, the next release of GO will be 1.3.  Adjusting the title of this issue accordingly.

**Comment by pixelzoom** [comment]
5/5/2023 started dev testing:

* https://github.com/phetsims/qa/issues/938
* https://github.com/phetsims/qa/issues/939

**Comment by pixelzoom** [comment]
5/17/2023 started RC testing:
* https://github.com/phetsims/qa/issues/944
* https://github.com/phetsims/qa/issues/945

**Comment by pixelzoom** [comment]
5//22 RC testing resumed with new release candidates:

* https://github.com/phetsims/qa/issues/947
* https://github.com/phetsims/qa/issues/948

**Comment by pixelzoom** [comment]
6/2/23 RC spot-check:
* https://github.com/phetsims/qa/issues/950
* https://github.com/phetsims/qa/issues/951

Completed 6/2/23.  No new issues found, ready to publish.

**Comment by pixelzoom** [comment]
6/4/2023: Geometric Optics 1.3.0 and Geometric Optics: Basics 1.3.0 were deployed.

`grunt production --branch=1.3 --brands=phet,phet-io`

Closing.
