### ISSUE TITLE
Hotkeys for moving rulers to specific positions.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#279]
Mentioned by @arouinfar in 12/16/21 design check in...

There may be a need for hotkeys to move the rulers to specific positions.

TODO:
- [ ] Identify which positions are important.
- [ ] Choose hotkeys. Reminder that they will need to differentiate between horizontal and vertical ruler.  And they should not conflict with existing hotkey bindings. (I don't know what those are, or where you might find them.)
- [ ] Design keyboard-help dialog, see https://github.com/phetsims/geometric-optics/issues/281

**Comment by arouinfar** [comment]
The important distances to measure are the focal length, object distance, image distance, object height, and image height. GFL and BASE have hotkeys to move the ruler/balloons to specific positions using "J + another letter", so I've followed that pattern. I think this simple set of hotkeys could work for both rulers. 

* J + L or J + M: Jump to lens/mirror (0, 0). This is good for measuring the focal length and image distance (if image is to the right of the optic). 
<img src="https://user-images.githubusercontent.com/8419308/147166008-dd469886-2347-4301-983b-04ac7ae56ae4.png" height=150> <img src="https://user-images.githubusercontent.com/8419308/147167061-693d8f3e-c800-4096-a68d-d8d8341bd0b1.png" height=150>
* J + O: Jump to object (x coordinate of object, 0). This is good for measuring the object distance or object height. 
<img src="https://user-images.githubusercontent.com/8419308/147166206-cff35a6d-8e06-4eae-a834-f3d41d077c62.png" height=150><img src="https://user-images.githubusercontent.com/8419308/147167191-633ed941-024c-487f-8917-989443de70bc.png" height=150>
* J + I: Jump to image (x coordinate of image, 0). This is good for measuring the image distance (if image is to the left of the optic) or the image height.  
<img src="https://user-images.githubusercontent.com/8419308/147166969-14268478-d456-47bb-a1c9-4051ce73a813.png" height=150> <img src="https://user-images.githubusercontent.com/8419308/147168343-58464180-2894-4f8d-8c1e-b6cd9dc353b0.png" height=150>

There will be cases where a user would still need to adjust the position of the ruler after jumping it to one of these locations, but the movement would be 1D and easy to tweak with the arrow keys. For example, to measure the height below the optical axis, the user would need to shift the ruler down until the bottom reaches the point of interest.  
<img src="https://user-images.githubusercontent.com/8419308/147168973-9923b780-2706-467d-9cf6-450d3f495015.png" height=150>

Similarly, users may want to shift the horizontal ruler to the vertical position of the image (intersection point of the rays).
<img src="https://user-images.githubusercontent.com/8419308/147169184-cbc85e31-17e3-4ab1-b671-afa136b2da42.png" height=150> 

@pixelzoom what do you think of this set of hotkeys? I think it covers all of the bases using the smallest and most general set of hotkeys. The only case this doesn't cover is the 2nd lamp, which I think we can ignore for the purpose of the hotkeys.

**Comment by pixelzoom** [comment]
This looks like a nice start.  Questions/clarifications: 

* For the horizontal ruler, do you want the hotkey to ALWAYS move the ruler so that it's top is on the optical axis, as shown in the mockups?

* If we really want a hotkey for the second light source, perhaps J + S ? (S = Second)

* Is J + O intended to apply to the first light source? It's technically not an "object" (or correct me on that if I'm mistaken), it just happens to be lumped into the objects combo box.  Should we use J + L or J + F (F = First) for the first light source?  And I suppose we could also support J + O for the first light source, in case there's any confusion.

* Is the plan to design the keyboard-help dialogs after this has been implemented and refined?

**Comment by pixelzoom** [comment]
@arouinfar Hotkeys were fixed in common code (see https://github.com/phetsims/scenery/issues/1334) so this is ready for review.

**Comment by pixelzoom** [comment]
@arouinfar it just ocurred to me that there's no hotkeys related to measuring f or 2f.  Do we need additional hotkeys? Do they make sense for the vertical ruler?  Will the dialogs be too crowded?

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The hotkeys look good in master. Can we amend the behavior of J+S to apply to the Second Point or second lamp? The dialog text could read, "Jump to Second point or light source." For the horizontal ruler, the behavior would effectively be the same as J+O, but it would be helpful for the vertical ruler if users want to measure the magnification with respect to the Second Point.

> @arouinfar it just occurred to me that there's no hotkeys related to measuring f or 2f.

I think the hotkey for the optics will work well here. Users can measure the distance from the optic to the f/2f points. I don't see a need for additional hotkeys to jump the ruler origin to these points.

**Comment by pixelzoom** [comment]
> Can we amend the behavior of J+S to apply to the Second Point or second lamp? The dialog text could read, "Jump to Second point or light source."

Done. Dialog is handled in https://github.com/phetsims/geometric-optics/issues/281.

@arouinfar please review.  Note that J+S is ignored if the "Second Point" checkbox is not checked.  Also note that J+I will eventually be ignored when the Image is hidden, but is not currently.

**Comment by arouinfar** [comment]
> @arouinfar please review. Note that J+S is ignored if the "Second Point" checkbox is not checked. Also note that J+I will eventually be ignored when the Image is hidden, but is not currently.

Thanks @pixelzoom. J+S looks good in master. Back to you for the remaining J+I issue.

**Comment by pixelzoom** [comment]
> ...  Back to you for the remaining J+I issue.

Note to self:  Pass `targetNode.visibleProperty` to GORulerNode, ignore J+I if `targetNode.visibleProperty.value` is false.

**Comment by pixelzoom** [comment]
J+I is now ignore when the Image is not visible.  This can be tested using the eyeball button.   Back to @arouinfar to review.  If it looks OK, feel free to close this issue.

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom
