### ISSUE TITLE
Initial position for rulers when using alt input.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#280]
Related to #258 ...

When the rulers are popped out of the toolbox, where would you like them to be positioned initially?

Info:
* The position of the horizontal ruler is defined by its upper-left corner. 
* The position of the vertical ruler is defined by its lower-left corner.
* Both rulers are initially positioned at (0,0), the origin of the model coordinate frame, and the fixed position of the optic.

**Comment by arouinfar** [comment]
@pixelzoom I think starting at the origin is the most natural choice. 

Another option would be to align the initial position of the rulers to the object or image, but then the positions would vary. I think it's cleaner to use the origin, so let's continue with that. Closing.
