### ISSUE TITLE
Keyboard-help dialogs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#281]
Related to https://github.com/phetsims/geometric-optics/issues/235 ...

Design the keyboard help dialogs, one for each screen. If possible, please provide mockups.

Currently, the dialogs contain the "Slider Controls" and "Basic Actions" sections:

![screenshot_287](https://user-images.githubusercontent.com/3046552/146450672-e9d076ac-7571-4650-bc85-c92a3e7ee5e7.png)

Other things that will be needed:
* Interaction with toolbox and rulers (space, arrow keys, escape,...)
* Hotkeys for rulers, see https://github.com/phetsims/geometric-optics/issues/279
* Interaction with source object, second point of interest, light sources, projection screen
* Combo box for choosing the object or light source, see https://github.com/phetsims/scenery-phet/issues/715

**Comment by arouinfar** [comment]
@pixelzoom here's a layout for the dialog:
<table>
<tr><td>Move Items</td><td>Slider Controls</td></tr>
<tr><td>Ruler Controls</td><td>Basic Actions</td></tr>
<tr><td>General section for ComboBoxes</td></tr>
</table>

The ComboBox content is being generalized in https://github.com/phetsims/scenery-phet/issues/715 so the only sim-specific content would be in the Move Items and Ruler Controls sections. @pixelzoom here's the content assuming we go with the hotkeys I proposed in https://github.com/phetsims/geometric-optics/issues/279. I went with "Items" since "Object" has a specific meaning in the sim context.

**Move Items**
* Move items [arrows] or [WASD]
* Move slower [Shift] + [arrows] or [Shift] + [WASD]

**Ruler Controls**
* Remove ruler from toolbox [Space]
* Return ruler to toolbox [Esc]
* Jump to lens [J] + [L] OR Jump to mirror [J] + [M] (depending on the screen)
* Jump to object [J] + [O]
* Jump to image [J] + [I]

**Comment by pixelzoom** [comment]
For this section:

> Move Draggable Items
> 
> * Move items [arrows] or [WASD]
> * Move slower [Shift] + [arrows] or [Shift] + [WASD]


See Fourier MeasurementToolsKeyboardHelpSection, and consider generalizing it, with a parameterized title.

**Comment by pixelzoom** [comment]
I'm done with the keyboard-help dialogs, with the exception of the "General section for Combo Boxes".  That's blocked until https://github.com/phetsims/scenery-phet/issues/715 is completed.  

As with Fourier, this took me a large amount of time, 4+ hours today alone.

**Comment by pixelzoom** [comment]
@arouinfar this is ready for review.  The  "General section for Combo Boxes" section title is temporary, until phetsims/scenery-phet#715 is completed.  Here's what the dialog looks like for each screen:

_Lens_ screen:

<img width="756" alt="screenshot_1483" src="https://user-images.githubusercontent.com/3046552/147999699-d2dee769-41d3-4550-b256-b391294f68bb.png">

_Mirror_ screen:

<img width="747" alt="screenshot_1484" src="https://user-images.githubusercontent.com/3046552/147999704-cbf014c3-552c-4d1d-bf0a-1c7a182718e1.png">

**Comment by arouinfar** [comment]
@pixelzoom the dialog contents look good, though I suggested this change to the dialog in https://github.com/phetsims/geometric-optics/issues/279:

>Can we amend the behavior of J+S to apply to the Second Point or second lamp? The dialog text could read, "Jump to Second point or light source."

**Comment by pixelzoom** [comment]
Done, see Lens screenshot below (Mirror screen is similar).  @arouinfar please review.

<img width="787" alt="screenshot_1500" src="https://user-images.githubusercontent.com/3046552/148850403-0bbf388c-9c57-486d-b51d-085bd0af6a79.png">

**Comment by arouinfar** [comment]
Looks good @pixelzoom. I think the only thing left is to fix the ComboBox heading, but not sure if that belongs in this issue or will be addressed in https://github.com/phetsims/scenery-phet/issues/715.

**Comment by pixelzoom** [comment]
Let's leave this open and "on-hold" until the ComboBox heading is addressed in phetsims/scenery-phet#715.

**Comment by pixelzoom** [comment]
In meeting with @arouinfar, we decided to change the "Choose a combo box option" to "Choose an Object".  Unfortunately, `ComboBoxKeyboardHelpSection` assumes that all nouns begin with a consonant, so we're currently stuck with "Choose a Object", see below.

<img width="373" alt="screenshot_1556" src="https://user-images.githubusercontent.com/3046552/153966664-418c739c-1fe2-4e9b-baca-72b9d317249e.png">

**Comment by pixelzoom** [comment]
After changes to ComboBoxKeyboardHelpSection in https://github.com/phetsims/scenery-phet/issues/715, issues are resolved, and the "Choose an Object" help section now looks correct, see below.

@arouinfar please make a (final?) pass through keyboard help, let me know if there's anything to change. If nothing to change, please close this issue.

<img width="430" alt="screenshot_1561" src="https://user-images.githubusercontent.com/3046552/154088305-4b0b6a45-8eac-4d65-9b39-b0507b3d6965.png">
.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The keyboard help dialog looks great! Closing.
