### ISSUE TITLE
Option to constrain object to horizontal dragging.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#282]
From 12/20/21 design meeting, would like to add a control that optionally constrains dragging of the source object (or light source) to the horizontal dimension.  The object's current y position will effectively be fixed.

From the design doc notes:

> Fix vertical position of objects:
>
> Should we have a mode that constrains movement of the object in the horizontal direction? Where would we fix it? Middle of frame, bottom of frame? 
> 
> For the Light source, we would want to snap it to the optical axis. For the picture frames, we would probably pick the middle. The model treats these objects the same. It doesn’t “know” what object is selected.
> 
> Would it be a checkbox or query parameter? AP would make it a checkbox.
> 
> Possible icon (empty frame with L/R arrow)
> 
> <img width="275" alt="screenshot_1461" src="https://user-images.githubusercontent.com/3046552/146836344-75a92f99-15d1-4ba6-840f-170f1523acf4.png">
> 
> Location
> 
> <img width="276" alt="screenshot_1462" src="https://user-images.githubusercontent.com/3046552/146836352-9db6dedf-f695-4989-b540-9dbca675f3dd.png">
> 
> Basics only.
> Default unchecked.
> Cueing arrow is 2D when checked.
> Snap light to optical axis. Snap picture frames to their vertical center (current default y-coordinate of picture frames looks about right).
> 
> Is this in both sims?
> Could be Basics-specific code, or could be in the main sim but invisible in phet-brand.
> 
> Implications for PhET-iO
> What happens if the client sets a bad y-value when the checkbox is on? Could reset the y-value to its appropriate value. Could uncheck the checkbox. 
> 
> Another option could be that the feature should lock the y-coordinate where the user/client leaves it. If the client passes in a new y-value nothing would break. Also doesn’t require the model to snap the objects to different y-coordinates.

**Comment by pixelzoom** [comment]
I put together a quick implementation of this.  

The control uses font awesome icons, so requires no external artwork. It turns red when it's "on".

<img width="289" alt="screenshot_1463" src="https://user-images.githubusercontent.com/3046552/146836758-39f15f67-1a5f-466a-a1ca-d7efdc460d84.png">
<img width="286" alt="screenshot_1464" src="https://user-images.githubusercontent.com/3046552/146836767-1c40ff1f-05f2-477c-b887-3783404f2274.png">

New PhET-iO elements:

```
geometricOptics.lensScreen.view.horizontalDragLockedProperty
geometricOptics.lensScreen.view.horizontalDragLockButton

geometricOptics.mirrorScreen.view.horizontalDragLockedProperty
geometricOptics.mirrorScreen.view.horizontalDragLockButton
```

@arouinfar please review, let me know what you'd like to change.

**Comment by pixelzoom** [comment]
TODO:  
 
- [ ] Set cueing arrows for source object and light source, based on whether `horizontalDragLockedProperty` is true or false

**Comment by pixelzoom** [comment]
It just occurred to me that perhaps the icon arrows should point up and down, to indicate that vertical position is locked.  I'm not sure...

**Comment by pixelzoom** [comment]
I've changed the icons to match the cueing arrows, screenshots below:

<img width="1043" alt="screenshot_1465" src="https://user-images.githubusercontent.com/3046552/147007553-33f16259-0502-4db5-8cd3-6cf30ff81e1f.png">

<img width="1045" alt="screenshot_1466" src="https://user-images.githubusercontent.com/3046552/147007547-f197e4dc-7ce5-4374-8503-6a951ffd122b.png">

**Comment by pixelzoom** [comment]
Revised PhET-iO elements:

```
geometricOptics.lensScreen.view.dragLockedProperty
geometricOptics.lensScreen.view.dragLockdButton

geometricOptics.mirrorScreen.view.dragLockedProperty
geometricOptics.mirrorScreen.view.dragLockedButton
```

**Comment by pixelzoom** [comment]
Notes from call with @arouinfar:

* Use realistic lock images
* Use font awesome icons for cueing arrows
* Move cueing arrows to right of projection screen

**Comment by pixelzoom** [comment]
Back to @arouinfar to review:
* any additional changes to toggle button
* drag behavior for objects and light sources
* cursor behavior for objects and light sources
* cueing arrows behavior for objects and light sources
* PhET-iO elements

**Comment by pixelzoom** [comment]
> Things in the Studio tree also look good, but I was wondering why there isn't an enabledProperty for the button. It's possible that a client would want to lock the button in a particular state by disabling the button, but have the icon serve as an indicator of the allowed direction of movement.

Because this isn't actually a sun button, it's a subclasss of something called a ToggleNode.  And by default, `enabledProperty` is not instrumented for ToggleNode.

So... I've reimplemented this as a sun button (BooleanRectangularToggleButton), with transparent background and stroke.  That gives us `enabledProperty` instrumentation.  And it will allow us to make it look like a rectangular sun button, if that's deemed necessary after interviews. 

@arouinfar please review.

**Comment by arouinfar** [comment]
Thanks for the explanation @pixelzoom. The tree looks good and the added flexibility to change the button appearance is a plus.

**Comment by pixelzoom** [comment]
@arouinfar debriefed the team on interviews, and there were no problems with this feature. One student used the feature quite a bit.

@arouinfar anything to add before closing this issue?

**Comment by arouinfar** [comment]
Thanks for summarizing, we can close.
