### ISSUE TITLE
Optical axis should look like it's passing through things.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#283]
Factored out of https://github.com/phetsims/geometric-optics/issues/125, because the optical axis is a separate project.  

We want it to look like the optical image passes through the object, image, and projection screen.  So it should be partially occluded by opaque things that are in front of it.  

Here's am old mockup, from https://github.com/phetsims/geometric-optics/issues/125#issuecomment-948945818, showing the optical axis passing through the (old) projection screen:

![image](https://user-images.githubusercontent.com/7633344/125514657-33a6a86c-9f25-46e0-9d44-2c5ccc03a9e8.png)

And in https://github.com/phetsims/geometric-optics/issues/125#issuecomment-949046971,  I said:

> Splitting each object, image, and projection screen into 2 Nodes is going to be quite a mess. I'm speaking from experience, since I did this in Faraday's Electromagnetic Lab.
> 
> I'm going to investigate another approach, where the optical axis and rays are split into multiple Nodes. The optical axis seems straightforward, the rays wil be tricky.

**Comment by pixelzoom** [comment]
The commit above uses 2 copies of OpticalAxisNode. One is in the far background, the other is in front of the object, image, and projection screen.  The one in front uses a `clipArea` to show only the part of the optical axis that is in front.  

This approach handles the object, real image, and projection screen.  But it does not handle the virtual image.  So I'm going to have to rethink this...

**Comment by pixelzoom** [comment]
Here are some screenshots showing how the optical axis passes through the object, real image, and projection screen respectively.  Note that the real image is transparent, so you can see the axis through it -- based on discussions, I'm not sure that this was anticipated, so @arouinfar @kathy-phet FYI.

<img width="188" alt="screenshot_1469" src="https://user-images.githubusercontent.com/3046552/147026916-e7b233dc-071e-4587-8bb0-34b139264018.png">

<img width="185" alt="screenshot_1470" src="https://user-images.githubusercontent.com/3046552/147026925-68956ce3-db21-40a2-a73b-dcd5c1d36a0b.png">

<img width="181" alt="screenshot_1471" src="https://user-images.githubusercontent.com/3046552/147026941-2238117c-4b0e-427a-8d10-f2f0480012ed.png">

**Comment by pixelzoom** [comment]
@arouinfar what do you want to do with the F and 2F points in situations where they are on part of the axis that is behind the object, image, or projection screen?  Example cases shown below. Dynamically adjusting the rendering order for the points (so that they are occluded by the object, image, projection screen) is possible, but not easy. I need to know this with high priority. 

<img width="153" alt="screenshot_1474" src="https://user-images.githubusercontent.com/3046552/147027541-cd505829-7e6f-43f9-a4f7-fb94797de24c.png">

<img width="308" alt="screenshot_1472" src="https://user-images.githubusercontent.com/3046552/147027396-5630e6c2-8781-4287-a1e2-2b53d292fbde.png">

**Comment by pixelzoom** [comment]
Notes from Zoom meeting with @arouinfar:

* This approach looks good.

* An approach of bisecting each object would have 2 major problems: multiple Nodes in the Studio tree, and possibly a vertical seam in the real/virtual image.

* These 2 checklist items are caused by the same problem:
> - [ ] Does not address the virtual image
> - [ ] Is buggy when the object is to the left of the focal point

* For the real image, would like the part of the optical axis that's occluded by the real image to be more transparent.  Add a mask behind the right half of the real image, filled with the background color, and with a bit of transparency (e.g. `opacity: 0.95`).

* For rays in #125:
  - For real image, use this same approach.
  - For virtual image, do nothing. Do not want the rays to look like they're going through the (solid) object.
  - For projection screen, do nothing, the current look is desired.

**Comment by pixelzoom** [comment]
In the above commit, I added support for virtual image. 

Next up is adding the mask to make the optical axis appear more "faint" where its occluded by the image.

**Comment by pixelzoom** [comment]
The remaining bit of work here from https://github.com/phetsims/geometric-optics/issues/283#issuecomment-999803267 is:
> For the real & virtual image, would like the part of the optical axis that's occluded by the image to be more transparent. Add a mask behind the right half of the real image (left half of virtual image), filled with the background color, and with a bit of transparency (e.g. `opacity: 0.95`).

The most straightforward way to create the mask would be to use scenery.Image `hitTestPixels: true` and `getSelfImage`, which should return the Shape for the mask.  But that feature of Image seems to be broken, and has in fact never been used , see https://github.com/phetsims/scenery/issues/1333.  I'll wait to hear from @jonathanolson before deciding if I need to investigate a workaround.

**Comment by pixelzoom** [comment]
In the above commit, I'm using Image `getSelfShape` with `hitTestPixels: false` for now.  This results in a rectangular mask, as show by the red stroke in the screenshot below with `?debugMask`.   This doesn't behave correctly above/below the non-transparent part of the image, but we'll live with it until @jonathanolson fixes phetsims/scenery#1333. 
  
<img width="1043" alt="screenshot_1489" src="https://user-images.githubusercontent.com/3046552/148140699-25ef5632-09c2-4400-8f95-7194ade91183.png">

**Comment by pixelzoom** [comment]
@arouinfar This can be reviewed before phetsims/scenery#1333 is resolved. Just keep in mind that the image mask is currently a rectangle, not the shape of the picture frame.  The current opacity of the image mask is 0.8. Let me know if you'd like to see more or less of the occluded optical axis. Note that this opacity will also affect how much of the occluded rays are seen.

**Comment by pixelzoom** [comment]
There's a mirror case that is incorrect, see below.  Back to me to fix this.

![screenshot_295](https://user-images.githubusercontent.com/3046552/148453739-97e3fc9e-446f-4ba5-b189-5cee044eb5fe.png)

**Comment by pixelzoom** [comment]
Fixed in the above commit.

Here are the 7 cases that can occur for the optical axis, showing how the optical axis looks as it passes through Object/Image/Optic/Screen.

### Lens + Light Source

![screenshot_302](https://user-images.githubusercontent.com/3046552/148457600-d13f744c-ceac-4120-b0b6-6a242cd10032.png)

### Convex Lens + Real Image

![screenshot_296](https://user-images.githubusercontent.com/3046552/148457111-dc70017e-f6fd-4861-82d9-d5bb1a168fd8.png)

### Convex Lens + Virtual Image

![screenshot_297](https://user-images.githubusercontent.com/3046552/148457164-8893d222-2050-4790-a550-15195707ba32.png)

### Concave Lens + Virtual Image

![screenshot_298](https://user-images.githubusercontent.com/3046552/148457237-85f38cdb-d4d4-436d-819e-3960bbce2600.png)

### Concave Mirror + Real Image (to right of Object)

![screenshot_299](https://user-images.githubusercontent.com/3046552/148457326-dbe99df6-faed-4376-9744-e221886a9486.png)

### Concave Mirror + Real Image (to left of Object)

![screenshot_300](https://user-images.githubusercontent.com/3046552/148457443-a958967d-1767-46ff-ae10-81466f0af1e0.png)

### Convex Mirror + Virtual Image

![screenshot_301](https://user-images.githubusercontent.com/3046552/148457489-370b08b9-e366-49f7-a1d0-a0d628abb5a2.png)

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The optical axis looks good in the screenshots (thanks for showcasing all of the permutations!) and in master.

Things can sometimes look a little strange when the object and image are close to one other, such as in this case:
![image](https://user-images.githubusercontent.com/8419308/148616809-5f87e7d7-7f3f-4bd3-aa2c-4d99b9154ad4.png)

Steps to reproduce:
1. Lens screen, select concave lens
2. Move object as close as possible to the lens
3. Set index of refraction to the maximum value

I think this is an acceptable edge case, but I wanted to bring it to your attention in case there's something else going on with the clipping regions.

**Comment by pixelzoom** [comment]
The problem demonstrated in the scenario shown in https://github.com/phetsims/geometric-optics/issues/283#issuecomment-1007798847 is that the implementation is using the nominal width of the framed Image to compute the clipArea. It needs to use _scale_ width of the framed Image.   There's a TODO related to this in 

```js
 const halfFrameWidth = 34; //TODO get this from sourceObject.boundsProperty, or from sourceObjectNode
```

I'll work on correcting that.

**Comment by pixelzoom** [comment]
The scenario in https://github.com/phetsims/geometric-optics/issues/283#issuecomment-1007798847 has been fixed, see screenshot below.  Any remaining weirdness should be related to phetsims/scenery#1333, so I'll leave this open until that issue is fixed.  Labeling as on-hold.

<img width="338" alt="screenshot_1502" src="https://user-images.githubusercontent.com/3046552/148858926-90ff62ce-771b-4748-824b-c1b2fb9f7f71.png">

**Comment by pixelzoom** [comment]
In the above commit, I've added a workaround for the bug in phetsims/scenery#1333. I'm explicitly creating shapes that match the "framed object" images. 

@arouinfar please review in master.  If it looks OK, assign back to me.

**Comment by arouinfar** [comment]
Looks good in master, back to you @pixelzoom.

**Comment by pixelzoom** [comment]
#296 tracks remaining work, so closing this issue.

**Comment by pixelzoom** [comment]
For posterity... At 1/20/22 design meeting, @ariel-phet asked about an approach where the optical axis is drawn in foreground/background segments.  I initially went down that path, then discovered that the dashed pattern of the line would move around. So as you dragged the Object, the axis appeared to scroll.  I could have tried resolving that using `lineDashOffset`, but it seemed a little to fiddly/brittle.

**Comment by pixelzoom** [comment]
For the record... After "scenes" were introduced in #217, it became possible to use a different approach when the selected object is a light source.  Instead of using clipArea, a foreground copy of the optical axis is drawn from the left edge of the screen to its intersection with the projection screen.  Because the left edge is the same as the background optical axis, there's no movement of the dash pattern.  This implementation has better performance, and appears in https://github.com/phetsims/geometric-optics/commit/397a6e124ddddd21dc610aadf80135e853beba44.
