### ISSUE TITLE
Use a single PNG for each framed object.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#284]
For the framed object (pencil, etc.) I'm wondering why we have 4 image files for each.  For example, for the pencil, we have:

pencilLeftFacingInverted.png
pencilLeftFacingUpright.png
pencilRightFacingInverted.png
pencilRightFacingUpright.png

... which look like this respectively (left to right):

![screenshot_294](https://user-images.githubusercontent.com/3046552/147277326-b13c02ff-05a0-4d47-8657-3b9168f619da.png)

The lighting cues are certainly not being adjusted for perspective (should they be?), so I don't think that's the reason.

Since it's trivial to use rotation and reflection to programmatically create 3 of these images from any 1 of them, I propose that we delete 3 of the PNG files for each framed object. 

@arouinfar do see any problems with this proposal?

And since I'm not familiar with the history here, maybe @veillette can clarify, if he's available.

**Comment by sarchang** [comment]
I don't remember exactly why we didn't programmatically rotate/reflect the images but that sounds like a good plan. Definitely double check with @veillette.

**Comment by pixelzoom** [comment]
Thanks @sarchang.

**Comment by veillette** [comment]
It would be possible to reduce it from 4 to 2, but one can't reduced it to
a single PNG, in general. Some images do not have horizontal reversal
symmetry, so at least two images are required for those.

Some images like the pencil, have horizontal reversal symmetry , so all the
images could be generated from one PNG for those ones.
Martin

**Comment by pixelzoom** [comment]
Thanks @veillette.  I see that now -- the penguin and planet do not have "horizontal reversal symmetry".

**Comment by pixelzoom** [comment]
I guess I'm going to "do nothing" here.  It was potentially going to make #283 and #125 a little easier.  But I'll work around it. 

Closing.
