### ISSUE TITLE
A11y dependencies for Geometric Optics 1.1 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#285]
This issue will be used to track a11y issues that potentially impact https://github.com/phetsims/geometric-optics/issues/278, Geometric Optics 1.1. 

--- 
### Blocking

**Alternative Input**
* https://github.com/phetsims/scenery/issues/1313 @zepumph 2022 Q1
* https://github.com/phetsims/scenery/issues/1354
* https://github.com/phetsims/scenery-phet/issues/715 @jessegreenberg 2022 Q1

**UI Sound**
* https://github.com/phetsims/phet-io/issues/1828 @zepumph 2022 Q1
* https://github.com/phetsims/sun/issues/697 @jbphet 2022 Q1
* https://github.com/phetsims/phet-io/issues/1626 @zepumph 2022 Q1 (specifically a reset all bug that likely applies to GO also, see [this comment](https://github.com/phetsims/phet-io/issues/1626#issuecomment-1034217060))

---
### Not Blocking

**Alternative Input**
* https://github.com/phetsims/joist/issues/769
* https://github.com/phetsims/scenery/issues/1307
* https://github.com/phetsims/scenery/issues/1330
* https://github.com/phetsims/scenery/issues/1331
* https://github.com/phetsims/scenery/issues/1334
* https://github.com/phetsims/scenery/issues/1335
* https://github.com/phetsims/scenery/issues/1355
* https://github.com/phetsims/scenery-phet/issues/716
* https://github.com/phetsims/scenery-phet/issues/717
* https://github.com/phetsims/sun/issues/698
* https://github.com/phetsims/sun/issues/703

**UI Sound**
* https://github.com/phetsims/tambo/issues/158

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet @jessegreenberg @zepumph FYI.

**Comment by zepumph** [comment]
Noting this as a sub issue to https://github.com/phetsims/phet-io/issues/1611.

**Comment by pixelzoom** [comment]
In 1/12/22 Q1 planning meeting, we triaged the list of issues in https://github.com/phetsims/geometric-optics/issues/285#issue-1093696823.  Issues that need to be completed in Q1 2022 are noted with responsible developer shown.

**Comment by pixelzoom** [comment]
2/17/22 design meeting:  I'm a bit ahead of schedule on Geometric Optics.  @kathy-phet suggested that I should notify a11y devs, which I did via a group Slack message.

**Comment by zepumph** [comment]
My blocking issues have been taken care of, unassigning.

**Comment by pixelzoom** [comment]
Since all blocking issues have been addressed, I'm going to close this.

Thanks @zepumph, @jessegreenberg, and @jbphet!
