### ISSUE TITLE
Physics bug with concave mirror.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#288]
This is a serious physics bug.

While discussing https://github.com/phetsims/geometric-optics/issues/125 with @ariel-phet, he had a new concern about the case shown in the screenshot below, a concave mirror, with the Object < 2f from the optic. Since the Object is blocking reflected rays, how can a Real Image be formed?   

@ariel-phet will investigate. @arouinfar FYI.

<img width="1044" alt="screenshot_1507" src="https://user-images.githubusercontent.com/3046552/149012626-082df136-097c-4f34-bcc2-3fbbb34aab40.png">

**Comment by pixelzoom** [comment]
There would probably be a shadow on the real Image, partially blocking it.  And we definitely do not want to go down that path.

@ariel-phet suggested that the way to avoid this problem would be to keep the Object above the optical axis, as shown in the screenshot below. Enforcing this for just the concave mirror would be a confusing user experience - when the user selects concave, we'd have to jump the Object to a new position and lock it to horizontal dragging.  So a better experience might be to limit object motion to horiztonal in the Mirror screen, with the Object positioned above the optical axis.

<img width="1043" alt="screenshot_1508" src="https://user-images.githubusercontent.com/3046552/149019868-c1aa12c4-2966-4eb6-b383-b9ca3f408f16.png">

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  She pointed out that locking to horizontal dragging in the Mirrors screen would also avoid the case below.   That case is not physically incorrect.  But it's conceptually confusing, because it shows the rays going through a Real Image that doesn't exist yet, as well as reflected rays continuing past (and in front of) a solid Object.

<img width="1041" alt="screenshot_1514" src="https://user-images.githubusercontent.com/3046552/149026309-eeb463c3-6f34-44c5-9d73-88f9ffd6f332.png">

**Comment by ariel-phet** [comment]
Discussed at design meeting 1/13/2022 -- it was agreed that keeping things locked to 1d motion on the mirror screen is likely best.

@arouinfar will communicate with @veillette regarding this issue.

**Comment by veillette** [comment]
@arouinfar . 
Yes that seems to be a bug. The constraint on the positioning you have chosen is probably the best way to go about addressing it.

I'll note that the projector screen was removed from the mirror screen for that very reason. Applying the same position contraint on the projector screen would allow to avoid the scenario that lead to its removal.

**Comment by pixelzoom** [comment]
A couple of questions that I asked @arouinfar on Slack:

> (1) Does https://github.com/phetsims/geometric-optics/issues/288#issuecomment-1012503170 mean I should proceed with constrained horizontal dragging in the Mirror screen?
>
> (2) Re https://github.com/phetsims/geometric-optics/issues/288#issuecomment-1013114767: Is there any interest in (or pedagogical reason to) add lights + projection screen to the Mirror screen, as Martin suggested?  If so, I have several other important questions.

@arouinfar replied:
> Yes, let’s proceed with constrained horizontal dragging on the Mirror screen. 
>
> I do not recommend adding the light/screen to the Mirror screen. We would need a screen on the left side of the mirror, and I think that would be more trouble than it’d be worth. The related learning goals can be served on the Lens screen.

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master.

In the Mirror screen, the Object is above the optical axis, and is constrained to horizontal dragging. There is no lock control.

For PhET-iO... The Lens screen has `view.dragLockedProperty` and `view.dragLockedButton`, while the Mirror screen does not.

**Comment by ariel-phet** [comment]
@pixelzoom reviewed in master -- this solution certainly removes the physics bugs we were concerned about and still seems to get at the key learning goals.

**Comment by pixelzoom** [comment]
1/20/22 design meeting:

This looks good, including constraining the dragging for convex and (eventually) flat mirror.
