### ISSUE TITLE
Guide arms need to be shortened

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#290]
Each guide is composed of 2 "arms" that are connected to a fulcrum.  The arms need to be shortened.  If you move an Object/Light as close to the optic as possible, the guides overlap the Object/Light in a bad way. See screenshots below. 

This bug has been present since at least 1.0.0-dev.9, before I started working on the sim.

![screenshot_312](https://user-images.githubusercontent.com/3046552/149219957-3c65c57b-87d8-466b-ae99-c019abdd8d06.png)
![screenshot_311](https://user-images.githubusercontent.com/3046552/149219961-e0fd85c5-ef9c-4aa8-8f6c-d581971e5ac4.png)

**Comment by pixelzoom** [comment]
Fixed in the above commit. The guide arms were shortened from 96 to 70.  Screenshots below show the scenarios where the Object/Light is at its closest to the guide arm.  I figured we wanted to see at least a little bit of the ray before it enters the guide arm.

@arouinfar please review in master, running with `?enableGuides`.

![screenshot_314](https://user-images.githubusercontent.com/3046552/149221112-258e6266-40f6-413e-bddb-ed7e4c24ea9a.png)

![screenshot_313](https://user-images.githubusercontent.com/3046552/149221118-4b2a7432-fe78-4f67-9863-c06740fb8aff.png)

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The updated length looks perfect. Closing.
