### ISSUE TITLE
Revisit zoom controls

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#291]
The sim current has zoom controls that looks like this:

![screenshot_316](https://user-images.githubusercontent.com/3046552/149222655-7ac64004-6626-499e-81a0-2d49ef7be5c6.png)

As currently implemented, I don't find this control to be very useful. There are 3 zoom levels (1x, 1/2x, 1/4x), so there's a huge amount of change each time you press a button.  

Can we change the amount of zoom for each level? This would be a relatively easy change.

Or would a zoom control like Gravity and Orbits we more useful?  See screenshot below. It doesn't look like this control has been generalized, so this would be a more expensive change. (See gravity-and-orbits ZoomControl.ts)

![screenshot_315](https://user-images.githubusercontent.com/3046552/149223038-cda56918-74a0-4957-8cb2-e993cc0045ff.png)

**Comment by arouinfar** [comment]
@pixelzoom I'm not opposed to using a continuous zoom control, but I don't know that it would work with the rulers. A continuous zoom would require continuous scaling of the rulers. The way it works now is that each zoom level has its own appropriately-scaled ruler.

**Comment by pixelzoom** [comment]
Ah right, those pesky rulers.  How about a couple more zoom levels in between the existing ones?

**Comment by veillette** [comment]
For your information, last summer, I had toyed with the idea of generalizing the way to handle ticks for a ruler of arbitrary length.  Currently, the client must specify the number of ticks, minor ticks as well as the length of the ruler.
However, the problem of layout ticks in a way that looks "natural" is quite common in graphs.

I remember spending some time looking at the desmos graphing calculator  and try to work backward to infer the algorithm that they used.  I came up with a few rules
- The separation between majors ticks are always multiples of (1,2,5)*10^n: (1,2,5,10,20,50,100,....
- The separation between major ticks can never be smaller than a threshold distance (in the view coordinates)
- There was also a rule about minor ticks per major tick but i dont remember it.


Although I dont remember the details, it should be possible to add additional logic to the ruler knows how to lay itself in a way that looks "natural".

**Comment by pixelzoom** [comment]
Thanks for the info @veillette.  I'm also confident that the ruler could lay itself out for an arbitrary zoom scale. But scenery-phet.RulerNode does not support mutation.  So the current implementation in geometric-optics creates an entirely new RulerNode for each scale.  I'm doubtful that a continuous control (e.g. slider) would remain responsive if RulerNode instances are being added/removed from the scene graph.  More importantly, there are more important things that need to be addressed for this sim, in a finite amount of time. 

So I'm going to modify the existing (discrete) zoom implementation so that it supports more (and arbitrary) zoom levels.

**Comment by pixelzoom** [comment]
While I did revise model-view transform implementation in #277, I decided not to change the zoom controls and zoom levels.  Even adding a scale like 0.75 would result in undesirable ruler ticks. 

Closing.
