### ISSUE TITLE
2D framed objects are not a solution

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#297]
This issue is to document some things that were discussed and tried.  @arouinfar @kathy-phet @ariel-phet FYI.

For the 3D framed objects, we'd like to make the optical axis and rays looks like they pass through the objects and their associated real/virtual images. Related issues are:
* https://github.com/phetsims/geometric-optics/issues/125
* https://github.com/phetsims/geometric-optics/issues/283
* https://github.com/phetsims/geometric-optics/issues/286

Trying to do this in a way that works with a transparent real/virtual image has turned into a bit of a nightmare. I've spent several weeks (easily 20+ hours) on this, and I'm not really happy with where it's at. There are so many edge cases, and it's not clear how to (or whether) to address them. There's also a significant performance hit to doing this, which makes dragging the Object feel sluggish on performance-challenged machines.

So over in https://github.com/phetsims/geometric-optics/issues/286, I suggested:
> (2) Replace 3D objects in picture frames with 2D objects that can be dragged similarly. The 3D perspective is gratuitous, doesn't add to the experience, doesn't support learning goals that can't be supported with 2D, and was inherited from the Flash version. Switching to 2D would also make several expensive issues (including this one) irrelevant. (This option is what I recommend.)

In https://github.com/phetsims/geometric-optics/issues/125#issuecomment-1015921755, @kathy-phet said:
> Before going down the road of replacing 3D with 2D, I think a design meeting to mock up what it would look like would be preferable. And I would recommend including MD in discussion/ideation too .... pedagogically my preference is the picture frames because we are not modeling the depth at all, and picture frame really makes that clear as this aspect of things being in a plane and when something is in focus.

I  threw together some 2D framed objects, plugged them into the sim, and adjusted a few things to make it all "work". I'll publish a dev version in a later comment.  But in summary, @arouinfar and I looked at the sim with 2D objects, and having 2D objects perpendicular to the lens just does not work.

**Comment by pixelzoom** [comment]
The dev version is [1.1.0-dev.16](https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.16/phet/geometric-optics_en_phet.html).  See example screenshot below.

The above commits will be reverted.

<img width="1077" alt="screenshot_1534" src="https://user-images.githubusercontent.com/3046552/150042492-5c2e0b8c-f3d6-4c45-9778-ed7a0964396e.png">

**Comment by pixelzoom** [comment]
@arouinfar anything that you'd like to add here? Close or leave open for discussion at design meeting?

**Comment by ariel-phet** [comment]
@pixelzoom I personally do not see a need to discuss this issue at design meeting. 2d object (in the way shown) do not really work. I think this issue can be closed.

**Comment by pixelzoom** [comment]
1/20/22 design meeting.

Agreed, non-starter. Closing.
