### ISSUE TITLE
Interplay between curvature radius and diameter of the lens.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#3]
On the flash simulation, when the diameter of the lens is increased, the lens width stays constant. At the same time, the numerical value of the slider for the curvature radius remains the same, which is physically impossible. A more "realistic" model of the lens would increase the width of the lens as well in order to preserve the curvature of the lens.  

If we decide to address this issue,  we would also need to address how to handle the case of a lens that has a diameter that is larger than the curvature radius.

Part of the "problem" arises from the range of values for the diameter of the lens that are unrealistic large in the simulation.

There are also good reasons to not address this issue as well.

The large diameter values for the lens stem from a design decision where the scaling along the X-axis is the same as along the Y-Axis. In this way the simulation preserve isotropy, and large lens diameter  are needed to make good use of vertical space. 
 
I'll mention that wave on a string is an example of a sim where this isotropy is broken, and the horizontal and vertical rulers have different scales. If we do break the isotropy, then it would be possible to make the lens behave a bit more realistically.

If we decide to maintain the isotropy, it is not physically possible to make "realistic" lens and we can safely close this issue.

**Comment by veillette** [comment]
This issue is a good starting point for a discussion at our next design meeting.

**Comment by sarchang** [comment]
The mirror and lens will behave realistically.
