### ISSUE TITLE
Adjust the opacity of the Image mask.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#300]
The Image (real or virtual) obscures portions of the optical axis and rays that pass through it.  Since the Image has transparency, sometime we can see those obscured things a little too well.  @arouinfar had the excellent idea of putting a mask behind the Image -- shaped like the image, color the same as the screen background - then setting the opacity of the mask to control how well we see the obscured parts of the optical axis and rays. 

@arouinfar has mentioned that he's like to adjust that opacity.  And how we set this opacity is also related to what we decide to do for https://github.com/phetsims/geometric-optics/issues/232 (opacity range of the Image).

I'm going to add a query parameter for setting the mask opacity, so that the sim team can experiment.

**Comment by pixelzoom** [comment]
I've added `?imageMaskOpacity` for experimenting with the mask's opacity. The default is `0.8`, the range is `[0,1]`, 0 is fully transparent, 1 is fully opaque.  You may wish to also adjust `?imageOpacityRange`, which was added for https://github.com/phetsims/geometric-optics/issues/232.

@ariel-phet would you mind take this for a spin, and suggesting what value looks good to you? @arouinfar and @kathy-phet also welcome to weigh in.

**Comment by pixelzoom** [comment]
Another related question... When I add the Object arrow representation, should its Image use the same opacity algorithm as the Images associated with framed Objects?

**Comment by ariel-phet** [comment]
@pixelzoom when paired with `?imageOpacityRange=0,0.75` I think the default value looks great and no need to adjust

**Comment by pixelzoom** [comment]
👍🏻 closing.
