### ISSUE TITLE
Put labels at tips of arrows.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#308]
One "polish" detail I'd like to take care of... I'd like the labels for arrows to be at their tips, not below them as in the screenshot below.  This is surprisingly difficult to accomplish with the current implementation of labels. I'll investigate, but we might consider living with it.

<img width="175" alt="screenshot_1549" src="https://user-images.githubusercontent.com/3046552/153689224-e93140dd-0657-4f87-b9ae-9db90e1f532a.png">

**Comment by arouinfar** [comment]
I actually like keeping all labels below the associated items. It looks cleaner that way. I realize you are trying to put the "object" label as close as possible to the origin of the point source, but I don't think that detail is necessary. I've made a note in the Teacher Tips issue.

**Comment by pixelzoom** [comment]
Great, then I won't spend time on this. Closing.
