### ISSUE TITLE
Revise hotkeys for rulers.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#310]
In https://github.com/phetsims/scenery/issues/1355#issuecomment-1039339856, @arouinfar said:

Member
[arouinfar](https://github.com/arouinfar) commented [2 hours ago](https://github.com/phetsims/geometric-optics/issues/new#issuecomment-1039339856)
I really like @terracoda's idea to cycle through the items. In Geometric Optics there will be 2-5 items visible on screen at any given time. If users are able to cycle in either direction, there would be at most 2 jumps to get to the desired location. Worst case, it would take 4 jumps if traveling in one direction. Not sure what the best key combination would be, but maybe J+I to jump between items in the play area?

I think this strategy could also generalize to more complicated situations. For example, in CCK we could use this method to jump the voltmeter probes to the vertices between circuit elements (or even jump between batteries, resistors, etc. separately). There, it wouldn't be feasible to do something like J+B+1, J+B+2, etc. to jump to a specific battery. There could be 10+ batteries in the play area and they are indexed by creation time so the number isn't going to be clear to the user. There will ultimately still be a lot of key presses to cycle through things, but for users with motor control issues, the repetitive key presses are probably far easier than precisely placing a probe with the arrow/WASD keys.

**Comment by pixelzoom** [comment]
OK, I'll proceed with implementing a cycle. The order will be optic, object1, object2, image1, image2. I'll also make up a new description for the keyboard-help dialog.

**Comment by pixelzoom** [comment]
In [1.1.0-dev.25](https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.25/phet/geometric-optics_en_phet.html), I implemented a J+R hotkey that cycles through an ordered list of useful measuement points.  The points for each scene are:

* Arrow Objects: optic, arrowObject 1, arrowImage1, arrowObject2, arrowImage2
* Framed Objects: optic, frameObject, secondPoint
* Light Objects: optic, lightObject1, lightObject2

This implementation feels a bit bewildering.  So after discussions with @arouinfar and @ariel-phet, I'm going to make the following changes:

* J+R will cycle through a list of useful measurement points, as they appear in the sim _from left to right_
* When we get to right-most point, we'll wrap around to the left-most point
* Horizontal vs vertical rulers will have different lists of measurement points
* Horizontal rulers will exclude image points to the right of the optic (because they are not useful), and add left focal point
* Vertical rulers will use the same points that we have now (as above, per scene)

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master or [1.1.0-dev.26]().

Here's a summary of the measurement points for each "scene".

Arrow Objects: 
* vertical ruler: optic, arrowObject 1, arrowImage1, arrowObject2, arrowImage2
* horizontal ruler: same as vertical ruler + left F point + left 2F point

Framed Objects: 
* vertical ruler: optic, frameObject, secondPoint
* horizontal ruler: same as vertical ruler + left F point + left 2F point

Light Objects: 
* vertical ruler: optic, lightObject1, lightObject2
* horizontal ruler: same as vertical ruler + left F point + left 2F point

Rules:
* Points are visited left-to-right, with wraparound to leftmost point
* Horizontal ruler ignores points to the right of the optic.
* Points are ignored if they are not visible, outside the ruler's drag bounds, or match the ruler's current position

**Comment by arouinfar** [comment]
I reviewed in master, and the behavior feels really nice. Thanks @pixelzoom!
