### ISSUE TITLE
Adjust ranges for ROC, IOR, Focal Length, and Diameter.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#311]
The ranges for ROC and IOR need to be adjusted.   It's currently possible to get focal points a little to close to the optic (first screenshot below) or outside the bounds of the first zoom level (second screenshot below).  Lens and Mirror will have different ranges.  The current values are:

```js
// Lens.ts
      radiusOfCurvatureRange: new RangeWithValue( 30, 130, 80 ), // in cm
      indexOfRefractionRange: new RangeWithValue( 1.2, 1.9, 1.5 ), // unitless

// Mirror.ts
      radiusOfCurvatureRange: new RangeWithValue( 150, 300, 200 ), // in cm

      // Although a mirror does not have an index of refraction, its focal length is equivalent to a lens
      // with an index of refraction of 2.
      indexOfRefractionRange: new RangeWithValue( 2, 2, 2 ), // unitless
```

<img width="1174" alt="screenshot_1554" src="https://user-images.githubusercontent.com/3046552/153964506-1357974e-8290-4e23-af11-e7b8675e773b.png">
 
<img width="1175" alt="screenshot_1555" src="https://user-images.githubusercontent.com/3046552/153964617-b5ef7114-1aeb-4ae8-a5df-705d7d3e752f.png">

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics/issues/311, we made Focal Length settable in the UI, with 'direct' vs 'indirect' models of focal length.  So we'll also need to adjust the ranges for Focal Length. 

Here's an updated summary of the ranges for ROC, IOR, and focal length:

```js
// Lens.js
      directFocalLengthModelOptions: {
        focalLengthRange: new RangeWithValue( 30, 130, 80 ), // in cm
        indexOfRefraction: 1.5 // fixed and unitless
      },
      indirectFocalLengthModelOptions: {
        radiusOfCurvatureRange: new RangeWithValue( 30, 130, 80 ), // in cm
        indexOfRefractionRange: new RangeWithValue( 1.2, 1.9, 1.5 ) // unitless
      }

// Mirror.js
      directFocalLengthModelOptions: {
        focalLengthRange: new RangeWithValue( 75, 125, 100 ), // in cm
        indexOfRefraction: 2 // fixed and unitless
      },
      indirectFocalLengthModelOptions: {
        radiusOfCurvatureRange: new RangeWithValue( 150, 300, 200 ), // in cm
        indexOfRefractionRange: new RangeWithValue( 2, 2, 2 ) // unitless
      }
```

**Comment by arouinfar** [comment]
@pixelzoom  can you please hook the parameters in https://github.com/phetsims/geometric-optics/issues/311#issuecomment-1047141232 up to query parameters?

**Comment by pixelzoom** [comment]
Query parameters for optic parameters:

**Lens screen**:

| Query Parameter | Optic Parameter | default |
| :---: | --- | --- |
| `rocRangeLens` | radius of curvature (ROC) | `30,130,80` |
| `iorRangeLens` | index of refraction (IOR) | `1.2,1.9,1.5` |
| `fRangeLens` | focal length (f) | `30,130,80` |
| `dRangeLens` | diameter (d) | `60,120,80` |

**Mirror screen**:

| Query Parameter | Optic Parameter | default |
| :---: | --- | --- |
| `rocRangeMirror` | radius of curvature (ROC) | `150,300,180` |
| - | index of refraction (IOR) | `2` (fixed) |
| `fRangeMirror` | focal length (f) | `75,125,90` |
| `dRangeMirror` | diameter (d) | `60,120,80` |

**Comment by pixelzoom** [comment]
Reminder that switching focal length between 'direct' and 'indirect' via the Options dialog will cause the current model's valuese to be written to the new model.  So if you start the GO with `? fRangeLens=10,100,50`, then swtich from 'indirect' to 'direct',  you'll see your focal-length range, but not your default value.  Start the sim with `focalLengthControl=direct` if you want to test only `fRangeLens` or `fRangeMirror`.

Also make sure that the final values that you choose work with both the 'indirect' and 'direct' models.

**Comment by pixelzoom** [comment]
It's highly recommended to run with ?ea (assertion enabled) when using these query parameter. These are not public query parameters, so if a value is incorrect, the sim will complain loudly in the browser console. If you don't run with ?ea, then the sim may work strangely, or fail a some later point.

**Comment by pixelzoom** [comment]
Raising priority to high, because we can't proceed with dev-lite testing without this one.

**Comment by arouinfar** [comment]
Thanks for setting up these query parameters @pixelzoom. Let's go with:

- [ ] `rocRangeLens=40,120,80`
- [ ] `iorRangeLens=1.2,1.9,1.5`
- [ ] `fRangeLens=40,120,80` (to keep it in sync with the focal lengths at IOR=1.5)
- [ ] `fRangeMirror=75,150,90` (so it matches up with `rocRangeMirror`)

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please review.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom
