### ISSUE TITLE
Separate opacity ranges for "framed objects" vs "arrow objects" 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#312]
After discussions/experiments with @arouinfar and @ariel-phet, it was decided that we need separate opacity ranges for "framed objects" `[0,0.75]` vs "arrow objects" `[0,0.6]`.

**Comment by pixelzoom** [comment]
Framed objects and arrow objects now have separate opacity ranges, controlled by separate query parameters. The defaults are `?frameObjectOpacityRange=0,0.75` and `arrowObjectOpacityRange=0,0.6`.

@arouinfar please review.

**Comment by arouinfar** [comment]
In general, the opacity of the arrows looks good, but I should review this as a part of #319 to make sure the final colors also work with this opacity range. I've tagged this issue in #319 and added the relevant query parameters, so I'll go ahead and close this issue.
