### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#319]
Revisit the overall color profile, and address these specific issues:

* https://github.com/phetsims/geometric-optics/issues/224
* https://github.com/phetsims/geometric-optics/issues/225
* https://github.com/phetsims/geometric-optics/issues/226
* https://github.com/phetsims/geometric-optics/issues/275
* #322 
* #312 `arrowObjectOpacityRange=0,0.6`

**Comment by pixelzoom** [comment]
@arouinfar I wasn't sure if you wanted me to close the issues listed above as part of this merging to one "Colors" issue.  Up to you...

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I'll close the linked issues and we can continue color discussions in this issue.

**Comment by pixelzoom** [comment]
I discovered that the second point/object is not currently using PhetColorScheme.RED_COLORBLIND, which is `rgb( 255, 85, 0 )`.   It's currently using 'rgb( 255, 51, 51 )'.

**Comment by arouinfar** [comment]
Here are the colors reviewed in the design check-in:
- [ ] panelFill `#e5f7fe` (Vector Addition background color)
- [ ] realRays1: black
- [ ] realRays2: `rgb(255, 51, 51)` 
- [ ] guideArm1Fill: `rgb(230,230,230)`
- [ ] guideArm2Fill: `rgb(255, 51, 51)`

Here are some screenshots (taken from an stale version of master, so ignore the zoom buttons)
![Geometric Optics screenshot (10)](https://user-images.githubusercontent.com/8419308/158883593-16359b5a-9d77-4839-a86e-f02029365658.png)
![Geometric Optics screenshot (11)](https://user-images.githubusercontent.com/8419308/158883599-7f0016e4-6b6c-4745-90a5-f6844a89316c.png)
![Geometric Optics screenshot (13)](https://user-images.githubusercontent.com/8419308/158884206-3987ac7f-cca4-4858-b903-abd57f2deb55.png)

**Comment by pixelzoom** [comment]
I checked with @arouinfar via Slack, and we are ditching the "projector" color profile.  So I'll remove those colors from GOColor.ts, and remove the "Projector Mode" checkbox from the Options dialog.

**Comment by pixelzoom** [comment]
Projector Mode has been removed, and default color profile has been revised as requested. Back to @arouinfar for review, close if it looks OK.

**Comment by pixelzoom** [comment]
One more things.... I noticed that our red is `rgb( 255, 51, 51 )`, not PhetColorScheme.RED_COLORBLIND `rgb( 255, 85, 0 )`.   Is that an issue?

**Comment by pixelzoom** [comment]
A couple more things...

* I noticed that our red is `rgb( 255, 51, 51 )`, not PhetColorScheme.RED_COLORBLIND `rgb( 255, 85, 0 )`.   Is that an issue?

* Has the new color profile been tested for colorblind issues?

**Comment by arouinfar** [comment]
The red we've been using `rgb( 255, 51, 51 )` had good contrast with previous colors, but it's not so great against the black rays. 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/8419308/159060922-ebb6820c-7fb4-42af-8777-b3dc02774807.png">

@pixelzoom let's swap out the red for `PhetColorScheme.RED_COLORBLIND`. I don't really love they way it looks, in general, but it definitely improves the contrast against black.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/8419308/159060956-7ca9923a-4dd4-4ff4-8a0b-e53e1fe1911f.png">

**Comment by pixelzoom** [comment]
Changed to `PhetColorScheme.RED_COLORBLIND` in the above commit.   I also prefer a nice pure red.  But I think this is a fine compromise.

Closing.
