### ISSUE TITLE
Panel sizes in Mirror and Lens Screens

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#32]
![image](https://user-images.githubusercontent.com/7633344/121583144-e329ac00-c9fd-11eb-8040-a0772335e27d.png)
![image](https://user-images.githubusercontent.com/7633344/121583256-081e1f00-c9fe-11eb-9965-069c50c31ae6.png)

The content of the panel in Lens and Mirror is slightly different, yet similar.
Since their content is different, scenery creates a panel of different sizes

This issue is to track any request about sizing and options that should be shared between the two control panels.

**Comment by sarchang** [comment]
Design meeting: control panel can adjust size based on elements

**Comment by veillette** [comment]
The panels do not need to have the same size.

**Comment by sarchang** [comment]
Panels adjust based on elements.
