### ISSUE TITLE
Focal points appear too "grabbable" 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#322]
@pixelzoom @arouinfar 

While reviewing a separate sim (Center and Spread) we were showing a feature of Geometric Optics, and several design team members commented that the focal points appear as though they should be draggable. 

My two suggestions to try might be:

1. Make the focal points slightly smaller
2.  Reduce the opacity of the fill

**Comment by pixelzoom** [comment]
> 1. Make the focal points slightly smaller

We previously polished the size of these, and the team was happy with the size. In choosing the current size, they needs to be larger than the 2F points; and the diameter of the black dot in the center needs to be wider than lineWidth of the light rays.

> 2. Reduce the opacity of the fill

Focal points overlap with other things on the screen. If they're transparent, you'll get all kinds of odd color combinations. If we use a less saturated color, that will negatively affect their visibility when the sim is projected on a screen.

My vote is to leave them as is.  If the user tries to grab them, so what? They're likely to try to grab the optic too. They'll quickly learn that they aren't draggable. It's part of exploring.

**Comment by arouinfar** [comment]
Thanks for bringing this to our attention @ariel-phet.

The Flash version used X's which didn't look particularly interactive but were a non-standard representation and bit tricky to measure.There are a few constraints we're working with here:
1. The focal points and 2F points need to be visible at the back of the classroom and distinguishable from one another.
2. The focal point is a <i>point</i>. Its center needs to be easy to perceive/measure and remain visible even when rays obscure it. This is why there is a black dot at its center. 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/8419308/155058978-a8869673-1ca9-4514-9d4b-79e150ea14ae.png">

@pixelzoom made the focal points a bit smaller, but they became too similar in size to the 2F points. We can certainly try another less saturated color for the fill, but I wouldn't actually crank down the opacity. Colors are being polished in #319 so I will add this issue there, and close.
