### ISSUE TITLE
Arrows should be resizeable in the Mirror screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#323]
Arrows currently cannot be resized in the Mirrors screen because drag-lock is on.  That's appropriate (and necessary) for the framed objects, but not the arrows.

**Comment by pixelzoom** [comment]
@arouinfar I'm wondering if we need to add the drag-lock toggle button to the Mirrors screen, so that arrows can be locked if desired.   The button would be disabled for framed objects, but that might still be confusing if the disabled stated showed that dragging was not locked. Maybe hide the button for framed objects?

**Comment by arouinfar** [comment]
@pixelzoom that's a great idea. Yes, I think the arrows will need the drag-lock feature, so let's add the button for the arrow scene but hide it when irrelevant.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

Once I got into this, it seemed to make more sense to disable (instead of hide) the drag-lock button.  For Pencil or Penguin, the button will always be disabled, and will indicate that dragging is locked to horizontal. It's the same for all 3 mirror shapes. (If you want to freely drag framed objects for the flat mirror, use Basics.)

![screenshot_336](https://user-images.githubusercontent.com/3046552/155631159-c84e48ae-a99b-4802-988c-3bd23ad18eb2.png)

When you switch to Arrow, the drag-lock button becomes enabled, and drag lock is off, so you can move the arrow freely. Again, it's the same for all 3 mirror shapes.
 
![screenshot_337](https://user-images.githubusercontent.com/3046552/155631352-109b0883-a9b7-4b77-8142-6f6ad4e1fa50.png)

There's one caveat, best described by steps:

1. Go to the Mirror screen
2. Select Arrow. Note that the drag-lock state is "off".
3. Click the drag-lock button to change state to "on".
4. Select Pencil.
5. Select Arrow.  Note that the drag-lock state is once again "off", it's not restored to the previous state that we put the arrow in.  So anytime you select Arrow from the combo box, you'll be starting with drag-lock off.

The issue here is that there's 1 `dragLockedProperty`, shared by the entire screen.  I don't think this is a big deal, and might even make the most sense.  But I wanted to point it out.  And I should mention that trying to do otherwise will be a big PhET-iO headache.

**Comment by arouinfar** [comment]
> Once I got into this, it seemed to make more sense to disable (instead of hide) the drag-lock button. For Pencil or Penguin, the button will always be disabled, and will indicate that dragging is locked to horizontal.

Good call, I think hiding the button would have been problematic. The behavior in master looks good.

> The issue here is that there's 1 `dragLockedProperty`, shared by the entire screen. I don't think this is a big deal, and might even make the most sense. But I wanted to point it out. And I should mention that trying to do otherwise will be a big PhET-iO headache.

This makes sense to me, but thanks for pointing it out. The current implementation looks reasonable to me, so I think we can call it here. Thanks @pixelzoom.
