### ISSUE TITLE
Can we enable cueing arrows using a query parameter, instead of a Property?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#324]
We currently have Property `geometricOptics.global.view.options.cueingArrowsEnabledProperty` which determines whether cueing arrows will be shown.  This Property is "PhET-iO only" and cannot be controlled from the sim UI. Managing this Property results in some complicated code, and the implementation would be much simpler (and consistent) if we treated this feature like the Guides and 2F features -- that is, set on startup via query parameter instead of dynamically via a Property.

Is there any reason why the cueing arrows feature needs to be dynamically turned on/off after the sim is running? Can we change this to query parameter `enableCueingArrows`?

**Comment by arouinfar** [comment]
Great question @pixelzoom. I don't see why a client would need to dynamically change the state of the cueing arrows, so a query parameter sounds reasonable to me.

**Comment by pixelzoom** [comment]
The cueing arrows feature is now enabled/disabled with query parameter `enableCueingArrows`.  It's a public query parameter, and defaults to `true`.

Closing.
