### ISSUE TITLE
stringTest

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#327]
Verify that the sim passes stringTests.

**Comment by pixelzoom** [comment]
@arouinfar ready for review. Tested with `stringTest=long`, `stringTest=double`, `stringTest=X`.  To make all features visible that involve strings, run with `enableGuides=true&enable2F=true` and check all checkboxes.

**Comment by arouinfar** [comment]
I reviewed in master with `enableGuides=true&enable2F=true` and all variations of `stringTest`. Everything looks good @pixelzoom, thanks!
