### ISSUE TITLE
Spot intensity seems to vary incorrectly with change in optic diameter

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#335]
@pixelzoom @arouinfar I do not think the spot "brightness" algorithm is quite correct when using the light source option. For a given configuration the spot size grows larger if the screen is not placed at the focus and the optic diameter is increased -- that behavior is correct. However, the spot appears to dim if you make the optic diameter larger. I think in this situation the spot size should grow but should maintain a constant color saturation. Using the idea of "many rays" the density of rays is not varying in the interior of the spot, so I don't believe the intensity of the light should be growing smaller at the spot.

Not sure if this is an optical illusion, or such, but seems worth discussing. 

See as part of #328 --Video illustration:

https://user-images.githubusercontent.com/4051174/155854127-fefd86f0-58ac-4a66-b262-d028ab555232.mp4

**Comment by pixelzoom** [comment]
Here's a description of the current implementation, which is in LightSpot.js

* A spot's intensity range is [0,1]
* Intensity is a function of spot diameter (D)
* Intensity = 7 / D, constrained to [0,1], so any spot with diameter <= 7 cm will be full intensity

Or as the author of this algorithm wrote in the code comments:

```js
    // The normalized intensity of the light spot is in the range [0,1].
    // The spot is dimmer when the light is spread on a larger surface.
    // To preserve dynamic range, the intensity is instead inversely proportional to the diameter.
    // The value saturates to max intensity for a spot diameter <= 7 cm.
```

Let me know specifically how you want to change this algorithm.

**Comment by ariel-phet** [comment]
@pixelzoom I will need to chew on this a bit

**Comment by ariel-phet** [comment]
@pixelzoom the spot diameter basically scales linearly with the diameter of the lens. So I think we just need to add a factor to the algorithm that takes the lens diameter into account. Perhaps just a multiplicative factor (call the minimum lens diameter of 60 cm "1" and the maximum lens size of 120 cm "2" and then multiply the opacity representing intensity by that factor.  The saturation condition should still be enforced (any spot less than 7cm is full opacity).

**Comment by pixelzoom** [comment]
> @pixelzoom the spot diameter basically scales linearly with the diameter of the lens. 

In addition to, our instead of, the diameter of the spot itself ?

**Comment by pixelzoom** [comment]
3/3/2022 

 @ariel-phet and I will take a stab at this next week. I'll contact him to set up a time.

**Comment by pixelzoom** [comment]
@ariel-phet and I knocked this one off this morning.  The algorithm in LightSpot.ts is:

```js
        if ( ( lightSpotDiameter === 0 || lightSpotDiameter === null ) ) {
          return 0;
        }
        else {
          assert && assert( optic.diameterProperty.range ); // {Range|null}
          const opticDiameterRange = optic.diameterProperty.range!;
          const opticDiameterFactor = Utils.linear( opticDiameterRange.min, opticDiameterRange.max, 0.5, 1, opticDiameter );

          // Any light spot less than this diameter will have full intensity when the optic diameter is at its maximum.
          const FULL_INTENSITY_DIAMETER = 14; // cm
          const lightSpotDiameterFactor = FULL_INTENSITY_DIAMETER / lightSpotDiameter;

          return GOConstants.INTENSITY_RANGE.constrainValue( opticDiameterFactor * lightSpotDiameterFactor );
        }
```

@arouinfar @ariel-phet ready for verification in master or [1.1.0-dev.35](https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.35/phet/geometric-optics_en_phet.html).

**Comment by ariel-phet** [comment]
Looks great to me, I think this issue can be closed.

**Comment by arouinfar** [comment]
Agreed, this does look great. Thanks @pixelzoom @ariel-phet!
