### ISSUE TITLE
Rulers vs tape measures

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#336]
For #328.

In https://github.com/phetsims/geometric-optics/issues/334, @ariel-phet identified a need for a read-out of the values (f, do, di) for the image equation.  This was motivated by the fact that there's a usability problem with the rulers. In many cases (especially when zoomed out) the horizontal ruler is not long enough to measure the desired distances.  

I suggested replacing rulers with tape measures. @ariel-phet agree that would be an improvement.  But it would be a large cost, and therefore might not be feasible at this late point in the process (though I am ahead of schedule). 

---
Relevant comments from https://github.com/phetsims/geometric-optics/issues/334:

@ariel-phet said in https://github.com/phetsims/geometric-optics/issues/334#issuecomment-1052443526:
> ...  Either way, there does seem to be a slight usability issue in terms of measuring image or object distances that exceed the length of the ruler.

@pixelzoom said in https://github.com/phetsims/geometric-optics/issues/334#issuecomment-1052450128:
> There's more than a slight usability isssue, and I've never understood the rulers in this sim. As you've identified, there are things that can't be measured when you're full zoomed in. But the rulers are almost useless when you zoom out.
> 
> A single tape measure would be a much more useful measuring device. And we could ditch the toolbox, and just have the tape measure in the upper-right (where the toolbox is) at all times.

@ariel-phet said in https://github.com/phetsims/geometric-optics/issues/334#issuecomment-1052459163:
> @pixelzoom -- if we are going there....
> 
> A tape measure (or allowing two tape measures) would frankly be ideal. I would think then you would have the tape measures be a bit "snappy" so that they preferentially snap to interesting points, like the center of the optic and the imaging points. A tape measure would also you to measure the diagonal if desired (which would allow further confirmation of the role of similar triangles). Our tape measures also have a readout so you could precisely measure distances.
> 
> The one "advantage" of a ruler is that it allows some measurement error, so perhaps just not having a tape measure be "snappy" would also achieve that goal. These also seem like questions worthy of a short design discussion.

@pixelzoom said in https://github.com/phetsims/geometric-optics/issues/334#issuecomment-1052480183:
> 2 tape measure is a toolbox is certainly doable. It will come with a very large cost. We spent an enormous amount of design & implementation time on the rulers (dynamic scale, alt input, hotkeys, iO,...) and we'd need to revist all of that for tape measures.

@ariel-phet said in https://github.com/phetsims/geometric-optics/issues/334#issuecomment-1052488399:
> @pixelzoom then my guess is that for the moment doing tape measures is not feasible and would perhaps be best as a separate issue as a design enhancement in future (might make a nice project for an intern/new dev/etc). We can keep this issue focused on whether we want to have the option for some sort of readout of values (which seems like it would be low cost comparatively).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics/issues/334#issue-1152060670, @ariel-phet provided this screenshot to demonstrate that the horizontal ruler is too short ("is not the right length to measure the image distance in one measurement"):

![measurement](https://user-images.githubusercontent.com/4051174/155853588-4d2de2d4-c751-4d11-acf1-14368042478f.PNG)

But while investigating this running with `?dev`, I discovered tht the horizontal ruler is in fact long enough to measure distances in the standard dev bounds, and in all zoom levels. See screenshots below.  Measuring only becomes a problem if you have a browser window that is wider than dev bounds.

<img width="1282" alt="screenshot_1582" src="https://user-images.githubusercontent.com/3046552/156064958-aa2103b5-a8c4-4ffa-91cc-24a982312a8c.png">

<img width="1285" alt="screenshot_1583" src="https://user-images.githubusercontent.com/3046552/156064981-e4ac0636-1b6c-4d1b-a53d-2f3758bba59b.png">

**Comment by pixelzoom** [comment]
Discussed with @arouinfar on 2/28/2022.  She's going to add comments about why we're not going to make this change.

**Comment by arouinfar** [comment]
Thanks for factoring out the measuring tape discussion into this issue @pixelzoom.

Early on, we considered using measuring tapes instead of rulers. A measuring tape would quickly provide more precise data to users. However, we ultimately decided to stick with rulers because it better fit the goals related to measurement and experimental error. I also think the scale of this project was very different then, so we didn't consider the option of having both types of measurement tools.

I would absolutely love to add a MeasuringTapeNode to this sim. It would speed up data collection and could perhaps even drive the rapid inquiry cycles that students often engage in when using sims. It would also streamline the process for instructors using the sim as a demo.

However, this sim supports alternative input, and the MeasuringTapeNode is complex. As far as I know, we haven't established a pattern for such a complex tool. It would likely need two separate focusable regions (tool body vs. tip) and we would need support from the a11y team for design and implementation consultation. I just don't think it's doable this close to publication, but I would reconsider in the future once MesuringTapeNode has alt input support.

**Comment by kathy-phet** [comment]
I would still defer - or even close this. We have the "markers" now that can be used if needed to help with this sort of measurement challenge (just like you would do in a lab).

**Comment by pixelzoom** [comment]
I'd like to close this. I think it's highly unlikely that we'll ever replace rulers with tape measures.  @arouinfar if you agree, please close.

**Comment by arouinfar** [comment]
I agree, let's close. Markers address the measurement challenges.

MeasuringTapeNode also doesn't have full UI sounds, so that would be a potential barrier in the future.
