### ISSUE TITLE
Does `framedImage2` need to be instrumented?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#339]
For #237 

Here's the current structure of `model.framedObjectScene`:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/8419308/156019374-2f8ee701-c4aa-478d-ad6b-8fe91f87025f.png">

There is a `framedImage2` which is confusing since there is only one framed image. Its children have the same values as their cousins under `framedImage1`. The useful data related to the second point is under `secondPoint`. Seems like we can uninstrument `framedImage2`, but if not, I just won't feature any of it.

**Comment by pixelzoom** [comment]
> Does framedImage2 need to be instrumented?

Any yes, `framedImage2` does need to be instrumented. The client will presumably want to know where the rays from `secondPoint` would form an image.  And `framedImage2` has state that must be saved/restored by iO.

**Comment by arouinfar** [comment]
I realized that`framedImage2.positionProperty` is the coordinate of the second point, which I had overlooked originally. After discussing with @pixelzoom, we can close this issue.
