### ISSUE TITLE
Create `magnificationProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#340]
For #237 

It would be helpful to have a `magnificationProperty` for the relevant images: `framedImage1`, `arrowImage1`, and `arrowImage2`. @pixelzoom can you please create it?

**Comment by pixelzoom** [comment]
`magnificationProperty` already exists in the model.  It's a DerivedProperty.  I've added instrumentation in the above commit, please review.

FYI,  in general, DerivedProperty elements don't need to be instrumented for iO state.  So there are other internal DerivedProperty instances that I've chosen not to expose in the API.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The `magnificationProperty` looks good in the tree and behaves as expected.

> FYI, in general, DerivedProperty elements don't need to be instrumented for iO state

Thanks, good to know!
