### ISSUE TITLE
Instrument light spots in the view

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#343]
For #237 

The data related to `lightSpot1` and `lightSpot2` lives entirely under the model, but users may naturally look for the light spots in the view. @pixelzoom please add `lightSpot1Node` and `lightSpot2Node` to the view under `lensScreen.view.scenes.lightObjectSceneNode` with a linked property that points back to the corresponding model element.

We currently do something similar for the `opticalAxisNode` which only contains a linked property to the corresponding model element.

**Comment by pixelzoom** [comment]
The decision to not instrument light spots in the view was previously made in https://github.com/phetsims/geometric-optics/issues/269 (there's a comment in the code that says "do not instrument").    But I think this is a good change, so I'll proceed.

**Comment by pixelzoom** [comment]
Done in the above commit.  Note that `lightSpotNode1` and `lightSpotNode2` both have instrumented `visibleProperty`, so you'll see those in the Studio tree too.  See screenshot below.  For `lightSpotNode1`, visibileProperty is linked to `opticalImage1.visibleProperty`.  For `lightSpot2Node`, visibleProperty is derived from `opticalImage2.visibleProperty` and `visibleProperties.secondPointVisibleProperty`.

@arouinfar please review in master.

<img width="266" alt="screenshot_1584" src="https://user-images.githubusercontent.com/3046552/156068671-83ab0dd8-58e4-4c92-b8ed-44723f63fc4a.png">

**Comment by arouinfar** [comment]
The tree structure looks good in master, thanks!

>  The decision to not instrument light spots in the view was previously made in https://github.com/phetsims/geometric-optics/issues/269 (there's a comment in the code that says "do not instrument").    But I think this is a good change, so I'll proceed.

Thanks for the reminder @pixelzoom. This change also enables light spots to be selectable in Studio, but the decision in #269 predates this Studio feature.
