### ISSUE TITLE
Consider adding 'Star' object back

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#344]
@pixelzoom @arouinfar although I generally like the trimming down of objects we have done, I think on the flat mirror screen of basics it might be nice to reintroduce the "star" object. Noticed as part of phetsims/geometric-optics-basics#7 

I think the star might offer a nice contrast to the penguin because of its horizontal symmetry (the pencil does have that quality but not quite as obviously), and also when I play with this screen, I do suppose having more objects is slightly more "fun"

My understanding is returning this object would be a trivial change, and I think it would make a minor improvement in the richness of the screen.

**Comment by ariel-phet** [comment]
@pixelzoom looks good in master, thanks!

**Comment by arouinfar** [comment]
Thanks for this suggestion @ariel-phet. You brought up a lot of really good points, and I totally agree that the star is an interesting example. Thanks for adding it back @pixelzoom.
