### ISSUE TITLE
Add linked elements

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#346]
For #237 

I found a few places that would benefit from having linked elements.

- [x] Link `model.scenes.arrowObjectScene.arrowImage*` under `view.scenes.arrowObjectSceneNode.arrowImage*Node`
- [x] Link `model.scenes.lightObjectScene.projectionScreen.positionProperty` under `view.scenes.lightObjectSceneNode.projectionScreenNode` (Could alternatively link one level up at `projectionScreen`, up to you @pixelzoom.)

**Comment by pixelzoom** [comment]
> ... (Could alternatively link one level up at `projectionScreen`, up to you @pixelzoom.)

I did link to `projectionScreen`.  While `projectionScreen` currently only has `positionProperty`, that could change someday (unlikely, but possible).   In general, by sticking with the convention of linking Nodes to their full model elements, we minimize the possibility of breaking the API (and client wrappers) in the future.

@arouinfar ready for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master.

> In general, by sticking with the convention of linking Nodes to their full model elements, we minimize the possibility of breaking the API (and client wrappers) in the future.

That makes sense to me @pixelzoom. I'll try to remember that when it inevitably comes up in other sims.
