### ISSUE TITLE
Make visibleProperty editable for all NumberControl elements.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#347]
The visibility of Focal Length, ROC, and IOR NumberControls is currently controlled by the sim, based on whether 'direct' or 'indirect' is selected for the focal-length model. @arouinfar would like all NumberControls to all have visibleProperty that can be controlled by the iO client.   So for example, a client should be able to hide the ROC control when they have 'indirect' selected.

This will require significant restructuring of the code.

**Comment by pixelzoom** [comment]
Done in the above commit.  The wrapper Nodes required to make this work did not require instrumentation, because their `visibleProperty` elements are derived.

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! This looks great in master.
