### ISSUE TITLE
Avoiding name collisions with common code in classes

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#35]
We should go over the name of the modules and make sure we dont have very generic name that conflict with common code.  (see for  instance https://github.com/phetsims/bending-light/issues/399 for example of problems).

Our solution would be to prefix the classes/modules with GeometricOptics.

**Comment by veillette** [comment]
There are two classes, that although do not conflict with common code, could be refactored: 
- [ ] ControlPanel
- [ ] ToolboxPanel

Their names are perhaps too common and will conflicts with many other sims.

**Comment by pixelzoom** [comment]
In the above commit, ToolboxPanel was renamed to RulersToolboxPanel, since it holds only rulers.

Closing.
