### ISSUE TITLE
Image looks like it gets less "bright" when should get more "bright" 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/geometric-optics#350]
The brightness of the real image seems to be pretty good to me, except under the case when the image gets quite small and the light is all shining into a small area. 

Starting from this case: 
![image](https://user-images.githubusercontent.com/5096804/156235601-67f2c4f8-c372-415a-bb05-7c79e2852199.png)

And changing the radius of curvature to smaller, the area drops to about 1/4 of its value, and so brightness should increase by x4 (density of light rays is much higher now). It appears (to my eye) to actually get dimmer. Perhaps it is at the limit of its brightness so doesn't actually dim, just stays the same opacity at a smaller size. @pixelzoom - Are we at a limit here and it doesn't get less transparent?

**Comment by pixelzoom** [comment]
No, we're not at any kind of limit.  ROC (and IOR) have no affect on image opacity.

Light intensity is a value in the range [0,1], and is a function of optic diameter and magnification.  Manification is a function of the optic position and the object position.  Here's the algorithm ( implemented in OpticalImage.ts), with the original author's comments:

```ts
// effect of the diameter of the optic on the light intensity of the Image (Hollywooded)
diameterFactor = diameter / maxDiameter;

// effect of the distance on the opacity, as 1/magnification for upscaled image (Hollywooded)
distanceFactor = Math.min( 1, Math.abs( 1 / magnification ) );

// product of the two factors
intensity = diameterFactor * distanceFactor;
```

Light intensity is linearly mapped to opacity ranges for rendering.  Opacity was previously dicussed and fine-tuned in https://github.com/phetsims/geometric-optics/issues/232 and https://github.com/phetsims/geometric-optics/issues/312.  There are separate opacity ranges for images associated with Arrows vs Framed Objects, settable via query parameters.  The same range is used for both real and virtual images. The currently ranges are:

Arrows:`?arrowImageOpacityRange=0,0.6`
Framed Objects: `?frameImageOpacityRange=0,0.75

@arouinfar @kathy-phet let me know what (if anything) you want to change here.

**Comment by pixelzoom** [comment]
Sorry, I take that back... ROC and IOR do affect intensity.  There is a limiting factor, and it's this line in the above algorithm:

```js
// effect of the distance on the opacity, as 1/magnification for upscaled image (Hollywooded)
distanceFactor = Math.min( 1, Math.abs( 1 / magnification ) )
```

This will always be 1 for an image whose size is less than the object size (down-sized).   And in the case that you've shown, the diameter is the max (120 cm).   So intensity will be 1 for all images that are down-sized, and changing ROC will have no affect on light intensity or image opacity.

**Comment by pixelzoom** [comment]
Here's the above algorithm with improved documentation:

```js
// Affect of optic diameter
diameterFactor = diameter / maxDiameter;

// Affect of magnification, for up-scaled images only. For down-scaled images, magnification has no affect.
magnificationFactor = Math.min( 1, Math.abs( 1 / magnification ) );

// product of the two factors
lightIntenity =  diameterFactor * magnificationFactor;
```

**Comment by kathy-phet** [comment]
Hi Chris, 

Magnification should have an impact for downscaled images - making them brighter if the captured light stays the same amount (e.g. if the diameter of the mirror or lens stays constant). 

Technically, if the magnification is 0.5, it means that you have the same light in 1/4 of the area, and the brightness would be 4 times larger. 

I don't thing we can go brighter than the original image as a technical sense but in reality it could appear brighter than the original. If it goes smaller, can we develop a scale that goes up to opacity of "1", perhaps with some sort of scale that brightens but maybe not as fast as it normally would. but where an image that is 1/4 the size of the original might appear full brightness?

**Comment by pixelzoom** [comment]
If @veillette is available, I'd be interested in the history behind the current algorithm - which now lives in OpticalImage.ts as `lightIntensityProperty`.  "Hollywooded" is mentioned in the comments, so someone must've decided that some compromises were necessary/acceptable.

That said... I'll be happy to change the algorithm.  Provide me with the specific formula for computing light intensity in the range [0,1], and let me know how you'd like that mapped to opacity in the range [0,1].

**Comment by pixelzoom** [comment]
3/3/2022 design meeting

We played around with making changes to the code, and concluded that the algorithm is more involved.  @kathy-phet will take a stab at it.   @ariel-phet and I may take a stab at it next week.

**Comment by veillette** [comment]
As Kathy pointed out, a magnification of 0.5 for the image should appear more intense than the object.

The issue we faced is that the intensity of light is connected to the transparency. At that point in time, the object had a transparency of 1  so we could not tackle images that would appear brighter than the object itself. Instead we simply address the case where the image where magnified >1, for which case we would make the image more transparent. 

If the starting point for the transparency of the object is 0.75, then there is a bit of room to make the image more intense.

**Comment by veillette** [comment]
Here is a first stab at addressing the issue

```

transparencyOfObject= 0.75 

// Affect of optic diameter
diameterFactor = diameter / maxDiameter;

magnificationFactor = Math.min( 1, Math.abs( transparencyOfObject / magnification ) );

// product of the two factors
transparencyOfObject = diameterFactor * magnificationFactor;

```

This is just one potential approach, and it has it own limitations.

In essence, an image of the same size as the object would have the same transparency, 
however, the transparency could be upscaled by for magnification between 1 and 3/4.
Magnifications that are smaller than 3/4, then the transparency is maxed out to 1.

**Comment by kathy-phet** [comment]
@pixelzoom - Here is my recommendation to try - that also accounts for object distance from lens: 

referenceObjectDistance = 160
objectDistanceFactor = referenceObjectDistance/objectDistance

diameterFactor = diameter/maxDiameter

magnificationFactor = Math.abs( 1/magnification)

transparencyOfImage = min[1 , 0.75*objectDistanceFactor*diameterFactor*magnificationFactor]

It could get very dim for an object very far away from the lens. We may need/want to impose a minimum transparency of something, or not. I suggest evaluating this. 

@veillette - The above is intended to also capture the fact that when the object is further away from the lens, less light is captured by the lens. This isn't exact, because its not using the light spreading in the 3 dimensions, but qualitatively for the relationships I think it captures everything. And it maxes transparency at 1, and it makes the sort of "default" scenario with max lens diameter as a transparency of 0.75.

**Comment by pixelzoom** [comment]
@kathy-phet (and anyone else who wants to try it) your algorithm is implemented in master, and ready for review.

Some notes:
* You skipped over light intensity and went directly to opacity. The model computes compute light intenstity in the range [0,1]. The view then maps light intensity to opacity (what you're calling transparencyOfImage).
* You used a range of [0,0.75] for opacity.  That's what we've been using for framed images, but not for arrow images.  The ranges can be set via query parameters: `?framedImageOpacityRange=0,0.75` and `?arrowImageOpacityRange=0,0.6`.
* You can use Studio to inspect the values for `lightIntensityProperty` (model) and `opacityProperty` (view).

Here's the TypeScript code to derive `lightIntensityProperty`, as it appears in OpticalImage.ts:

```js
// Affect of object's distance from the optic.
const referenceObjectDistance = 160;
const objectDistanceFactor = referenceObjectDistance / opticObjectXDistance;

// Affect of optic diameter
const diameterFactor = diameter / diameterRange.max;

// Affect of magnification.
const magnificationFactor = Math.abs( 1 / magnification );

// Multiply factors, constrained to [0,1].
return GOConstants.INTENSITY_RANGE.constrainValue( objectDistanceFactor * diameterFactor * magnificationFactor );
```

The value of `lightIntensityProperty` is then linearly mapped to `framedImageOpacityRange` in FramedImageNode.ts (for framed images), and to `arrowImageOpacityRange` in ArrowImageNode.ts (for arrow images).

**Comment by pixelzoom** [comment]
@kathy-phet your algorithm is implemented in master, and ready for review. @arouinfar and @ariel-phet, please have a look and provide feedback.

Some notes:
* You skipped over light intensity and went directly to opacity. The model computes compute light intenstity in the range [0,1]. The view then maps light intensity to opacity (what you're calling transparencyOfImage).
* You used a range of [0,0.75] for opacity.  That's what we've been using for framed images, but not for arrow images.  The ranges can be set via query parameters: `?framedImageOpacityRange=0,0.75` and `?arrowImageOpacityRange=0,0.6`.
* You can use Studio to inspect the values for `lightIntensityProperty` (model) and `opacityProperty` (view).

Here's the TypeScript code to derive `lightIntensityProperty`, as it appears in OpticalImage.ts:

```js
// Affect of object's distance from the optic.
const referenceObjectDistance = 160;
const objectDistanceFactor = referenceObjectDistance / opticObjectXDistance;

// Affect of optic diameter
const diameterFactor = diameter / diameterRange.max;

// Affect of magnification.
const magnificationFactor = Math.abs( 1 / magnification );

// Multiply factors, constrained to [0,1].
return GOConstants.INTENSITY_RANGE.constrainValue( objectDistanceFactor * diameterFactor * magnificationFactor );
```

The value of `lightIntensityProperty` is then linearly mapped to `framedImageOpacityRange` in FramedImageNode.ts (for framed images), and to `arrowImageOpacityRange` in ArrowImageNode.ts (for arrow images).

**Comment by kathy-phet** [comment]
Hi Chris, The model I had suggested resulted in the opacity of the largest diameter lens and the framed picture at the 0.75 opacity that folks liked, but allowed the opacity to go up to 1, because of the min [1 , 0.75*model factors] where 0.75 * model factors could result in >1 values. From what I am seeing here, the opacity cannot get to 1 now because of the range that is set. I wanted to ensure that the default was 0.75 opacity which the model I had did accomplish without saying that 0.75 was to top of the range. 

So I don't know quite how to adjust your implementation to get to the opacity behavior I had in the implementation I suggested.

**Comment by pixelzoom** [comment]
If you want the opacity of the framed images to go to 1, run with `? framedImageOpacityRange=0,1`.

**Comment by kathy-phet** [comment]
Chris, I am not seeing either of these properties in studio
You can use Studio to inspect the values for lightIntensityProperty (model) and opacityProperty (view).

**Comment by pixelzoom** [comment]
How are you running Studio? Did you have "All" or "Featured" selected? (You must have "All" selected -- nothing is featured yet.) Any errors in the console? If you're using phettest, have you pulled all repositories? ... 

Dev versions:
https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.33/phet-io/
https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.33/phet/geometric-optics_en_phet.html

Instances of `lightIntensityProperty` are in the model, one for each optical image. For example:

<img width="779" alt="screenshot_1594" src="https://user-images.githubusercontent.com/3046552/157172776-9e280b0c-1621-4315-81d4-d9f1c40d33b2.png">
 
Instances of `opacityProperty` are in the view, one for each optical image. For example:

<img width="776" alt="screenshot_1595" src="https://user-images.githubusercontent.com/3046552/157172968-44f21a90-fbe2-45bc-bc4c-0f58a6d1f071.png">

**Comment by kathy-phet** [comment]
I was running on Master, and looking under this iD, using "All Elements". 
geometricOptics.lensScreen.view.scenes.framedObjectSceneNode.framedImageNode

I also tried to use the search and it didn't pull up anything with opacity in it. 

I'm not sure why I cannot see what you are seeing on Master. phettest?

**Comment by pixelzoom** [comment]
https://bayes.colorado.edu/dev/phettest/phettest/ currently shows many common-code repos out of dates, and geometric-optics out of date. See screenshot below.   If phettest's repos are stale, then you're not going to see changes that were checked in later. 

After pressing the "Pull All" button at the top of phettest, and waiting for all of the repos to change to "up-to-date", running Geometric Optics in Studio works as I described, and searching for `lightIntensityProperty` and `opactityProperty` works.

<img width="906" alt="screenshot_1596" src="https://user-images.githubusercontent.com/3046552/157175119-f425abb1-56cc-4c4a-abb4-e8691d80ef7d.png">

**Comment by kathy-phet** [comment]
I see in dev.33, but not on Master/phettest. 

Going with dev.33, I want the opacity to go 0-1, but in the way that I had modeled it to get 0.75 transparency where it needed to be. 

Can you do 
lightIntensity = min[1 , 0.75 * objectDistanceFactor * diameterFactor * magnificationFactor]

Then map that linearly to opacity of [0-1]. That should give the behavior for images that I am looking for.

**Comment by pixelzoom** [comment]
> So I don't know quite how to adjust your implementation to get to the opacity behavior I had in the implementation I suggested.

If running with `?framedImageOpacityRange=0,1` doesn't give you want you want, then please revise your algorithm to include light intensity (in the range [0,1]) that is then mapped to opacity.   I can't simply skip the light intensity step.

**Comment by pixelzoom** [comment]
Revised derivation of `lightIntensityProperty` in OpticalImage.ts:

```js
// Affect of object's distance from the optic.
const referenceObjectDistance = 160;
const objectDistanceFactor = referenceObjectDistance / opticObjectXDistance;

// Affect of optic diameter
const diameterFactor = diameter / diameterRange.max;

// Affect of magnification.
const magnificationFactor = Math.abs( 1 / magnification );

// Multiply factors, constrained to [0,1].
return GOConstants.INTENSITY_RANGE.constrainValue( 0.75 * objectDistanceFactor * diameterFactor * magnificationFactor );
```

I've revised the query parameter ranges for opacity, so that both ranges at [0,1].  This will cause `lightIntensityProperty` and `opacityProperty` values to be identical. 

`framedImageOpacityRange=0,1`
`arrowImageOpacityRange=0,1`

To my eye, the arrow images are too opaque.  So I question whether your 0.75 multiplier is appropriate for arrows.  There is one `lightIntensityProperty` algorithm for ALL optical images.  There are separate `opacityProperty` algorithms for framed vs arrow images.  This is why we were attempting to address your 0.75 multiplier in the computation of `opacityProperty`, rather than in `intensityProperty`.

**Comment by kathy-phet** [comment]
This is looking great for the images to me, with framedImageOpacityRange=0,1 and this intensity calculation above. And it does a very nice job of being less opaque when the object is further from the lens and capturing less light. It gets dim, but you can still see it in the cases I tried. I didn't admittedly exercise the most dim cases - we might want to put minimum on it, possibly. 

To return to the dimmer arrow node, the previous look then set ?arrowImageOpacityRange=0,0.8, and you get ~0.6 for the nominal test case setting of the full diameter lens. 

However, @arouinfar @ariel-phet @pixelzoom, this discussion around the arrow made me wonder, if we aren't doing the proper scaling of the arrow head and such, should we be doing the intensity scaling of the arrow at all? Or should it just be a constant, but lighter opacity arrow? I can go either way here, this just seems a bit of a conflicting behavior to have intensity scale but not size. 

If we do intensity scaling, This setting works well I think. 
https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.34/phet/geometric-optics_en_phet.html?arrowImageOpacityRange=0,0.8

**Comment by kathy-phet** [comment]
@pixelzoom - Also, the reason putting the 0.75 factor in the opacity directly didn't meet the effect I was after, was because I wanted to utliize the entire dynamic range of 0-1, so that compact images where the light is focused to a small area needed to look very opaque/bright, thus needed to go higher than 0.75.

**Comment by pixelzoom** [comment]
Yes, I understand why you put the 0.75 factor where you did.  I was trying to make what you gave me work with the current implementation, so that we still had the flexibility and tunability   provided by decoupling intensity and opacity.  I'm glad that where we ended up achieved the look you were going for. I'm not happy with where the code is at now.

Going forward... Since we now have opacity ranges of [0,1], there's no difference between intenisty and opacity values.  So how about if we ditch the query parameters for opacity, and rename `lightIntensityProperty` to `opacityProperty`. Then change the 0.75 multiplier in your algorithm to a parameter, use 0.75 for framed objects, use a different value for arrows. 

And let's see what @arouinfar and @ariel-phet say about arrows.  The look that we had previously fined-tuned (for both framed images and arrow images) was designed to communicate that they were images, not confuse them with objects (especially when object and image are on the same side of the optic), and hopefully prevent the user from trying to interact with them.

**Comment by arouinfar** [comment]
The opacity of the images in the framed objects scene looks great to me, and I think it's a huge improvement.

> If we do intensity scaling for the arrowNode. This setting works well I think.
https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.34/phet/geometric-optics_en_phet.html?arrowImageOpacityRange=0,0.8

Thanks @kathy-phet. Assuming we treat arrows like framed objects, I don't think we can fine-tune their opacity until we decide on the final colors, so I had originally combined the arrow opacity issue under the umbrella issue for colors, #319.

> However, @arouinfar @ariel-phet @pixelzoom, this discussion around the arrow made me wonder, if we aren't doing the proper scaling of the arrow head and such, should we be doing the intensity scaling of the arrow at all? Or should it just be a constant, but lighter opacity arrow? I can go either way here, this just seems a bit of a conflicting behavior to have intensity scale but not size.

I would be fine with either of these proposals, since the arrow scene is more of a model. The arrow opacity, in general, is tricky because we are effectively mixing a single color with white, so it is difficult to recreate the same effect we see with the framed objects.

> This is what we call a "magic number".

I'll let @kathy-phet fill in the actual blanks, but my guess is that this value was chosen because it is twice the default focal length, so an object placed there would have a magnification of 1.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar @kathy-phet for the Arrow representation, I would be fine it were just a constant opacity with no scaling. It seemed at the time easier to just have it behave (in an opacity sense) like other objects. However, having the arrow image being a constant opacity seems also likely an easy and clear implementation, so I would be fine with that and it would probably be a clearer, simpler representation in that regard.

**Comment by kathy-phet** [comment]
> Going forward... Since we now have opacity ranges of [0,1], there's no difference between intenisty and opacity values. So how about if we ditch the query parameters for opacity, and rename lightIntensityProperty to opacityProperty (replacing the current opacityProperty). Then change the 0.75 multiplier in your algorithm to a parameter, use 0.75 for framed objects, use a different value for arrows.

This sounds OK to me, and would give the same behavior I think.

**Comment by pixelzoom** [comment]
Now that we have everyone's opinion on what to do for the arrows... Who is making the decision on what we're going to do?

**Comment by kathy-phet** [comment]
@arouinfar - Your call on what to do with arrow. If forced to choose, I lean towards fixed opacity for the arrows to stick with the model framing of this representation, but happy to support either direction.

**Comment by arouinfar** [comment]
@pixelzoom let's go with a fixed opacity for the arrow objects. I'm a bit concerned that it will be tricky to find an opacity that works for both arrow images. Could we instead add arrowImage1 and arrowImage2 to the color profile? That way, we could tune them independently to achieve the same perceived saturation.

**Comment by pixelzoom** [comment]
>  let's go with a fixed opacity for the arrow objects.

Will do.

>  Could we instead add arrowImage1 and arrowImage2 to the color profile?  That way, we could tune them independently to achieve the same perceived saturation.

They are already in the color profile. See `arrow1Fill` and `arrow2Fill`.

**Comment by pixelzoom** [comment]
When I asked about `referenceObjectDistance = 160`, @kathy-phet said:

> You can turn that value into 2*F_default, if you want to not use a value.

f is the distance from the optic. F is a point.  F.x is not the same as f unless the optic is at x = 0.  That said...

Is using 2f really safe to do?  In https://github.com/phetsims/geometric-optics/issues/311, we're changing the ranges (and perhaps defaults) for all controls. I'll be surprised if 2f = 160 

Also note that 2f is not 160 by default in the Mirror screen, it's 180. @kathy-phet have you tested this in the Mirror screen?

**Comment by kathy-phet** [comment]
This doesn't have to be an exact science on the "default distance". It's just a comfortable distance from the lens, and nominally where the image/object sizes are the same. I have not tested it on the mirror screen, so will need to look at that. 

If you are OK with hard coding a value then 160 is fine, if things change 10% here or there in distances, I think it will remain fine. 

I did think the Optic was by default at 0, that that was the definition in the code. Which is why I suggested 2f.

**Comment by pixelzoom** [comment]
I decided to stick with the magic numbers so that the behavior won't inadvertently change.  I documented those magic numbers in the code like this:

```js
        // Kathy Perkins described this constant as "a comfortable distance from the lens, and nominally where the
        // image/object sizes are the same".
        const referenceObjectDistance = 160; // cm
...
        // Prior to rewriting this algorithm, the opacity range was [0,0.75]. Kathy Perkins described this constant
        // like this: "it was easiest to find ... where you would get a value of 1, and then just multiply that
        // by 0.75 to create the visual effect we wanted".
        const multiplier = 0.75;
```

@arouinfar @kathy-phet ready for review in master, or use the dev links below. Remember to test in both Lens and Mirror screen!

https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.35/phet/geometric-optics_en_phet.html
https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.35/phet-io/

**Comment by arouinfar** [comment]
@pixelzoom I think the behavior in master looks great for both screens. Given @kathy-phet's earlier review comments, I think this is safe to close, but please feel free to re-open if you feel otherwise @kathy-phet.
