### ISSUE TITLE
The opticalAxisNode is not pickable in studio autoselect

### ISSUE THREAD

**Issue by samreid** [phetsims/geometric-optics#351]
From https://github.com/phetsims/studio/issues/243#issuecomment-1055735992 @arouinfar said:

> I ran into a situation where I was unable to select an element in Studio in geometric-optics. I tried selecting the Optical Axis (the dashed horizontal line running across the center of the play area) with ctrl and opt/alt, both with no success. There is a Node in the view, but its only child is a linked property to the corresponding model element, see `geometricOptics.lensScreen.view.scenes.framedObjectSceneNode.opticalAxisNode`. 

@zepumph and I investigated and found that Line stroke are not pickable by default, and `strokePickable: true` must be added to make the stroke pickable.

**Comment by pixelzoom** [comment]
I get that `strokePickable: false` might be a nice default for Paintable.  But for Line, which is nothing but a stroke...?   Seems like a scenery issue would have been more appropriate here.

But I'll go ahead and add `strokePickable: true`.

**Comment by pixelzoom** [comment]
@arouinfar please review in master.

**Comment by zepumph** [comment]
Great idea! I created https://github.com/phetsims/scenery/issues/1370 after speaking with @jonathanolson about it.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, the optical axis is now selectable in Studio, closing.
