### ISSUE TITLE
Set `positionProperty` of draggable elements to `phetioHighFrequency: true`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#352]
For #237 

Moving freely-draggable elements around the play area generates a ton of events in the data stream. Let's mark the corresponding `positionProperty` as high-frequency.

- [ ] `model.rulers.*Ruler.positionProperty`
- [ ] `model.scenes.*ObjectScene.*Object*.positionProperty` (all objects in all scenes)
- [ ] `model.scenes.framedObjectScene.secondPoint.positionProperty`
- [ ] `lensScreen.model.scenes.lightObjectScene.projectionScreen.positionProperty`

**Comment by pixelzoom** [comment]
@arouinfar and I discussed this.  

`model.rulers.*Ruler.positionProperty` might have been worthwhile, since nothing depends on it.

But `positionProperty` related to the object (and second point) is a dependency of so many other things, that making `positionProperty` high-frequency has almost no impacty on the data stream. 

@arouinfar also found
https://github.com/phetsims/phet-io/issues/1629#issuecomment-608002410 (best practices for phetioHighFrequency in the data stream), where our conclusions were:

> * For now we will no longer design phetioHighFrequency events
> * We aren't going back and removing it just yet, we will wait for a better alternative to be implemented.
> * the priority of creating a wrapper side data stream customization is lower than other current priorities. (unless it is needed for some of that work. i.e. natural selection will be more data than we have encountered yet!).

So our conclusion is that we should not be adding `phetioHighFrequency: true` to anything, since that's an obsolete way of doing things. 

@zepumph @samreid thoughts?

**Comment by zepumph** [comment]
>since that's an obsolete way of doing things.

If we are deciding that we no longer care about HFE, then I'm all for it, just as long as designers are up for still navigating the data stream to look at what is coming out and making sure that it is acceptable. HFE used to be a nice way to wean out certain events (once acceptably designed) and to look at the user-driven event stream. 

Even though https://github.com/phetsims/phet-io/issues/1734 is still in our future, it was my understanding that designers should be putting some level of spot checking into the data stream.

**Comment by pixelzoom** [comment]
> ... just as long as designers are up for still navigating the data stream to look at what is coming out and making sure that it is acceptable.

I don't think that's a reasonable expectation.  It's pretty much impossible inspect (much less validate) the data stream without writing code to do so.  It also seems problematic that there's no automated testing of the data stream.

**Comment by arouinfar** [comment]
Individual events are reasonably human-readable, but the data stream as a whole isn't, nor is it meant to be. A single click can generate dozens of events. For example, pressing the decrement button on a NumberControl can create 55 events. It's not 55 (or even 10) instances of a single thing, though. Changing the index of refraction will change the focal length of the lens and therefore the position of the focal points, the position and magnification of the images in all scenes, the angle of the guide arms, etc. It seems like the appropriate events are triggered, but it's really not something I can reasonably analyze while I interact with the sim.

**Comment by pixelzoom** [comment]
Since we're no longer using `phetioHighFrequency: true`, there's nothing to do here. So closing.
