### ISSUE TITLE
Polish labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#353]
3/3/2022 design meeting, for https://github.com/phetsims/geometric-optics/issues/328

* Label focal points as simply “F”
* Split the longer labels into 2 lines:  “Real Image”, “Virtual Image”, “Concave Lens”, “Convex Lens”, etc.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master
