### ISSUE TITLE
Add position markers to the toolbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#355]
3/3/2022 design meeting, for https://github.com/phetsims/geometric-optics/issues/328

Add 2 position markers to the toolbox.  Freely draggable.  See center-and-spread for example "look", maybe something like "pins" used in map apps.

**Comment by pixelzoom** [comment]
Notes to self:

* RulersToolbox will need to be renamed
* GOMarker can be similar to GORuler
* GOMarkerNode can use similar drag handlers to GORulerNode
* Alt input
* Hotkeys?

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master.

Notes:
* Markers look like upside-down Map markers, and use a FontAwesome icon. If you want something else, please provide artwork.
* Default colors for the markers are `positionMarker1Fill` and `positionMarker2Fill`, both default to 'black'. Let me know if you want to change these.
* Markers are to the right of rulers in the toolbox. Let me know if you'd prefer a different order.
* For all forms of dragging (mouse, touch, keyboard) a marker is returned to the toolbox if any part of its bounding rectangle overlaps the toolbox.
* Markers are in the same layer as rulers. If you click on a marker or ruler, it moves to the front.
* Like rulers, markers have a `visibleProperty`. When false, the marker is in the toolbox; when true the marker is outside the toolbox.  See phetioDocumentation, similar to rulers.
* Like rulers, markers can be dragged anywhere in the visible bounds of the screen. This includes on top of controls, etc.  If a marker is in the way of something, move the marker.
* Like rulers, markers do not move when the zoom level is changed. So if (for example) you put your marker at the position of the optical object, then zoom out, your marker is no longer at the position of the optical object.
* iO elements exist for markers. Look under `model.tools` and `view.tools`.  The view elements are linked to the model elements. 
* Keyboard dragging uses the same steps that are used for rulers, optical objects, and the projection screen.
* The only hotkey supported by markers is Escape, which returns the marker to the toolbox.

Questions:
*  Do you want additional hotkeys to move to specific points, like rulers? It will be a significant piece of work, starting with specification of the points.

**Comment by pixelzoom** [comment]
Some polishing of the markers with @ariel-phet in the above commit, including:

* slight vertical elongation
* use the ruler fill color, with black stroke (fills and strokes are in color profile)
* use `opacity: 0.85`
* make toolbox icons slight smaller (0.8 scaling) than the actual markers

@arouinfar let me know if you find any of those changes to be disagreeable.

We also discussed a couple of things from https://github.com/phetsims/geometric-optics/issues/355#issuecomment-1062321541:

> Like rulers, markers do not move when the zoom level is changed. So if (for example) you put your marker at the position of the optical object, then zoom out, your marker is no longer at the position of the optical object.

At first, @ariel-phet thought that the markers should maintain their model position, and _should_ move when zooming. I explained the problems with zoom in, when we need to move things (including markers) into the visible bounds. The markers do no know that they are on "significant" points, so keeping them on significant points in that case is currently not possible. (It is possible with several costly changes and a couple of UX compromises - ask if you're interested.) Since we double that users will be changing zoom level while (for example) trying to put a framed object and light source at the same position (the use-case for markers that @kathy-phet mentioned), we concluded that it wasn't worth the bother, and markers should continue to behave like rulers. @arouinfar let me know whether you agree/disagree.

> Do you want additional hotkeys to move to specific points, like rulers? It will be a significant piece of work, starting with specification of the points.

@ariel-phet suggested (and I reluctantly agree) that markers should have a hotkey like J+R for rulers. That is, the hotkey should cycle through "interesting measurement points", from left to right. And unlike rulers, points to the right of the optic are interesting for markers.  

Since we don't really have room in the keyboard-help dialog for another section, @ariel-phet suggested using J+P (for Jump to Point) for both the rulers and markers, and titling the help section "Ruler and Marker Controls".

@arouinfar I'm going to move forward with these hotkeys. Stop me asap if you disagree.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed on Zoom. Summary:

* Like the "look" of markers.
* Zoom behavior as described in the previous comment sounds correct.
* Hotkeys as described in previous comments sounds like the right thing to do, go for it.
* We changed traversal order, so that tools that are outside the toolbox are in the "play area".
* I'm going to revisit how `visibleProperty` is used for tools in the model, because it's overloaded/confusing.

**Comment by pixelzoom** [comment]
Summary of above commits:

* `visibleProperty` was replaced with `isInToolboxProperty` for tools
* icons in the toolbox are iO-instrumented, and the client can hide them via their `visibleProperty`
* major refactoring to move duplicated code into base classes: GOTool (model), GOToolNode (view), GOToolIcon (toolbox icon), GOToolDragHandler, and GOToolKeyboardDragHandler.  This was a big piece of work, took almost an entire (long) day.
* moved all tool-related code to common/model/tools/ and common/view/tools/.
* changed hotkey to J+P, and updated keyboard help
* moved support for "jump points" into GOToolNode base class (see `jumpPoints`)

Still to be done:
* add J+P support to position markers
* factor out some duplication of jump points in GOSceneNode subclasses
* add some additional interesting points to 'Light' scene for position markers (not sure what or how)

**Comment by pixelzoom** [comment]
J+P is implemented for position markers, and required major refactoring of the implementation for rulers.

I have to say that I'm concerned about how complicated this feature is to implement, explain, and test, because  I think it's symptomatic of the UX.  That said...

The set of jump points (in no particular order) is as follows:

All scenes:
* optic
* F left
* F right
* 2F left
* 2F right

Framed Object scene:
* framed object
* second point on framed object
* framed image
* second point on framed image

Arrows scene
* arrow object 1
* arrow object 2
* arrow image 1
* arrow image 2

Lights scene
* light 1
* light 2
* position where rays from light 1 converge
* position where rays from light 2 converge
* light spot 1
* light spot 2

Assuming the optic is at (0,0), the rules are as follows:

* For all tools, jump points are ignored if they are not visible, or if they are outside the drag bounds of the tool.

* For all tools, jump points are dynamically ordered (and visited) by ascending x-coordinate, (left to right) with wrap-around.

* Horizontal rulers ignore all points (x,y) with x > 0, and position themselves at (x,0).

* Vertical rulers look at the y coordinate of a point (x,y).  If y=0, the point is ignored. If y > 0, the ruler is placed at (x,0). so that we're measuring _up from_ the optical axis.  If y < 0, the ruler is placed at (x,y), so that we're measuring _up to_ the optical axis.

* Position markers simply jump to (x,y). 

@arouinfar position markers are now ready for a full review, including hotkeys.

**Comment by pixelzoom** [comment]
> Can you modify the logic so that the optic is a valid jump point? When the vertical ruler is at (0,0) the user can measure the radius of the optic.

The jump code has a list of points and whether they're visible. It doesn't know that one of those points is the optic.  This is going to be a big change, so I'm going to ask... Do you still want this?

**Comment by pixelzoom** [comment]
I'm also curious about why we'd want to measure the optic radius when the diamater is shown (and settable) in the control panel.

**Comment by arouinfar** [comment]
> The J+P jump code has a list of points and whether they're visible. It doesn't know that one of those points is the optic. This is going to be a big change, so I'm going to ask... Do you still want this?

It's not a hill I'm willing to die on, but it is a noticeable change from the previous implementation. 

> I'm also curious about why we'd want to measure the optic radius when the diamater is shown (and settable) in the control panel. The other values that we're measuring are not shown somewhere in the sim.

It'd purely be for verification purposes. It's not critically important and the default position of the ruler is (0,0), so I suppose that'll do. Closing.

**Comment by pixelzoom** [comment]
Vertical ruler now includes the optic position in its list of jump points. Back to @arouinfar for review.  Close if this looks OK.

**Comment by arouinfar** [comment]
Looks good, thanks!
