### ISSUE TITLE
Add 2F to Options dialog.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#356]
3/3/2022 design meeting, for https://github.com/phetsims/geometric-optics/issues/328

Add a control to enable the "2F" feature to the Options dialog.  Initial values set via the existing `enable2F` query parameter.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.  Screenshot below.

Notes:
* Let me know if you'd prefer a different label on the checkbox. Note that "Show 2F points" would be an incorrect label. The "2F Points" checkbox shows the points. This checkbox makes the 2F feature available.
* `geometricOptics.global.view.options.enable2FProperty` is the new iO Property.
* `enable2F` query parameter provides the initial value (false in GO, true GO:Basics)
* Changing `enable2FProperty` to false hides the "2F Points" checkbox and any 2F points that were visible.  Changing `enable2FProperty` to true shows the "2F Points" checkbox, and 2F points if the checkbox is checked.

![screenshot_342](https://user-images.githubusercontent.com/3046552/156679266-20740e16-5df0-45f5-9d8f-ca37c04da2b7.png)

**Comment by pixelzoom** [comment]
Maybe this is a better label for the checkbox? It's not exactly accurate, but perhaps more meaningful to users.

![screenshot_345](https://user-images.githubusercontent.com/3046552/156679671-06d45b3b-ffe3-48ab-85a5-c7184dd338e6.png)

**Comment by pixelzoom** [comment]
I pushed the change to the checkbox label, as shown in https://github.com/phetsims/geometric-optics/issues/356#issuecomment-1058725215.   

Note that this is a case where the iO element names do not match the checkbox label.  Checkbox is `enable2FCheckbox` because it's associated with the `enable2FProperty` Property, which is associated with the `?enable2F` query parameter.  This seems preferable to have to use names `show2FPointsCheckboxCheckbox`, `show2FPointsCheckboxProperty`, `?show2FPointsCheckbox`.

**Comment by arouinfar** [comment]
Thanks @pixelzoom this looks good in master. I prefer using the `enable2F` language in the tree for clarity, but I think you made a good call to use more natural language for the checkbox in the Options dialog. I know we generally try to coordinate the phetioID and the checkbox label, but there are good reasons not to do that here.
