### ISSUE TITLE
New instrumented Properties for object and image

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#360]
FYI... As part of https://github.com/phetsims/geometric-optics/issues/354, 2 additional DerivedProperties were instrumented.

`opticObjectXDistanceProperty` is included for every optical object.  It's what we've been calling D<sub>o</sub> or d<sub>o</sub> in other issues.  It looks like this in Studio:

<img width="677" alt="screenshot_1593" src="https://user-images.githubusercontent.com/3046552/157161300-3ac9574a-9ba8-4b1f-9b21-da8d986a09e6.png">

`opticImageXDistanceProperty` is included for every optical image.  It's what we've been calling D<sub>i</sub> or d<sub>i</sub> in other issues.  It looks like this in Studio:

<img width="675" alt="screenshot_1592" src="https://user-images.githubusercontent.com/3046552/157161410-76b22646-a8cb-4486-b86b-26bb85670c53.png">

@arouinfar please review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. These look great in Studio and should be convenient for clients, closing.
