### ISSUE TITLE
Dragging the object through the focal point is jerky.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#361]
In https://github.com/phetsims/geometric-optics/issues/149#issuecomment-1057655181, @arouinfar noted:
>  The only issue I've noticed is that things can get pretty jerky when dragging the object through the focal point. When Do = f, Di = Infinity, so I imagine that's causing the stutter. It's noticeable even on my new MacBook Pro and pretty laggy on my phone.

**Comment by pixelzoom** [comment]
When the object passes through the focal point, the HTMLImageElement used to draw the image changes, and the image mask is regenerated.  Line 109 in FramedImageNode.ts is causing the performance problem:

```ts
    framedImage.htmlImageElementProperty.link( htmlImageElement => {
      imageNode.image = htmlImageElement;
109   maskNode.shape = imageNode.getSelfShape();
      updateScaleAndPosition();
    } );
```

Since all images are the same size, I should be able to load 1 mask, and reuse it by transforming it.

**Comment by pixelzoom** [comment]
I took this approach:
> (3) Ditch getSelfShape altogether, create my own trapezoid mask, 

The downside is that the mask will need to be modified if the PNG files are changed. I've documented that well, and it seems like a fine compromise for the performance improvement.

@arouinfar ready for review, OK to close.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I'm no longer seeing the jerky behavior in master.

> The downside is that the mask will need to be modified if the PNG files are changed. I've documented that well, and it seems like a fine compromise for the performance improvement.

This seems like a reasonable trade-off to me.

**Comment by pixelzoom** [comment]
A couple of additional notes for posterity:

* The sim is now much more responsive on my Mid-2012 Mac Pro.  With `getSelfShape`, dragging framed objects was noticeably laggy.  I expect this improvement to apply to other performance-challenged machines, like Chromebooks.

* The new mask Shape is composed of 6 line segments. The mask generated by `getSelfShape` looks like it contained possibly hundreds of segments. See for example screenshot below from 1.1.0-dev.30 with `?debugMask`.   In addition to the cost of `getSelfShape`, I suspect that a simpler Shape also results in improved performance.

![screenshot_347](https://user-images.githubusercontent.com/3046552/158035527-5febcbd5-4f8a-4cf5-9e84-03ab3674d685.png)
