### ISSUE TITLE
Change dragLockedProperty to objectDragModeProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#364]
While working on https://github.com/phetsims/geometric-optics/issues/333, I found myself getting confused about the value of `dragLockedProperty`.  This Property has bugged me for awhile, and I think it could be improved - a boolean value isn't quite cutting it.  So I'm going to change it to `objectDragModeProperty`, with values `'free'` and `'horizontal'`.    This will make the code easier to maintain (as I can attest :) and should improve the presentation in Studio.

**Comment by pixelzoom** [comment]
@arouinfar this is ready for review.  Screenshot below shows what it looks like in Studio.  I like this quite a bit more, and it made the code so much more understandable.   

Also... The tandem name of the toggle button changed to `objectDragModeToggleButton`.

<img width="875" alt="screenshot_1599" src="https://user-images.githubusercontent.com/3046552/157781107-17fe26b2-08c3-4177-b7ac-0b6f720f3257.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. This change definitely adds more clarity, I like it! Closing.
