### ISSUE TITLE
Empty regions of toolbox should not be focusable

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#368]
Observed in master and dev.36 (latest) but not dev.30 (arbitrarily chosen older version).

Steps to reproduce:
1. Remove any tool from the toolbox (using mouse or keyboard, doesn't matter)
2. Tab until focus reaches the toolbox.
3. Notice that empty regions of the toolbox receive focus. 
![image](https://user-images.githubusercontent.com/8419308/157993522-ec03cfbc-c473-4a5f-9f34-4f54d8e8ab48.png)

**Comment by pixelzoom** [comment]
Thanks for noticing this @arouinfar.  Fixed in the above commits, ready for review.  This regression occurred in https://github.com/phetsims/geometric-optics/issues/355, when we decided to make the `visibleProperty` of toolbox icons settable by iO clients.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom.
