### ISSUE TITLE
Create a new geometric-optics-screenshot.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#369]
Create a new geometric-optics-screenshot.png.  The current one is for the prototype and looks completely different.

**Comment by pixelzoom** [comment]
This will also be needed if we publish a new prototype version.

**Comment by pixelzoom** [comment]
@arouinfar can you please update geometric-optics-screenshot.png for the new prototype version?

**Comment by arouinfar** [comment]
I've updated the main screenshot and added the alternates to master and 1.1. Unless there are significant visual changes, this set of screenshots should also be fine for publication in https://github.com/phetsims/geometric-optics/issues/278.
