### ISSUE TITLE
Should size of scene buttons remain consistent across lens and mirror screens?

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#37]
Currently, scene buttons are not the same size for both lens and mirror screens. The button size adjusts based on the icon size.
![image](https://user-images.githubusercontent.com/29347882/122079794-fa301b80-cdba-11eb-9801-02b9cc46370e.png)
![image](https://user-images.githubusercontent.com/29347882/122079832-05834700-cdbb-11eb-8d12-a6993a74395f.png)

**Comment by sarchang** [comment]
Design meeting: make them all square

**Comment by sarchang** [comment]
Size of buttons stay constant.

**Comment by veillette** [comment]
Good use of spacer. Closing
