### ISSUE TITLE
Zoom buttons are floating at the top of the window

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#370]
@pixelzoom the zoom buttons are currently aligned to the top of the browser window instead of the control panel. You can currently find them floating near the ComboBox:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/8419308/158243077-c2eba613-e168-4496-8c6c-3a7712e6eaf6.png">

**Comment by pixelzoom** [comment]
Thanks. This snuck in during https://github.com/phetsims/geometric-optics/issues/365, when I was dealing with dynamic layout of the control panel in response to iO changes.  

Fixed in the above commit, closing.
