### ISSUE TITLE
Remove temporary KeyboardDragListenerOptions

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/geometric-optics#371]
KeyboardDragListener has been converted to TypeScript so it should be possible now to replace the KeyboardDragListenerOptions  in GOCommonOptions.ts with the actual options exported by KeyboardDragListener.ts.

**Comment by jessegreenberg** [comment]
For the temporary options I had to update the `drag` option to match the type required by KeyboardDragListener in https://github.com/phetsims/geometric-optics/commit/c973a49bc089e5b67595a5b0eb8bc3c2bbc61a3d, just wanted to point out this commit.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg!  I removed my temporary type definition, and I'm now using 
KeyboardDragListenerOptions from scenery imports.js.
