### ISSUE TITLE
Reduce lineWidth for rays?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#385]
Now that we've settled on ray colors in #319 ....

I like the new colors (black & red) for rays.  But they feel really "heavy" with `lineWidth=2`. Examples:

<img width="1144" alt="screenshot_1615" src="https://user-images.githubusercontent.com/3046552/158907965-33242c18-eb75-4738-8d45-cf8d6e8d813d.png">
<img width="1144" alt="screenshot_1614" src="https://user-images.githubusercontent.com/3046552/158907994-87d181a0-37a7-406b-97bb-3b561c9c6860.png">

Should we consider reducing to `lineWidth=1`? Same examples:

<img width="1138" alt="screenshot_1616" src="https://user-images.githubusercontent.com/3046552/158908079-58f03016-4d4f-4a9c-b982-3fccc7f73e20.png">

<img width="1144" alt="screenshot_1613" src="https://user-images.githubusercontent.com/3046552/158908102-2ae66fd3-2a8b-4f6a-802e-39be271e40ce.png">

**Comment by pixelzoom** [comment]
Or we could split the difference, and use `lineWidth=1.5`.  

I think that `lineWidth=2` was chose when the background was dark, since a thicker line is typically needed on dark backrounds.  But with the white background, it feels too heavy.  And I think that switching from gray & green for the ray colors has accentuated that.

**Comment by pixelzoom** [comment]
Here's `lineWidth=1.5`.  This still feels a little heavy on a computer screen, but might project better?

<img width="1139" alt="screenshot_1618" src="https://user-images.githubusercontent.com/3046552/158908459-8a2e7c44-91a5-4481-b564-cd5f8d321f22.png">

<img width="1143" alt="screenshot_1619" src="https://user-images.githubusercontent.com/3046552/158908485-9fd4bd36-e77a-4b59-bffc-0df476dc35b7.png">

**Comment by pixelzoom** [comment]
I've added query parameter `raysLineWidth` (default 2) so you can experiement in master.

**Comment by pixelzoom** [comment]
Different lineWidth for real vs virtual rays is also trivial, if that's desirable. The dash virtual rays could definitely use a larger lineWidth without feeling too heavy, and might project better. Happy to add separate query parameters if you want to explore that.

**Comment by pixelzoom** [comment]
In the above commit, I replaced `raysLineWidth` with `realRaysLineWidth` (default 2) and `virtualRaysLineWidth` (default 2).

I like 
`?realRaysLineWidth=1&virtualRaysLineWidth=1.5`
or maybe even 
`?realRaysLineWidth=1&virtualRaysLineWidth=2`

**Comment by arouinfar** [comment]
@pixelzoom thanks for creating these query parameters! I'm not sure if I would take the real rays all the way down to 1. It looks great on a computer screen, but it's probably a bit too thin for classroom projection. My vote would be for `realRaysLineWidth=1.5&virtualRaysLineWidth=2`. It lightens things up a bit, but should still look good at the back of the classroom.

**Comment by pixelzoom** [comment]
`realRaysLineWidth=1.5&virtualRaysLineWidth=2` looks great to me, done in the above commit. Closing.
