### ISSUE TITLE
Image missing when 'None' is selected with light propagation off

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#390]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/787
Switching to the 'None' option for Rays with light propagation turned off, will not produce an image (either Real or Virtual) when light propagation is turned on. 

**Steps to reproduce**
1. On either screen, press the Light Propagation toggle button to turn it off
2. Switch Rays to 'None'
3. Press the Light Propagation toggle button--no image appears
4. Turn Light Propagation off and on again--image appears

This only happens with the 'None' option.

**Visuals**

https://user-images.githubusercontent.com/87318828/159270901-e0f55a96-1851-4089-b98f-9a99e2367c2a.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.1 2022-03-18 20:41:59 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36
Language: en-US
Window: 1369x678
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Reproduced with real and virtual images in master and 1.1.0-rc.1.

**Comment by pixelzoom** [comment]
Light scene is also messed up:

1. Go to Lens screen
2. Choose 'Light' fron the combo box
3. Set Light Propagation toggle button to off
4. Set Rays to "None"
5.  Set Light Propagation toggle button to on.  Light spot should be visible on projection screen, but is not.
6. Set Light Propagation toggle button to off. Light spot should NOT be visible on projection screen, but is. 
7. Continue to toggle button on/off.  Light spot remains visible regardless of toggle button setting.

**Comment by pixelzoom** [comment]
For posterity... I want to once again note how the complexity of implementing this button (and our repeated inability to get it right) is directly related to the fact that this button has too many responsibilities, and high potential to get the user into confusing situations.  I understand the goal, but the design and excution here has been nothing but problems.

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet @kathy-phet For posterity... I want to once again note how the complexity of implementing this button (and our repeated inability to get it right) is directly related to the fact that this button has too many responsibilities, and high potential to get the user into confusing situations. I understand the goal, but the design and excution here has been nothing but problems.

**Comment by pixelzoom** [comment]
This is duplicated in ArrowImageNode and FramedImageNode, and should probably be moved to OpticalImageNode:

```js
      // OpticalImageNodeOptions
      visibleProperty: new DerivedProperty(
        [ virtualImageVisibleProperty, arrowImage.opticalImageTypeProperty, lightPropagationEnabledProperty, arrowImage.visibleProperty, objectVisibleProperty ],
        ( virtualImageVisible: boolean, opticalImageType: OpticalImageType, lightPropagationEnabled: boolean, framedImageVisible: boolean, objectVisible: boolean ) =>
          ( virtualImageVisible || opticalImageType === 'real' ) && lightPropagationEnabled && framedImageVisible && objectVisible, {
          tandem: providedOptions.tandem.createTandem( 'visibleProperty' ),
          phetioType: DerivedProperty.DerivedPropertyIO( BooleanIO )
        } )
```

**Comment by pixelzoom** [comment]
The commits above hide the light spots when light propagation is disabled.

There's another problem. 

1. Go to Lens screen
2. Select the Light scene
3.  Set Rays to "None"
4. Press and release toggle button to turn light propagation off. Note that it takes a long time for the toggle button to pop back up, and a long time for the light spots to disappear.  

This delay does not occur with other Ray choices, only with "None".  And it does not occur in the other scenes.

**Comment by Nancy-Salpepi** [comment]
Looks good in master.

**Comment by pixelzoom** [comment]
To verify in 1.1.0-rc.2:

* Check the scenario that reported in https://github.com/phetsims/geometric-optics/issues/390#issue-1175399517
* Check the scenario described in https://github.com/phetsims/geometric-optics/issues/390#issuecomment-1074091244.  


If it looks OK, close this issue.

**Comment by KatieWoe** [comment]
Looks good. Will reopen if something comes up.
