### ISSUE TITLE
Migrate translated strings with updated string keys

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#393]
This issue blocks the publication of 1.1.0, but not additional RC versions on this branch. When the 1.1.0 version is ready to be deployed, @pixelzoom should notify @jbphet so he can manually update babel files.

Rosetta now has support for translating prototypes, and the Geometric Optics prototype has already been translated into 13 locales. @pixelzoom pointed out that many string keys have changed, which is problematic. A sub-set of the website and rosetta teams met to discuss strategy around prototype sim translations and here are the relevant takeaways:
* While we should try to avoid changing string keys, it is sometimes necessary. This will be discussed more at dev meeting.
* Re-translating strings is a burden to translators, so we should try to preserve their previous work.
* If a string key changes, but the string in the sim didn't change, we can manually update the babel files so translators do not lose previous work.
* ON will notify translators that there are new strings to translate when the sim is republished. We will also add messaging to prototype sims in rosetta so translators are forewarned, but this is being tracked elsewhere.

I compared the strings and string keys in the currently published prototype and the 1.1 branch. Here's a [spreadsheet](https://docs.google.com/spreadsheets/d/11-Z-Y0_pkVwJOY7R-uPdSujwPQsqyhEZa14QZKpO8dM/edit#gid=909441108) with a side-by-side comparison of the new and old string keys. I went with a spreadsheet instead of a markdown table since it can easily be exported to a .csv. Empty cells in the "Old string key" column indicate that the string should not be migrated (because it's new or has changed significantly).

**Comment by pixelzoom** [comment]
>  @pixelzoom should notify @jbphet so he can manually update babel files.

I hope that @jbphet is not actually going to do this update manually.  Given @arouinfar's spreadsheet, it should be straightforward to write something that handles the migration of old strings to the new keys.

**Comment by pixelzoom** [comment]
Barring any unforeseen problems with RC spot-check, I’m anticipating that Geometric Optics will be ready to publish around this time next week (4/7?). It will be a public version, not a prototype version. 

I alerted @jbphet via Slack, and he said:
>  I'll put the script together tomorrow, and you can keep me posted next week.  We should make the changes right before you publish to minimize the chances of a translation coming in during the changes to the keys.  We can even put Rosetta in "maintenance mode" if we want to be extra careful.

**Comment by jbphet** [comment]
I have the script working, so I think I'm ready for my part.

@arouinfar - I noticed some inconsistencies in the format of the spreadsheet.  My script is handling it okay, but I wanted to make sure that it wasn't indicative of something that was missed.  I noticed that in some cases there is nothing in the 2nd column, in some cases the values in the first and second columns match, and sometimes the values in the two columns are different.  The script is only paying attention to the cases where there are two different values in the columns.  Can you verify that this is correct?

@pixelzoom: Below is the list of changed strings identified by the script from the spreadsheet as it was at around 3 pm MT today.  Does this look correct?

```
The following string key renames will be attempted:
  radiusOfCurvature ---> radiusOfCurvaturePositive
  none ---> radioButton.none
  marginal ---> radioButton.marginal
  principal ---> radioButton.principal
  many ---> radioButton.many
  focalPoints ---> checkbox.focalPoints
  labels ---> checkbox.labels
  virtualImage ---> checkbox.virtualImage
  secondPoint ---> checkbox.secondPoint
  guides ---> checkbox.guides
  convexLens ---> label.convexLens
  concaveLens ---> label.concaveLens
  convexMirror ---> label.convexMirror
  concaveMirror ---> label.concaveMirror
  object ---> label.object
  realImage ---> label.realImage
  projectorScreen ---> label.projectionScreen
  opticalAxis ---> label.opticalAxis
```

**Comment by arouinfar** [comment]
>The script is only paying attention to the cases where there are two different values in the columns, and I'm assuming that the ones that are blank in the 2nd column are new, and the ones that are the same are unchanged. Can you verify that this is correct?

Yes, that's correct @jbphet.

**Comment by pixelzoom** [comment]
@jbphet FYI, Geometric Optics 1.1 is ready for production deploy, as soon as the build sever is fixed (see https://github.com/phetsims/perennial/issues/266).

**Comment by jbphet** [comment]
I've run the script for changing the keys and commit the changes to the babel repo.  Here is a list of the translation files that were changed:

```
  ./babel/geometric-optics/geometric-optics-strings_da.json
  ./babel/geometric-optics/geometric-optics-strings_de.json
  ./babel/geometric-optics/geometric-optics-strings_el.json
  ./babel/geometric-optics/geometric-optics-strings_es.json
  ./babel/geometric-optics/geometric-optics-strings_eu.json
  ./babel/geometric-optics/geometric-optics-strings_fa.json
  ./babel/geometric-optics/geometric-optics-strings_it.json
  ./babel/geometric-optics/geometric-optics-strings_iw.json
  ./babel/geometric-optics/geometric-optics-strings_pl.json
  ./babel/geometric-optics/geometric-optics-strings_pt_BR.json
  ./babel/geometric-optics/geometric-optics-strings_sk.json
  ./babel/geometric-optics/geometric-optics-strings_sr.json
  ./babel/geometric-optics/geometric-optics-strings_th.json
  ./babel/geometric-optics/geometric-optics-strings_tr.json
  ./babel/geometric-optics/geometric-optics-strings_zh_TW.json
```

Once the publication is complete, we should check several of these sims and make sure that they changes strings appear to be translated.  @pixelzoom and I did some local testing of this before triggering the build, so he should know what to look for.

Once the publication is complete, we should check the translations.

**Comment by pixelzoom** [comment]
I spot-checked a few translations after 1.1 publication, and they looked good. Strings had been migrated as expected.  

@jbphet asked about where his scripts should live, etc I'm not sure, and will defer to him.  I am concerned that this may become a standard part of publication.  If that's the case, we can't be doing this manually. 

@jbphet I'm comfortable closing this when you are.

**Comment by jbphet** [comment]
I added the script that was used for this - named `rename-string-keys.js` - to the rosetta repo, and I brought several others along for the ride.  I think we're good here.  Closing.
