### ISSUE TITLE
Should pointing tools stay in place when zooming with buttons?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#398]
**Device**
iPad
**OS**
iPadOS 15.4
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/787
If you place one of the pointing tools in the play area then use the zoom buttons to zoom in or out, the pointing tool stays in the same place on the screen, but not in regards to the items in the sim. So if you put it on the image then zoomed out, it will be to the side of the image. Fixing this may not be feasible, but if it's an easy fix it seems like it would be more useful for the tool to move with the objects of the sim.
**Visuals**

https://user-images.githubusercontent.com/41024075/159527815-06a3fe42-0832-409a-8a19-7ecedbb11e11.MOV

**Comment by pixelzoom** [comment]
Yes, the position markers are supposed to behave like the rulers - they do not move when zoom changes.

Discussion about this occured in https://github.com/phetsims/geometric-optics/issues/355#issuecomment-1063226660:
> At first, @ariel-phet thought that the markers should maintain their model position, and should move when zooming. I explained the problems with zoom in, when we need to move things (including markers) into the visible bounds. The markers do no know that they are on "significant" points, so keeping them on significant points in that case is currently not possible. (It is possible with several costly changes and a couple of UX compromises - ask if you're interested.) Since we double that users will be changing zoom level while (for example) trying to put a framed object and light source at the same position (the use-case for markers that @kathy-phet mentioned), we concluded that it wasn't worth the bother, and markers should continue to behave like rulers. @arouinfar let me know whether you agree/disagree.

And https://github.com/phetsims/geometric-optics/issues/355#issuecomment-1063264701:
> @arouinfar and I discussed on Zoom. Summary:
> ...
> Zoom behavior as described in the previous comment sounds correct.
> ...

So my recommendation is to close this issue.  Assigning to @arouinfar in case she wants to revisit, otherwise close.

**Comment by arouinfar** [comment]
Thanks for the suggestion @KatieWoe and thanks for summarizing @pixelzoom. When zooming out, we can maintain the model coordinates while keeping the markers on the screen. However, this isn't always the case when zooming in, which can lead to strange UX. Treating the markers like the rulers is a more consistent experience, though I concede it may not always be the most convenient. 

My preference is to leave the behavior as-is.
