### ISSUE TITLE
Combo box and overlap of menu. 

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#40]
![image](https://user-images.githubusercontent.com/7633344/122436889-30120300-cf67-11eb-9d98-9b07d40755e8.png)

Although we expect the menu of the combo box to be long, it should not be underneath the lens, or mirror, but above it.

**Comment by veillette** [comment]
Upon reflection, there are least three possible options:
- the combox box and list is beneath the optic
- the combox bos is beneath (z-order) the optic but the list is visible, the list is above the optic
-  the optic is alway beneath the combox box and the list.

The button in common code is currently tagged as private, so it is not possible to change the z-order dynamically.

**Comment by veillette** [comment]
Options #2 
![image](https://user-images.githubusercontent.com/7633344/122789579-73c97d00-d285-11eb-9d18-54c6898b28d6.png)
![image](https://user-images.githubusercontent.com/7633344/122789635-8348c600-d285-11eb-83ff-712560507506.png)

Options #3 
![image](https://user-images.githubusercontent.com/7633344/122789843-bbe89f80-d285-11eb-84a5-1c67fdd92180.png)

**Comment by veillette** [comment]
Currently the simulation is using option 1

**Comment by sarchang** [comment]
optic should be beneath both list and combo box

**Comment by sarchang** [comment]
moved playAreaNode to be beneath zoom buttons, combo box, and toolbox nodes in z-order so that the object, optic, image, and optical axis are all underneath the zoom buttons, combo box, and toolbox.

**Comment by veillette** [comment]
Combobox is fixed. I'm not sure about the behavior of the other components, but we can raise an issue if the design team thinks it is problematic.
