### ISSUE TITLE
Consider increasing vertical range of "second point" slightly

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#401]
Found as part of testing https://github.com/phetsims/qa/issues/787 (Windows 11, Chrome)

It would be nice if the second point extended slightly further vertically downward in its range. On the penguin and the pencil it would be nice if the second point reached to the full extent of each of these objects. Currently it feels a little unsymmetric if you move the second point all the way to the end of its range it doesn't quite reach the end of the eraser, or the penguins feet. I think this could just be adjust by eye, and it looks like the change would accommodate both cases. Not a showstopper by any means, more a polish/suggestion.

![pencil](https://user-images.githubusercontent.com/4051174/159582358-63afd8d0-dce5-4ea1-bfc8-1e07948585a8.png)
![penguin](https://user-images.githubusercontent.com/4051174/159582361-239dc165-823a-49ae-b2ab-b6f9bfacef4b.png)

**Comment by pixelzoom** [comment]
This is also something that could probably wait until after the 1.1 prototype release.  On the other hand, there were enough things in 1.1.0-rc.1 that another RC will be needed, and we could patch this in.

**Comment by pixelzoom** [comment]
I went for it, pushed to master and 1.1 in the above commits. 

This was indeed adjusted by eye.  And because the extrema for the pencil and penguin are not exactly the same location, it's a compromise.   If it's not acceptable, please describe what you'd like changed. If it's acceptable, please mark this issue as "fixed:ready-for-review" and I'll schedule it for the next 1.1 RC.

**Comment by ariel-phet** [comment]
@pixelzoom that visual "compromise" looks great to me! Marking the issue as requested

**Comment by pixelzoom** [comment]
@arouinfar if this looks OK to you, feel free to unassign yourself.

**Comment by arouinfar** [comment]
Thanks for the suggestion @ariel-phet. @pixelzoom master looks good to me!

**Comment by KatieWoe** [comment]
Looks good. If something comes up, will reopen.
