### ISSUE TITLE
Make optic label read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#411]
Discovered in https://github.com/phetsims/geometric-optics-basics/issues/3 but applies to both flavors.

Currently, `view.scenes.*.labels.opticLabel.textNode.textProperty` is editable. However, the model will override it when the optic type is changed, and rightly so. Let's make these `phetioReadOnly: true` @pixelzoom.

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master.

**Comment by arouinfar** [comment]
Thanks, looks good!
