### ISSUE TITLE
IOR of mirrors should be read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#412]
Noticed in #362 and applies to both flavors.

`mirrorScreen.model.mirror.focalLengthModels.indirectFocalLengthModel.indexOfRefractionProperty` should be `phetioReadOnly: true`. Otherwise, a client could completely break the mirror model which assumes IOR=2.

This has no impact on the 1.1 release, so I'll mark as on-hold.

**Comment by pixelzoom** [comment]
I thought of a quick-and-dirty way to make `indexOfRefractionProperty` conditionally read-only, if the length of its range is zero:

```js
    this.indexOfRefractionProperty = new NumberProperty( options.indexOfRefractionRange.defaultValue, {
      // units: unitless
      range: options.indexOfRefractionRange,
      tandem: options.tandem.createTandem( 'indexOfRefractionProperty' ),
      phetioReadOnly: ( options.indexOfRefractionRange.getLength() === 0 )
    } );
```

Again, this is not something that should be handled on a sim-specific basis.  But I'll reluctantly add it in this case, if you'd like.

**Comment by arouinfar** [comment]
@pixelzoom thanks for the explanations, both long and short. I agree, we don't need to do anything here. I am not featuring anything related to the IOR of mirrors because it's really just a trick that allows us to share code between the lens and mirror models.

> For the Mirror screen, indexOfRefractionProperty is already effectively read-only because it's range is limited to a single value (2). 

I think it's clear enough to anyone looking at it in Studio. I'll admit that I didn't really pay much attention or try to edit the value. When traversing through the tree and checking off featured, I noticed the data input controls, realized it wasn't read-only, and then made a note to open an issue. Next time I see something like this, I'll double-check the range. :)
