### ISSUE TITLE
Jumping tools become stuck at identical points of interest.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#413]
For https://github.com/phetsims/qa/issues/787, and related to https://github.com/phetsims/geometric-optics/issues/395.

There is a general problem with tools. If 2 points of interest have the same coordinates, the tool will become stuck at that position.  I suspect that it's stuck looping between the 2 identical points.  To reproduce:

1. Go to Lens screen
2. Check "Second Point" checkbox
3. Use keyboard to pop horizontal ruler out of the toolbox
4. Press 'J' key until ruler moves to framed object position. Continue to press 'J' and note that the ruler is stuck at this position.

I verified this another way by changing LensModel.ts to start with both arrows at identical positions:

```js
      arrowObject1Position: new Vector2( -160, 60 ),
-     arrowObject2Position: new Vector2( -125, 30 ),
+     arrowObject2Position: new Vector2( -160, 60 ),
```

... and then observing that the horizontal ruler gets stuck at the arrow object position.

I think the solution to this is to filter the points of interest so that the points (Vector2) are unique.

**Comment by KatieWoe** [comment]
Looks good in rc.2. However, I wasn't able to reproduce this in rc.1, so I'm a bit less confident.
