### ISSUE TITLE
PhET-iO instrumentation for Options dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#415]
@arouinfar and I ran across this while working on something else. The Options dialog has not been reviewed for PhET-iO design. Change requests:

Uninstrument these children of `optionsDialogCapsule.optionsDialog.content`:

- [x] visibleProperty
- [x] add2FPointsCheckbox.labelNode.visibleProperty
- [x] focalLengthModelControl.labelNode.visibleProperty
- [x] focalLengthModelControl.radioButtonGroup.visibleProperty
- [x] focalLengthModelControl.radioButtonGroup.directRadioButton.visibleProperty
- [x] focalLengthModelControl.radioButtonGroup.indirectRadioButton.visibleProperty 

Instrument these children of `optionsDialogCapsule.optionsDialog.content`:

- [x] focalLengthModelControl.radioButtonGroup.directRadioButton.labelText.textProperty
- [x] focalLengthModelControl.radioButtonGroup.indirectRadioButton.labelText.textProperty

**Comment by pixelzoom** [comment]
On hold until 1.1 prototype is published. I don't want to introduce master changes that make it more difficult to cherry-pick.

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom this all looks good in master, closing.
