### ISSUE TITLE
Radius of Curvature control should be hidden for flat mirrors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#424]
When switching to the flat mirror, the ROC NumberControl does not disappear as it should. This bug exists in the published 1.1 version of the sim, and appears to have been introduced sometime between dev.30 and dev.31. However, the bug is not present in master for GO or GOB. @pixelzoom I recommend publishing a MR as this a fairly serious bug.

![Screenshot Capture - 2022-04-08 - 15-54-22](https://user-images.githubusercontent.com/8419308/162537127-f805d0ce-0606-4d21-b3d4-e1e3cc87426f.png)

**Comment by pixelzoom** [comment]
Wow... That's been broken since 3/2/2022, and was broken in every 1.1 RC.  

Nice to know it's fixed in master. But it's not going to be easy to patch in 1.1, because master has now diverged significantly.  I'll probably need to create a fix that's specific to 1.1, then run it through QA as an RC test.  That's not going to happen until Monday 4/8/22 at the earliest.

**Comment by pixelzoom** [comment]
Broken sometime between 2/22/2022 5:41PM and 3/2/2022 1:27PM MT.   And there are hundreds of commits between those 2 times :(

**Comment by pixelzoom** [comment]
Notes to self:
* This fix needs to be applied in OpticSubpanel.
* For `radiusOfCurvatureControl` add an option something like:

```js
visibleProperty: new DerivedProperty( [ optic.opticShapeProperty ],
  ( opticShape: OpticShape ) => ( opticShape !== 'flat' ) )
```

**Comment by pixelzoom** [comment]
@arouinfar please review these scenarios in master and 1.1.1-rc.1.  Verify that the control panel looks correct.

Focal Length control = 'direct':
- [ ] convex lens
- [ ] concave lens
- [ ] concave mirror
- [ ] convex mirror
- [ ] flat mirror

Focal Length control = 'indirect':
- [ ] convex lens
- [ ] concave lens
- [ ] concave mirror
- [ ] convex mirror
- [ ] flat mirror

Assign back to me, and I'll proceed with creating a QA issue for RC spot-check.

**Comment by arouinfar** [comment]
@pixelzoom looks good in master and the RC, back to you.

**Comment by pixelzoom** [comment]
To verify in 1.1.1-rc.1:

After starting the sim (Focal Lenght control defaults to "indirect") verify the look of the control panel as follows:

- [ ] both lens shapes:

<img width="850" alt="screenshot_1645" src="https://user-images.githubusercontent.com/3046552/162790908-8d2d61c6-81fb-47a8-98b1-3b7f2dba9c7f.png">

- [ ] for concave and convex mirror:

<img width="670" alt="screenshot_1646" src="https://user-images.githubusercontent.com/3046552/162791082-f641b803-c810-4529-a30e-fdb2b19e7ebb.png">

- [ ]  for flat mirror:

<img width="497" alt="screenshot_1647" src="https://user-images.githubusercontent.com/3046552/162791140-aaad4fb7-74a5-486a-9444-e8f450e99c10.png">

Next, go to PhET > Options, and switch "Focal Length control" to "direct".  Then verify the look of the control panel as follows:

- [ ] both lens shapes:

<img width="664" alt="screenshot_1648" src="https://user-images.githubusercontent.com/3046552/162791676-fed70167-ac60-4b45-ab98-e3d1cf1dd931.png">

- [ ] for concave and convex mirror:

<img width="664" alt="screenshot_1649" src="https://user-images.githubusercontent.com/3046552/162791658-1ab22453-ca9e-432e-8a63-010f720ef59b.png">

- [ ]  for flat mirror:

<img width="497" alt="screenshot_1647" src="https://user-images.githubusercontent.com/3046552/162791140-aaad4fb7-74a5-486a-9444-e8f450e99c10.png">

Please close this issue if verified.

**Comment by Nancy-Salpepi** [comment]
The controls present match what is shown in https://github.com/phetsims/geometric-optics/issues/424#issuecomment-1095303315. 

@pixelzoom I just wanted to make sure that the negative sign (-) is present at the correct times (because it is a bit different from what I am seeing in your comment).

When the Focal Length control is indirect:
For the concave lens/mirror, the Radius of Curvature has (-) written after it 
For the convex lens/mirror, the Radius of Curvature does not have the negative

When the Focal Length control is direct:
For the concave lens/mirror, the Focal Length control does not have the negative
For the convex lens/mirror, the Focal Length control has (-) written after it

**Comment by pixelzoom** [comment]
Thanks for confirming @Nancy-Salpepi.

For ROC and Focal Length, we decided to show (-) when the value is negative, but not show (+) for positive.  That was a bit of a compromise, documented in https://github.com/phetsims/geometric-optics/issues/345#issuecomment-1062088842 and in the code.

As for when the value is negative...

> When the Focal Length control is indirect:
For the concave lens/mirror, the Radius of Curvature has (-) written after it
For the convex lens/mirror, the Radius of Curvature does not have the negative

Correct.  For ROC, the sign is related to the shape of the optic: convex is positive, concave is negative.

> When the Focal Length control is direct:
For the concave lens/mirror, the Focal Length control does not have the negative
For the convex lens/mirror, the Focal Length control has (-) written after it

NOT correct.  For Focal Length, the sign is related to whether the optic is converging or diverging: converging is positive, diverging is negative.  A concave lens is diverging, and a **CONVEX** mirror is diverging.  

Please confirm that you're really seeing the incorrect behavior that you've described. I just checked 1.1.1-rc.1, and it looks correct to me.
