### ISSUE TITLE
CT: reentry detected (SliderTrack)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#428]
Reported for geometric-optics-basics, but would presumably be an issue in geometric-optics too.

```
geometric-optics-basics : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649933219440/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649933219440%22%2C%22timestamp%22%3A1649946409833%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: reentry detected, value=40, oldValue=120
Error: Assertion failed: reentry detected, value=40, oldValue=120
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649933219440/assert/js/assert.js:25:13)
at assert (Property.ts:273:14)
at _notifyListeners (Property.ts:208:13)
at set (SliderTrack.ts:103:20)
at handleTrackEvent (SliderTrack.ts:125:8)
at _dragListener (PressListener.ts:526:9)
at call (DragListener.ts:307:35)
at apply (PhetioAction.ts:123:16)
at execute (DragListener.ts:458:21)
at drag (PressListener.ts:895:13)
id: Bayes Chrome
Snapshot from 4/14/2022, 4:46:59 AM
```

I was unable to reproduce locally with:
`?phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false`
... and in case it was related to the Focal Length slider, which is difficult for CT to reach:
`?phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false&focalLengthControl=direct`

Unfortunately the stack trace isn't specific, so I can't tell which of the 4 SliderTrack-related Properties experienced the problem.  Since this test is `multitouch-fuzz`, my hypothesis is that there was a press in the slider track while the thumb was being dragged (or visa versa). 

This is not a blocking issue, because it wouldn't cause a problem in practice.

**Comment by pixelzoom** [comment]
> ... my hypothesis is that there was a press in the slider track while the thumb was being dragged (or visa versa).

I tested this hypothesis with a tethered iPad6, and could not reproduce the problem.

**Comment by KatieWoe** [comment]
Closing for https://github.com/phetsims/qa/issues/832. Feel free to reopen if this is in error.

**Comment by pixelzoom** [comment]
Please keep this open.

**Comment by pixelzoom** [comment]
It is not necessary to address this for #278, the 1.3 PhET-iO release.

**Comment by pixelzoom** [comment]
Closing. This seems to have been addressed elsewhere, and hasn't occurred in a long long time.
