### ISSUE TITLE
Reduce max magnitude of arrows to 80cm

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#429]
Tagging https://github.com/phetsims/qa/issues/799 since we should address in the 1.2 version.

It's currently possible to create situations with the Arrow where there are less than 2 rays intersecting the optic.

Steps to reproduce:
1. Either screen, Arrow scene, Many Rays
2. Maximize the height of the arrow and minimize the optic diameter
3. Minimize object distance 
![image](https://user-images.githubusercontent.com/8419308/163886298-a2dfcfc4-66fe-41ce-8b75-6a9895d015de.png) ![image](https://user-images.githubusercontent.com/8419308/163886421-a3f0d97e-c802-44dd-a663-9c94612f11cf.png)

We limit the height of the Light to 80 cm, so let's do the same with the Arrow.
![image](https://user-images.githubusercontent.com/8419308/163886651-0fd7ab5f-dc44-479b-b081-88d37d625674.png) ![image](https://user-images.githubusercontent.com/8419308/163886746-e1718734-c958-40c8-ad95-5440c2566866.png)

**Comment by pixelzoom** [comment]
> We limit the height of the Light to 80 cm, so let's do the same with the Arrow.

Actually, we're not limiting the height of any of the objects.  We're constraining objects to be fully inside the "scene bounds", which we've defined to extend +100cm and -100cm from the optical axis.    Run with `?debugSceneBounds` to display the scene bounds as a red rectangle, see screenshot below. 

For the framed object and lights, the entire object must inside the scene bounds.  The lights can be dragged ~80 cm above the optical axis, and ~58 cm below the optical axis, and this is a side-effect of their PNF files sizes, not any limit on where the light "position" can be location.  For the arrows, the tip must be inside the scene bounds, so it has a max length of 100 cm.

But yes, I can limit the magnitude of the Arrows to 80 cm.

**Comment by pixelzoom** [comment]
Done in the above commit.  Note that it's ideal for 2 rays to interect the optic, but not required for the ray tracer to work correctly.  And with "Many" rays, the original length (100 cm) may have been fine (even conceptually?) That said, over to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks for the explanation @pixelzoom and for making the change. The 100 cm length was convenient for calculating magnification, but I think it's preferable to limit the length so that two rays are guaranteed to intersect the optic. 

A length of 80 cm looks good in master, so I'll go ahead and close.
