### ISSUE TITLE
Pixel polish the look of control panel.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#43]

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/122792479-361a2380-d288-11eb-8d50-20e422f5707f.png)

**Comment by veillette** [comment]
List of things that need to be addressed:
- Add a title
- Center the vertical directions the number controls
- The size of the checkbox and the size of the font of the checkbox should match the design document.
- The control panels should be divided by vertical separators.
- Address issue #16 (supporting icons)

**Comment by sarchang** [comment]
done
