### ISSUE TITLE
Possible to have an arrow with no height

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#430]
**Device**
iPad
**OS**
iPadOS 15.4.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/798
If you drag the arrow to the middle line exactly, it doesn't jump to a taller value and seems to disappear. You can still grab it with touch by swiping over it. May be possible on other devices, but I've mostly seen it on iPad.
**Visuals**
![0AB86F52-9A53-441B-BBFD-62DEAF5FDF1B](https://user-images.githubusercontent.com/41024075/164056805-fa69bf75-7ccb-4491-828f-2c2711038080.png)

**Comment by pixelzoom** [comment]
Good find! 

 Here's the relevant code in ArrowObjectNode.ts that snaps the arrow to its minimum magnitude:

```js
    const end = ( sign: 1 | -1 ) => {
      const arrowLength = arrowObject.positionProperty.value.y - optic.positionProperty.value.y;
      if ( Math.abs( arrowLength ) < SNAP_TO_MIN_MAGNITUDE ) {
        const x = arrowObject.positionProperty.value.x;
        const y = sign * Math.sign( arrowLength ) * SNAP_TO_MIN_MAGNITUDE;
        arrowObject.positionProperty.value = new Vector2( x, y );
      }
    };
```

The problem line is:

```js
        const y = sign * Math.sign( arrowLength ) * SNAP_TO_MIN_MAGNITUDE;
```

When `arrowLength` is exactly zero, `Math.sign( 0 )` returns `0`, so `y = 0`.

Fixed in the above commit. @KatieWoe please verify in master. Be sure to test with both mouse, touch, and keyboard dragging.  If it looks OK, change label to "fixed-awaiting-deploy".

**Comment by pixelzoom** [comment]
> ...  I will note that in the original dev test I was never able to do this with a mouse, and it seemed almost impossible with keyboard nav, so confirming those is a bit harder.

Understood. I wanted you to test with mouse and keyboard to verify that the fix hadn't broken anything more general with drag handling of the arrows.

**Comment by KatieWoe** [comment]
Things looked ok from what I saw.

**Comment by KatieWoe** [comment]
Looks ok in dev.1
