### ISSUE TITLE
Layering of tools not recorded in State

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#431]
**Device**
Dell
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/799
If you pull multiple tools out of the tool box in State, the layering of those tools isn't necessarily the same in the bottom sim as in the top sim.
**Visuals**
<img width="519" alt="rulerlayering" src="https://user-images.githubusercontent.com/41024075/164311168-b202fa8e-70f8-4c70-9451-fec00fe6ca6c.png">

**Comment by pixelzoom** [comment]
All of the tools share the same parent, `toolsLayer` in GOScreenView.  When a drag starts on a GOToolNode, `moveToFront` is called.  See `start:` in GOToolDragListener and GOToolKeyboardDragListener. 

Looking at ComboBoxListItemNode, I added `phetioType: IndexedNodeIO` to GOToolNode, the base class for tools.  It had no effect, the z-ordering of the GOToolNode instances is not stateful.

@zepumph @samreid did I miss something? Or is this feature not working?

**Comment by pixelzoom** [comment]
Excellent, thanks @zepumph!

@KatieWoe please verify in master.  If it looks OK, change the label to "fixed-awaiting-deploy" and clear assignees.

**Comment by KatieWoe** [comment]
Looks good on master.

**Comment by KatieWoe** [comment]
This looks good in dev.1
