### ISSUE TITLE
Excess property checking for SimOptions/CreditsData

### ISSUE THREAD

**Issue by samreid** [phetsims/geometric-optics#433]
In https://github.com/phetsims/joist/issues/795 we added types for SimOptions and CreditsData which are working well in most sims, but Geometric Optics defines the credits in a different way and hence is not doing excess property checking.  Should we make any changes?

**Comment by pixelzoom** [comment]
@samreid You title for this issue says " SimOptions/CreditsData".  What is the problem with SimOptions in GO?  Looking at GOSim.ts, it seems like type-checking is being handled correctly.

**Comment by pixelzoom** [comment]
I went ahead and pushed type-checking for GOConstants.CREDITS.  @samreid please review after https://github.com/phetsims/joist/issues/805 is fixed.

**Comment by samreid** [comment]
It seems like `optionize` is just being used to type check the arguments in those examples, so it doesn't seem like a desirable usage of `optionize`.  Here are 2 other ways to type check things in a globals object.

(1) a local variable

```ts
const NUMBER_CONTROL_OPTIONS: NumberControlOptions = {
  layoutFunction: NumberControl.createLayoutFunction3( { ySpacing: 12 } ),
  titleNodeOptions: {
    font: CONTROL_FONT,
    maxWidth: 140
  },
  sliderOptions: {
    trackSize: new Dimension2( 140, 4 ),
    thumbSize: new Dimension2( 15, 30 ),
    thumbTouchAreaXDilation: 5,
    thumbTouchAreaYDilation: 5
  },
  numberDisplayOptions: {
    maxWidth: 70,
    textOptions: {
      font: CONTROL_FONT
    }
  }
};
```

(2) If we prefer a way to check that inline, then instead of using `optionize`, how about we create a function like `identity` that cane be used like so?

```ts
  NUMBER_CONTROL_OPTIONS: identity<NumberControlOptions>( {
    layoutFunction: NumberControl.createLayoutFunction3( { ySpacing: 12 } ),
    titleNodeOptions: {
      font: CONTROL_FONT,
      maxWidth: 140
    },
    sliderOptions: {
      trackSize: new Dimension2( 140, 4 ),
      thumbSize: new Dimension2( 15, 30 ),
      thumbTouchAreaXDilation: 5,
      thumbTouchAreaYDilation: 5
    },
    numberDisplayOptions: {
      maxWidth: 70,
      textOptions: {
        font: CONTROL_FONT
      }
    }
  } ),
```

**Comment by pixelzoom** [comment]
> It seems like optionize is just being used to type check the arguments in those examples, so it doesn't seem like a desirable usage of `optionize`. 

Why not? I don't see a problem with this.  It's doing what it's name says it does.  If you're saying that `optionize` shouldn't be used unless we're "merging" object literals, I disagree.

**Comment by samreid** [comment]
`optionize` is inappropriate here for the following reasons:

* You have to repeat type parameters.  `optionize<CreditsData, {}, CreditsData>()`.  Unnecessary repetition is generally undesirable.
* The documentation for `optionize` describes its type parameters like so:

> // ProvidedOptions = The type of this class's public API (type of the providedOptions parameter in the constructor)
> // SelfOptions = Options that are defined by "this" class. Anything optional in this block must have a default provided in "defaults"
> // ParentOptions = The public API for parent options, this will be exported by the parent class, like "NodeOptions"

The usage in GOConstants does not match this description.

* optionize.ts says `For up-to-date examples on how to use this file, see WILDER/WilderOptionsPatterns.ts`.  WilderOptionsPatterns.ts provides 14 example usages of how to use `optionize`.  All 14 occurrences demonstrate `optionize` in the context of a class constructor.  The usage in GOConstants does not match this description.

For completeness, brainstorming a 3rd alternative to optionize for consideration.  A classic old-fashioned IIFE:

```ts
  // Shared with geometric-optics-basics
  CREDITS: ( () => {
    const creditsData: CreditsData = {
      leadDesign: 'Amy Rouinfar, Michael Dubson',
      softwareDevelopment: 'Sarah Chang, Chris Malley (PixelZoom, Inc.), Martin Veillette',
      team: 'Chris Klusendorf, Diana L\u00f3pez Tavares, Ariel Paul, Kathy Perkins',
      qualityAssurance: 'Steele Dalton, Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
      graphicArts: 'Megan Lai'
    };
    return creditsData;
  } )(),
```

But I think my favorite so far is (2), described in https://github.com/phetsims/geometric-optics/issues/433#issuecomment-1108816286

**Comment by pixelzoom** [comment]
> You have to repeat type parameters. `optionize<CreditsData, {}, CreditsData>()`. Unnecessary repetition is generally undesirable.

How about making `optionize<CreditsData>` an alternative?

In the meantime... I'm using a pattern that works, but that you don't prefer.  Can we move the general discussion to a new issue, and closing this issue?

**Comment by pixelzoom** [comment]
Btw...  If you don't like `optionize<CreditsData, {}, CreditsData>`, it's used in many places throughout common code, especially for subcomponents.  It's the only way I've found to combine options, and it works well.  If the syntax were implied to `optionize<CreditsData>`, it would be perfect.  https://github.com/phetsims/phet-core/issues/114 has asked for the syntax to be reviewed.

> All 14 occurrences demonstrate optionize in the context of a class constructor. The usage in GOConstants does not match this description.

> WilderOptionsPatterns.ts provides 14 example usages of how to use optionize. All 14 occurrences demonstrate optionize in the context of a class constructor. The usage in GOConstants does not match this description.

So you're really that confident that WilderOptionsPattern.ts is complete?  It confident that its not.   And WilderOptionPattern only show examples in contructors, therefore optionize can only be used in constructors??.... Sounds like fallacious logic to me.

**Comment by samreid** [comment]
In https://github.com/phetsims/geometric-optics/issues/433#issuecomment-1108814774 I was asked to review the proposed implementation.  I performed the code review, explained why I believe the proposal to be suboptimal, and I described an alternative that is IMO superior.  You are not required to adopt the recommendation from the code review, you can close this issue and/or open a side issue if you wish.

**Comment by pixelzoom** [comment]
Noted in https://github.com/phetsims/phet-core/issues/114#issuecomment-1110436488. 

Closing.
