### ISSUE TITLE
Increase maxWidth of checkbox.add2FPointsCheckbox string

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#435]
In the Options dialog, the maxWidth of the 2F checkbox string is a bit shorter than the direct/indirect radio buttons. The Spanish translation is reaching the maxWidth and scaling down, and it's probably a common occurrence. Let's increase the maxWidth of the 2F checkbox to match the width of the radio buttons @pixelzoom.

![image](https://user-images.githubusercontent.com/8419308/166058329-d1d206ee-1c21-4ad9-b844-d69b1a85fefe.png)

**Comment by pixelzoom** [comment]
Addressed in the above commit.  We actually have lots of space, so I increase to `maxWidth: 500` for all control labels in the Options dialog.  See screenshots below. @arouinfar please review, close if this looks OK.

`?locale=es`:

<img width="634" alt="screenshot_1664" src="https://user-images.githubusercontent.com/3046552/166301379-68a485e8-1518-45de-8de7-9a89bdfc18e2.png">

`?stringTest=long`:

<img width="606" alt="screenshot_1663" src="https://user-images.githubusercontent.com/3046552/166301447-faa7ef5c-9df0-4121-a0bc-e6911c586675.png">

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom.
