### ISSUE TITLE
Add sims to phet-io-api-stable?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#438]
While reading about `phetioDesigned` for https://github.com/phetsims/phet-io/issues/1862, I noticed this comment in PhetioObject.ts:

>   // (b) the simulation is listed in perennial/data/phet-io-api-stable

Should geometric-optics and geometric-optics-basics be added to perennial/alias/phet-io-api-stable?   Or does that happen _after_ publication, as suggested in https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-technical-guide.md#publication-process?

**Comment by arouinfar** [comment]
I don't think this is a call I can make, I'll defer to the devs.

**Comment by zepumph** [comment]
>So why don't we want to add this sim to phet-io-api-stable as soon as we feel that the design is solid?

Yes, @samreid and I agree. with this. Love the idea! With a note that this should absolutely have happened by the time we get to RC.1.

**Comment by zepumph** [comment]
We added friction in https://github.com/phetsims/friction/issues/304

**Comment by zepumph** [comment]
I added phetioDesigned to all sims that are in phet-io api stable. I think this will be a more streamlined process from here, but I wouldn't want this to be more automatic since the flag `compareDesignedAPIChanges` doesn't necessarily mean that we want the whole sim designed.
