### ISSUE TITLE
Update QA credits for 1.3 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#439]
Update QA credits for 1.3 release #278.

Credits are shared with geometric-optics-basics via `GOConstants.CREDITS`.

**Comment by pixelzoom** [comment]
Per https://github.com/phetsims/geometric-optics-basics/issues/27#issuecomment-1295331012, the next release of GO will be 1.3.  Adjusting the title of this issue accordingly.

**Comment by pixelzoom** [comment]
Dev tests https://github.com/phetsims/qa/issues/938 and https://github.com/phetsims/qa/issues/939 have completed. Are there any updates to the QA credits?

**Comment by KatieWoe** [comment]
No new additions

**Comment by pixelzoom** [comment]
RC testing has been completed, and there were no additional requests for changes to QA credits. So closing this issue.
