### ISSUE TITLE
address size of buttons

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#44]
While tackling #43, I realize that the size of some buttons do not line up with the design document.
Two types of buttons to consider:

- [x] curve control buttons
- [x]  zoom in and out buttons

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/122929386-e47da180-d338-11eb-9cec-b91d67197df2.png)

**Comment by sarchang** [comment]
Passed in custom options for RectangularButton to make zoom buttons more square and margins smaller; there was a comment in RectangularButton.js that referenced https://github.com/phetsims/sun/issues/109#issue-35756026. Does PhET want all the zoom buttons standardized (dimensions, margins, color, etc)? CCK zoom buttons were the only yellow zoom buttons I could find on another simulation and I think they used the default dimensions.  But also I think these custom dimensions look a little better?

**Comment by veillette** [comment]
Well done, I'm not sure about the relative positioning of the buttons with respect to the control panel but we can see what the design team think about it.
