### ISSUE TITLE
Fold Options into Preferences

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#440]
Related to https://github.com/phetsims/joist/issues/837 ...   @kathy-phet asked me to focus on Geometric Optics for Preferences dialog integration.

- [x] Add Preferences dialog
- [x] Fold the Options dialog into the Preferences dialog
- [x] Rename things accordingly (GOOptionsNode, GOOptions, associated tandems)
- [ ] Revise the PhET-iO API, have it approved by @arouinfar 

Some of this has already been handled by @zepumph in https://github.com/phetsims/joist/issues/837.

**Comment by pixelzoom** [comment]
This is now ready for PhET-iO design review by @arouinfar.  Summary of changes:

* Properties related to Options were formerly under `global.view.options`.  They are now under `global.model.preferences`. This convention has not been discussed; I put them where they seemed to make the most sense. Also note that https://github.com/phetsims/joist/issues/840 plans to link Properties from `global.model.preferences` under `geometricOptics.general.model.preferencesModel`. That is common-code work that has not been done yet.

* `geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsMenuItem` no longer exists, because there is no Options menu item in the PhET menu.

* `geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule` no longer exists, because there is no Options dialog. Controls that appeared in the Options dialog were moved to the General tab of the Preferences dialog.

* Controls that were added to the General tab of the Preferences dialog now appear under `geometricOptics.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.generalPreferencesPanel.simPreferences` .  The `simPreferences` naming convention was chosen in https://github.com/phetsims/joist/issues/837#issuecomment-1224743329. Feel free to recommend a different convention, since that's what this review is about.

**Comment by arouinfar** [comment]
@pixelzoom thanks for summarizing the changes. I reviewed both sims, and the Preferences dialog and corresponding elements in the tree all look good. Housing the properties in `global.model.preferences` makes a lot of sense to me. Anything else to do here?

**Comment by pixelzoom** [comment]
All done, closing.
