### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#441]
... similar to what was done in https://github.com/phetsims/natural-selection/issues/319.

This also includes geometric-optics-basics.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics-basics/commit/633f7468efd220a6b715d9fac5fd3a2a81626a50, support for geometric-optics-basics was addressed -- it's just the title.  That sim has never been published, so has no translations and cannot be tested.

**Comment by pixelzoom** [comment]
This sim is up next in the list that @kathy-phet gave me, so increasing priority.

**Comment by pixelzoom** [comment]
Published [1.2.0-dev.2](https://phet-dev.colorado.edu/html/geometric-optics/1.2.0-dev.2) with brands=phet,phet-io as a baseline before doing this work.

**Comment by pixelzoom** [comment]
Looks like @zepumph converted some of the strings in this sim, but not others - very inconsistent. And I wasn't aware of this. See 83c13163.

**Comment by pixelzoom** [comment]
This is done.  The only bit that's not supporting dynamic strings in the "Slider Controls" section of the keyboard-help dialog, and that's being tracked in https://github.com/phetsims/scenery-phet/issues/769.

Ready for review by @arouinfar.

**Comment by pixelzoom** [comment]
I should note that this sim went a lot faster than Natural Selection https://github.com/phetsims/natural-selection/issues/319 because:
(1) It has fewer strings.
(2) The majority of the Text/RichText instances were already instrumented.
(3) It's in TypeScript, so I got some help from the type-checker, and imports worked in WebStorm.

**Comment by pixelzoom** [comment]
Geometric Optics and Natural Selection have roughly the same number of strings (56 vs 55 respectively).  But Geometic Optics went a lot faster than Natural Selection https://github.com/phetsims/natural-selection/issues/319 because:
(1) The majority of the Text/RichText instances were already instrumented.
(2) It's in TypeScript, so I got some help from the type-checker, and imports worked in WebStorm.

**Comment by arouinfar** [comment]
@pixelzoom I reviewed both sims in Studio, and the dynamic locales look great. I didn't encounter any layout issues when editing strings, and everything was nicely instrumented in the view with `labelText` and `titleText` which made the strings very easy to find/edit.
