### ISSUE TITLE
PhET-iO design review for 1.3 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#443]
#441 (add support for dynamic locale) will certainly result in many API changes, and there have been many common-code API changes and additions.  So this sim will require a full design review of the PhET-iO API.

This includes geometric-optics-basics.

**Comment by arouinfar** [comment]
I reviewed dynamic strings/layout in #441 and the preferences in #440.

Remaining work for both geometric-optics and geometric-optics-basics:
- [ ] Review `phetioFeatured` elements and update overrides as needed
    - see https://github.com/phetsims/phet-io-sim-specific/issues/11#issuecomment-1258969845 for instructions
- [ ] Create examples.md

**Comment by pixelzoom** [comment]
Per https://github.com/phetsims/geometric-optics-basics/issues/27#issuecomment-1295331012, the next release of GO will be 1.3.  Adjusting the title of this issue accordingly.

**Comment by arouinfar** [comment]
I created examples.md for both flavors in the above commits. I've provided QA with links to the examples docs in the testing issues. Nothing else left to do here, closing.
