### ISSUE TITLE
size and font of combo box

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#45]
The size and font of the combo box does not match the design document.

![image](https://user-images.githubusercontent.com/7633344/122929483-feb77f80-d338-11eb-9f53-58839e3164bd.png)

**Comment by sarchang** [comment]
@veillette artwork will change eventually, so I'm not too worried about the icons looking weird for now

**Comment by veillette** [comment]
Good work hoisting the font constant all the way to the constant file. It looks good.
