### ISSUE TITLE
Use common `MoveDraggableItemsKeyboardHelpSection`

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#451]
Today over in https://github.com/phetsims/my-solar-system/issues/93 and https://github.com/phetsims/scenery-phet/issues/801, we created and are using a common help section based on the one from Geometric Optics for dragging:

![image](https://user-images.githubusercontent.com/6856943/226061128-67d2a059-247f-441e-ad43-645c39a3d876.png)

Because this sim has been published, there is going to be some annoyance about translations for the previously GO-specific strings, but it would be best if we used the common code type in this sim. 

For next time we are working on this sim!

**Comment by pixelzoom** [comment]
scenery-phet's MoveDraggableItemsKeyboardHelpSection is now used in keyboard help.  I verified that it's identical to what it replaced. 

Closing.

**Comment by pixelzoom** [comment]
@zepumph said above:
> Because this sim has been published, there is going to be some annoyance about translations for the previously GO-specific strings, but it would be best if we used the common code type in this sim.

In the above commit, I removed unused strings.   Translators will need to translate the scenery-phet strings used by MoveDraggableItemsKeyboardHelpSection.
