### ISSUE TITLE
PhET-iO: Should we validate the positions of the objects or put bounds.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#454]
![image](https://user-images.githubusercontent.com/7633344/232868007-c6f5e5a0-f7ac-45a2-b360-e34660516970.png)

In PhET-IO we can set the position of the arrowObject such that it ends up on the right side of the lens. This is not possible do to by dragging the object and the simulation makes an assumption that the object is always to the left of the lens, so it lead to erroneous result.

While discussing  with @arouinfar, she mentioned that this has been noted in other sims, for instance, https://github.com/phetsims/beers-law-lab/issues/322 and https://github.com/phetsims/ph-scale/issues/270 . Often the solution has been to document it properly in `examles.md` such as 
https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/beers-law-lab/examples.md#fix-the-position-of-the-concentration-probe-to-the-bottom-of-the-beaker.

However, here the position of the framedObject seem to have some form of position validation that the arrowObject does not have so it me be worth investigating if it is possible to validate the position of the objects.

**Comment by pixelzoom** [comment]
This has come up numerous times in the context of other sims.  The solution has been to document in example.md.  I recommend we do the same here.   I see little value for the effort involved in trying to prevent the designer from putting things in "bad" positions.

**Comment by arouinfar** [comment]
I agree @pixelzoom, let's close.
