### ISSUE TITLE
Uninstrument all model `Guides` and `GuideNode` elements

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#455]
This came up during a discussion with @arouinfar.
From the 1054 Featured PhET-io Elements, 166 are related to "Guides".
If we consider all the 2610 PhET-io Elements, 235 are related to "Guides".
It is worth noting that in PhET-brand,  guides are not present, even in the preferences dialogue.
In PhET brand it is only possible to show the guides by turning on a checkbox related to guides. 

I would argue the sheer number of elements related to guide makes the guides less relevant, as it becomes even more difficult to merely attempt to turn the guides as the model elements pollute the namespace.

We propose to unistrument the model elements of the guides.

![image](https://user-images.githubusercontent.com/7633344/232894565-4623a1c6-ffd7-45ae-8dfb-dc39eb803a43.png)

**Comment by veillette** [comment]
On the view side, it is also not necessary to instrument the visibility property of the guides2Node.

The guides2Node visibility is a derived property that depends on the visibility of the second point.

![image](https://user-images.githubusercontent.com/7633344/232896317-26892717-4350-4235-a7a3-61222a50a4c2.png)

**Comment by pixelzoom** [comment]
The decision about flat mirrors is documented in Optic.ts:

```ts
// A flat mirror has infinite focal length and ROC. We approximate a flat mirror as a convex mirror with very-large
// focal length and ROC. Note that these very-large values will be visible in PhET-iO, and it was decided that is OK.
// See https://github.com/phetsims/geometric-optics/issues/227
const FLAT_MIRROR_FINITE_FOCAL_LENGTH = 100000; // positive, to make it convex
const FLAT_MIRROR_FINITE_RADIUS_OF_CURVATURE = 2 * FLAT_MIRROR_FINITE_FOCAL_LENGTH; // ROC = 2 * f
```

And our decision about exposing this in PhET-iO is documented in https://github.com/phetsims/geometric-optics/issues/227#issuecomment-949048738, from 10/21/2021 design meeting:

> * Bogus values (ROC, focal length) in PhET-iO are OK. They can be explained in PhET-iO client guide.

**Comment by pixelzoom** [comment]
When I did attempt to use physically accurate values, it got complicated, see https://github.com/phetsims/geometric-optics/issues/227#issuecomment-1047445905.  @arouinfar and I met, and enumerated the options for proceeding, see https://github.com/phetsims/geometric-optics/issues/227#issuecomment-1048133397.  @arouinfar concluded that the complication of a physically-accurate mode was not worth the worth it, and we should "hollywood", see https://github.com/phetsims/geometric-optics/issues/227#issuecomment-1054585375.

**Comment by veillette** [comment]
The above commit uninstrument  all guide and guides on the model side.

**Comment by veillette** [comment]
Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
Looks great.  I made one change in GuideNode.ts, see above commit - param `providedOptions` is no longer needed for the constructor. 

Over to @arouinfar for design review.  If this looks OK, you can close this issue.

**Comment by arouinfar** [comment]
Looks great, thanks @veillette!
