### ISSUE TITLE
Why does Studio use radio buttons for boolean `guidesVisibleProperty`?

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#456]
In studio, @arouinfar noted that guidesVisibleProperty appears with extra radio buttons

![image](https://user-images.githubusercontent.com/7633344/233076659-ef04649c-873a-46c4-a90a-92d9a66172a9.png)

In comparison,  the checkboxes in the sim do not have these extra radio buttons
![image](https://user-images.githubusercontent.com/7633344/233076517-f505cc03-15be-4857-86dc-4be52ff4c8d3.png)

**Comment by veillette** [comment]
The only valid values for Boolean property is true or false. Therefore we don't usually specify their valid values
```
    this.twoFPointsVisibleProperty = new BooleanProperty( false, {
      tandem: isExclusivelyFlatMirror ?
              Tandem.OPT_OUT :
              providedOptions.tandem.createTandem( 'twoFPointsVisibleProperty' )
    } );
```
However for `guidesVisibleProperty` there is a bit of defensive programming going on.

```
    this.guidesVisibleProperty = new BooleanProperty( false, {
      validValues: isMirror ? [ false ] : [ true, false ],
      tandem: isMirror ? Tandem.OPT_OUT : providedOptions.tandem.createTandem( 'guidesVisibleProperty' )
    } );
```

This bit says ``  validValues: isMirror ? [ false ] : [ true, false ]`` , if it is a Mirror they only valid value is false. This will prevent any client, or a future developer, from ever setting the visibility to true. If it is not a Mirror, say a Lens, then the valid values are true or false.

I think that studio always show the valid values, if provided, see for instance the `RaysTypeProperty` 
![image](https://user-images.githubusercontent.com/7633344/233079921-ccfe430c-14b5-406a-a609-02c39a61dbda.png)

**Comment by pixelzoom** [comment]
Self assigning. I think this can be addressed with something like the following change:

```ts
    this.guidesVisibleProperty = new BooleanProperty( false, {
-     validValues: isMirror ? [ false ] : [ true, false ],
-     tandem: isMirror ? Tandem.OPT_OUT : providedOptions.tandem.createTandem( 'guidesVisibleProperty' )
+     tandem: isMirror ? Tandem.OPT_OUT : providedOptions.tandem.createTandem( 'guidesVisibleProperty' ),
+     phetioReadOnly: isMirror
    } );
```

**Comment by pixelzoom** [comment]
Fixed in the above commit.  @arouinfar please review and close if OK.

`lensScreen.view.visibleProperties.guidesVisibleProperty` is instrumented and Studio shows a checkbox, see screenshot below. `mirrorScreen.view.visibleProperties.guidesVisibleProperty` is not instrumented,  because the guides feature is not supported for mirrors.

<img width="749" alt="screenshot_2497" src="https://user-images.githubusercontent.com/3046552/234941853-96279614-c4c7-4fc0-8ce0-d772080706e6.png">

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!
