### ISSUE TITLE
Primary vs secondary focal points, lenses vs mirrors, convex vs concave.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#457]
A user pointed out:
>The spherical mirror portion of the Geometrical Optics sim has a pretty serious visual bug: it draws two focal points for a spherical mirror rather than just one. This is a common mistake that our introductory students make when learning how to do ray tracing, and they invariably produce disfigured ray diagrams as they attempt in vain to make use of “both” mirror focal points (just as they did, successfully, for lenses).

**Comment by veillette** [comment]
I'd like to explain why the user is correct. In addition, I would like to say that it leads to other changes, such as the '2f' points for mirrors. In the context a mirror , there is only one '2f' point for a mirror, which is often referred by the letter 'C' as it is the actual center of the spherical mirror.

**Comment by veillette** [comment]
For some background, there are two focal points for a lens often referred as $f_1$ and $f_2$. In GO, on the lens screen, we don't distinguish between.

- $f_1$ is the position of object from which image formed by lens or a mirror at infinity.
- $f_2$ is the position of the image when the object is put at infinity.

**Comment by veillette** [comment]
![primary_vs secondary_concave lense](https://user-images.githubusercontent.com/7633344/233145367-c7b388a5-e6d3-4545-9c9c-fd348a55a95d.png)

![primary_vs secondary_convex lense](https://user-images.githubusercontent.com/7633344/233145322-b8fe8a9c-5f50-40fb-9d97-4029d6138827.png)

**Comment by veillette** [comment]
For a concave mirror $f_1$ is to the left of the mirror.
![image](https://user-images.githubusercontent.com/7633344/233146825-62d1f63a-6f8e-4dfa-919c-74034dd86610.png)
but $f_2$ is also to the left of the mirror.
![image](https://user-images.githubusercontent.com/7633344/233147072-e7e58a0d-23d9-4c42-adb0-dec2f323be90.png)

For a convex mirror, $f_2$ is to the right of the mirror
![image](https://user-images.githubusercontent.com/7633344/233147405-70b7d505-6c55-455a-baed-e1f79aa30760.png)
And although you demonstrate it $f_1$ is as the same location for $f_2$ for a convex mirror.

**Comment by veillette** [comment]
Here is a patch that addresses issues #457 and #458


<details><summary>Details</summary>
Subject: [PATCH] https://github.com/phetsims/geometric-optics/issues/458
---
Index: js/common/view/GOSceneNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GOSceneNode.ts b/js/common/view/GOSceneNode.ts
--- a/js/common/view/GOSceneNode.ts	(revision 890b205bb2f59a39ad5160f872a533b17a6f353d)
+++ b/js/common/view/GOSceneNode.ts	(date 1682022083935)
@@ -38,7 +38,7 @@
 
 export default abstract class GOSceneNode extends Node {
 
-  // 'Jump points' for the tools. These are interesting points, where you might want to place a tool.
+  // 'Jump points' for the tools. These are interesting points where you might want to place a tool.
   // When a tool has focus, 'J' hotkey will cycle through these points, in order of ascending x coordinate.
   public abstract readonly toolJumpPoints: ToolJumpPoint[];
 
@@ -57,10 +57,10 @@
   // Visibility of things that have labels, intended to be used to control the visibility of associated labels.
   public readonly opticNodeVisibleProperty: TReadOnlyProperty<boolean>;
   public readonly opticalAxisNodeVisibleProperty: TReadOnlyProperty<boolean>;
-  public readonly leftFocalPointNodeVisibleProperty: TReadOnlyProperty<boolean>;
-  public readonly rightFocalPointNodeVisibleProperty: TReadOnlyProperty<boolean>;
-  public readonly left2FPointNodeVisibleProperty: TReadOnlyProperty<boolean>;
-  public readonly right2FPointNodeVisibleProperty: TReadOnlyProperty<boolean>;
+  public readonly primaryFocalPointNodeVisibleProperty: TReadOnlyProperty<boolean>;
+  public readonly secondaryFocalPointNodeVisibleProperty?: TReadOnlyProperty<boolean>;
+  public readonly primary2FPointNodeVisibleProperty: TReadOnlyProperty<boolean>;
+  public readonly secondary2FPointNodeVisibleProperty?: TReadOnlyProperty<boolean>;
 
   /**
    * @param scene - model element
@@ -101,25 +101,38 @@
 
     // Focal Points (F)
     const focalPointsTandem = options.tandem.createTandem( 'focalPoints' );
-    const leftFocalPointNode = new FocalPointNode( scene.optic.leftFocalPointProperty, modelViewTransform, {
+    const primaryFocalPointNode = new FocalPointNode( scene.optic.primaryFocalPointProperty, modelViewTransform, {
       visibleProperty: visibleProperties.focalPointsVisibleProperty,
-      tandem: focalPointsTandem.createTandem( 'leftFocalPointNode' )
+      tandem: focalPointsTandem.createTandem( 'primaryFocalPointNode' )
     } );
-    const rightFocalPointNode = new FocalPointNode( scene.optic.rightFocalPointProperty, modelViewTransform, {
-      visibleProperty: visibleProperties.focalPointsVisibleProperty,
-      tandem: focalPointsTandem.createTandem( 'rightFocalPointNode' )
-    } );
+    const focalPointNodes = [ primaryFocalPointNode ];
+
+    let secondaryFocalPointNode: FocalPointNode | undefined;
+    if ( scene.optic.secondaryFocalPointProperty ) {
+      secondaryFocalPointNode = new FocalPointNode( scene.optic.secondaryFocalPointProperty, modelViewTransform, {
+        visibleProperty: visibleProperties.focalPointsVisibleProperty,
+        tandem: focalPointsTandem.createTandem( 'secondaryFocalPointNode' )
+      } );
+      focalPointNodes.push( secondaryFocalPointNode );
+    }
 
     // 2F Points
     const twoFPointTandem = options.tandem.createTandem( 'twoFPoints' );
-    const left2FPointNode = new TwoFPointNode( scene.optic.left2FProperty, modelViewTransform, {
+    const primary2FPointNode = new TwoFPointNode( scene.optic.primary2FProperty, modelViewTransform, {
       visibleProperty: visibleProperties.twoFPointsVisibleProperty,
-      tandem: twoFPointTandem.createTandem( 'left2FPointNode' )
+      tandem: twoFPointTandem.createTandem( 'primary2FPointNode' )
     } );
-    const right2FPointNode = new TwoFPointNode( scene.optic.right2FProperty, modelViewTransform, {
-      visibleProperty: visibleProperties.twoFPointsVisibleProperty,
-      tandem: twoFPointTandem.createTandem( 'right2FPointNode' )
-    } );
+
+    const twoFPointNodes = [ primary2FPointNode ];
+
+    let secondary2FPointNode: TwoFPointNode | undefined;
+    if ( scene.optic.secondary2FProperty ) {
+      secondary2FPointNode = new TwoFPointNode( scene.optic.secondary2FProperty, modelViewTransform, {
+        visibleProperty: visibleProperties.twoFPointsVisibleProperty,
+        tandem: twoFPointTandem.createTandem( 'secondary2FPointNode' )
+      } );
+      twoFPointNodes.push( secondary2FPointNode );
+    }
 
     // Layers for things that may be added by subclasses
     this.opticalAxisForegroundLayer = new Node();
@@ -165,10 +178,8 @@
       this.opticalAxisForegroundLayer,
       opticNode,
       opticVerticalAxisNode,
-      leftFocalPointNode,
-      rightFocalPointNode,
-      left2FPointNode,
-      right2FPointNode,
+      ...focalPointNodes,
+      ...twoFPointNodes,
       this.raysForegroundLayer,
       guidesLayer
     ];
@@ -179,20 +190,31 @@
 
     this.opticJumpPoints = [
       new ToolJumpPoint( scene.optic.positionProperty, opticNode.visibleProperty ),
-      new ToolJumpPoint( scene.optic.leftFocalPointProperty, leftFocalPointNode.visibleProperty ),
-      new ToolJumpPoint( scene.optic.rightFocalPointProperty, rightFocalPointNode.visibleProperty ),
-      new ToolJumpPoint( scene.optic.left2FProperty, left2FPointNode.visibleProperty ),
-      new ToolJumpPoint( scene.optic.right2FProperty, right2FPointNode.visibleProperty )
+      new ToolJumpPoint( scene.optic.primaryFocalPointProperty, primaryFocalPointNode.visibleProperty )
     ];
+
+    if ( scene.optic.secondaryFocalPointProperty && secondaryFocalPointNode instanceof FocalPointNode ) {
+      this.opticJumpPoints.push( new ToolJumpPoint( scene.optic.secondaryFocalPointProperty, secondaryFocalPointNode.visibleProperty ) );
+    }
+    this.opticJumpPoints.push( new ToolJumpPoint( scene.optic.primary2FProperty, primary2FPointNode.visibleProperty ) );
+
+    if ( scene.optic.secondary2FProperty && secondary2FPointNode instanceof TwoFPointNode ) {
+      this.opticJumpPoints.push( new ToolJumpPoint( scene.optic.secondary2FProperty, secondary2FPointNode.visibleProperty ) );
+    }
 
     // Visibility for associates labels
     this.opticNodeVisibleProperty = opticNode.visibleProperty;
     this.opticalAxisNodeVisibleProperty = opticalAxisNode.visibleProperty;
-    this.leftFocalPointNodeVisibleProperty = leftFocalPointNode.visibleProperty;
-    this.rightFocalPointNodeVisibleProperty = rightFocalPointNode.visibleProperty;
-    this.left2FPointNodeVisibleProperty = left2FPointNode.visibleProperty;
-    this.right2FPointNodeVisibleProperty = right2FPointNode.visibleProperty;
+    this.primaryFocalPointNodeVisibleProperty = primaryFocalPointNode.visibleProperty;
+    this.primary2FPointNodeVisibleProperty = primary2FPointNode.visibleProperty;
+
+    if ( secondaryFocalPointNode instanceof FocalPointNode ) {
+      this.secondaryFocalPointNodeVisibleProperty = secondaryFocalPointNode.visibleProperty;
+    }
+    if ( secondary2FPointNode instanceof TwoFPointNode ) {
+      this.secondary2FPointNodeVisibleProperty = secondary2FPointNode.visibleProperty;
+    }
   }
 }
 
-geometricOptics.register( 'GOSceneNode', GOSceneNode );
\ No newline at end of file
+geometricOptics.register( 'GOSceneNode', GOSceneNode );
Index: js/common/view/labels/GOLabelsNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/labels/GOLabelsNode.ts b/js/common/view/labels/GOLabelsNode.ts
--- a/js/common/view/labels/GOLabelsNode.ts	(revision 890b205bb2f59a39ad5160f872a533b17a6f353d)
+++ b/js/common/view/labels/GOLabelsNode.ts	(date 1682022083906)
@@ -71,39 +71,47 @@
 
     // Focal Point labels ------------------------------------------------------------------------------------
 
-    const leftFocalPointLabel = new LabelNode( GeometricOpticsStrings.label.FStringProperty,
-      optic.leftFocalPointProperty, zoomTransformProperty, {
+    const primaryFocalPointLabel = new LabelNode( GeometricOpticsStrings.label.FStringProperty,
+      optic.primaryFocalPointProperty, zoomTransformProperty, {
         yOffset: FOCAL_POINT_LABEL_Y_OFFSET,
-        visibleProperty: sceneNode.leftFocalPointNodeVisibleProperty,
-        tandem: providedOptions.tandem.createTandem( 'leftFocalPointLabel' )
+        visibleProperty: sceneNode.primaryFocalPointNodeVisibleProperty,
+        tandem: providedOptions.tandem.createTandem( 'primaryFocalPointLabel' )
       } );
-    this.addChild( leftFocalPointLabel );
+    this.addChild( primaryFocalPointLabel );
 
-    const rightFocalPointLabel = new LabelNode( GeometricOpticsStrings.label.FStringProperty,
-      optic.rightFocalPointProperty, zoomTransformProperty, {
-        yOffset: FOCAL_POINT_LABEL_Y_OFFSET,
-        visibleProperty: sceneNode.rightFocalPointNodeVisibleProperty,
-        tandem: providedOptions.tandem.createTandem( 'rightFocalPointLabel' )
-      } );
-    this.addChild( rightFocalPointLabel );
+    if ( optic.secondaryFocalPointProperty ) {
+
+      assert && assert( sceneNode.secondaryFocalPointNodeVisibleProperty, 'secondaryFocalPointNodeVisibleProperty is required' );
+      const secondaryFocalPointLabel = new LabelNode( GeometricOpticsStrings.label.FStringProperty,
+        optic.secondaryFocalPointProperty, zoomTransformProperty, {
+          yOffset: FOCAL_POINT_LABEL_Y_OFFSET,
+          visibleProperty: sceneNode.secondaryFocalPointNodeVisibleProperty!,
+          tandem: providedOptions.tandem.createTandem( 'secondaryFocalPointLabel' )
+        } );
+      this.addChild( secondaryFocalPointLabel );
+    }
 
     // 2F Point labels ----------------------------------------------------------------------------------------
 
-    const left2FPointLabel = new LabelNode( GeometricOpticsStrings.label.twoFStringProperty,
-      optic.left2FProperty, zoomTransformProperty, {
+    const primary2FPointLabel = new LabelNode( GeometricOpticsStrings.label.twoFStringProperty,
+      optic.primary2FProperty, zoomTransformProperty, {
         yOffset: FOCAL_POINT_LABEL_Y_OFFSET,
-        visibleProperty: sceneNode.left2FPointNodeVisibleProperty,
-        tandem: providedOptions.tandem.createTandem( 'left2FPointLabel' )
+        visibleProperty: sceneNode.primary2FPointNodeVisibleProperty,
+        tandem: providedOptions.tandem.createTandem( 'primary2FPointLabel' )
       } );
-    this.addChild( left2FPointLabel );
+    this.addChild( primary2FPointLabel );
 
-    const right2FPointLabel = new LabelNode( GeometricOpticsStrings.label.twoFStringProperty,
-      optic.right2FProperty, zoomTransformProperty, {
-        yOffset: FOCAL_POINT_LABEL_Y_OFFSET,
-        visibleProperty: sceneNode.right2FPointNodeVisibleProperty,
-        tandem: providedOptions.tandem.createTandem( 'right2FPointLabel' )
-      } );
-    this.addChild( right2FPointLabel );
+    if ( optic.secondary2FProperty ) {
+
+      assert && assert( sceneNode.secondary2FPointNodeVisibleProperty, 'secondary2FPointNodeVisibleProperty is required' );
+      const secondary2FPointLabel = new LabelNode( GeometricOpticsStrings.label.twoFStringProperty,
+        optic.secondary2FProperty, zoomTransformProperty, {
+          yOffset: FOCAL_POINT_LABEL_Y_OFFSET,
+          visibleProperty: sceneNode.secondary2FPointNodeVisibleProperty!,
+          tandem: providedOptions.tandem.createTandem( 'secondary2FPointLabel' )
+        } );
+      this.addChild( secondary2FPointLabel );
+    }
   }
 
   public override dispose(): void {
@@ -112,4 +120,4 @@
   }
 }
 
-geometricOptics.register( 'GOLabelsNode', GOLabelsNode );
\ No newline at end of file
+geometricOptics.register( 'GOLabelsNode', GOLabelsNode );
Index: js/common/model/Optic.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Optic.ts b/js/common/model/Optic.ts
--- a/js/common/model/Optic.ts	(revision 890b205bb2f59a39ad5160f872a533b17a6f353d)
+++ b/js/common/model/Optic.ts	(date 1682020309018)
@@ -32,6 +32,7 @@
 import optionize from '../../../../phet-core/js/optionize.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import PickOptional from '../../../../phet-core/js/types/PickOptional.js';
+import Lens from '../../lens/model/Lens.js';
 
 // A flat mirror has infinite focal length and ROC. We approximate a flat mirror as a convex mirror with very-large
 // focal length and ROC. Note that these very-large values will be visible in PhET-iO, and it was decided that is OK.
@@ -97,16 +98,16 @@
   // focal length (f) of the optic, converging is positive, diverging is negative focal length.
   public readonly focalLengthProperty: TReadOnlyProperty<number>;
 
-  // focal points (F) to the left and right of the optic
-  public readonly leftFocalPointProperty: ReadOnlyProperty<Vector2>;
-  public readonly rightFocalPointProperty: ReadOnlyProperty<Vector2>;
+  // focal points (F) of the optic, secondaryFocalPoint is only present for a lens
+  public readonly primaryFocalPointProperty: ReadOnlyProperty<Vector2>;
+  public readonly secondaryFocalPointProperty?: ReadOnlyProperty<Vector2>;
 
   // twice the focal length (2f) of the optic
   public readonly twiceFocalLengthProperty: TReadOnlyProperty<number>;
 
-  // 2F points to the left and right of the optic
-  public readonly left2FProperty: ReadOnlyProperty<Vector2>;
-  public readonly right2FProperty: ReadOnlyProperty<Vector2>;
+  // 2F points property of the optic, secondary2F is only present for a lens
+  public readonly primary2FProperty: ReadOnlyProperty<Vector2>;
+  public readonly secondary2FProperty?: ReadOnlyProperty<Vector2>;
 
   // Resets things that are specific to this class.
   private readonly resetOptic: () => void;
@@ -241,25 +242,27 @@
                              'while a diverging optic has a negative focal length.'
       } );
 
-    // left focal point (F)
-    this.leftFocalPointProperty = new DerivedProperty(
+    // primary focal point (F)
+    this.primaryFocalPointProperty = new DerivedProperty(
       [ this.positionProperty, this.focalLengthProperty ],
-      ( position, focalLength ) => position.plusXY( -Math.abs( focalLength ), 0 ), {
+      ( position, focalLength ) => position.plusXY( -focalLength, 0 ), {
         units: 'cm',
-        tandem: options.tandem.createTandem( 'leftFocalPointProperty' ),
+        tandem: options.tandem.createTandem( 'primaryFocalPointProperty' ),
         phetioValueType: Vector2.Vector2IO,
-        phetioDocumentation: 'focal point F, at a distance f to the left of the optic'
+        phetioDocumentation: 'focal point F, at a distance -f from the optic'
       } );
 
-    // right focal point (F)
-    this.rightFocalPointProperty = new DerivedProperty(
-      [ this.positionProperty, this.focalLengthProperty ],
-      ( position, focalLength ) => position.plusXY( Math.abs( focalLength ), 0 ), {
-        units: 'cm',
-        tandem: options.tandem.createTandem( 'rightFocalPointProperty' ),
-        phetioValueType: Vector2.Vector2IO,
-        phetioDocumentation: 'focal point F, at a distance f to the right of the optic'
-      } );
+    if ( this instanceof Lens ) {
+      // secondary focal point (F)
+      this.secondaryFocalPointProperty = new DerivedProperty(
+        [ this.positionProperty, this.focalLengthProperty ],
+        ( position, focalLength ) => position.plusXY( focalLength, 0 ), {
+          units: 'cm',
+          tandem: options.tandem.createTandem( 'secondaryFocalPointProperty' ),
+          phetioValueType: Vector2.Vector2IO,
+          phetioDocumentation: 'focal point F, at a distance +f from the optic'
+        } );
+    }
 
     // 2f
     this.twiceFocalLengthProperty = new DerivedProperty( [ this.focalLengthProperty ], focalLength => 2 * focalLength, {
@@ -269,25 +272,27 @@
       phetioDocumentation: '2f, twice the focal length'
     } );
 
-    // left 2F point
-    this.left2FProperty = new DerivedProperty(
+    // Primary 2F point
+    this.primary2FProperty = new DerivedProperty(
       [ this.positionProperty, this.twiceFocalLengthProperty ],
-      ( position, twiceFocalLength ) => position.plusXY( -Math.abs( twiceFocalLength ), 0 ), {
+      ( position, twiceFocalLength ) => position.plusXY( -twiceFocalLength, 0 ), {
         units: 'cm',
-        tandem: options.tandem.createTandem( 'left2FProperty' ),
+        tandem: options.tandem.createTandem( 'primary2FProperty' ),
         phetioValueType: Vector2.Vector2IO,
-        phetioDocumentation: 'point 2F, at a distance 2f to the left of the optic'
+        phetioDocumentation: 'point 2F, at a distance -2f from the optic'
       } );
 
-    // right 2F point
-    this.right2FProperty = new DerivedProperty(
-      [ this.positionProperty, this.twiceFocalLengthProperty ],
-      ( position, twiceFocalLength ) => position.plusXY( Math.abs( twiceFocalLength ), 0 ), {
-        units: 'cm',
-        tandem: options.tandem.createTandem( 'right2FProperty' ),
-        phetioValueType: Vector2.Vector2IO,
-        phetioDocumentation: 'point 2F, at a distance 2f to the right of the optic'
-      } );
+    // Secondary 2F point, only if this is a Lens
+    if ( this instanceof Lens ) {
+      this.secondary2FProperty = new DerivedProperty(
+        [ this.positionProperty, this.twiceFocalLengthProperty ],
+        ( position, twiceFocalLength ) => position.plusXY( twiceFocalLength, 0 ), {
+          units: 'cm',
+          tandem: options.tandem.createTandem( 'secondary2FProperty' ),
+          phetioValueType: Vector2.Vector2IO,
+          phetioDocumentation: 'point 2F, at a distance +2f from the optic'
+        } );
+    }
 
     this.resetOptic = () => {
       this.opticSurfaceTypeProperty.reset();
@@ -386,4 +391,4 @@
   }
 }
 
-geometricOptics.register( 'Optic', Optic );
\ No newline at end of file
+geometricOptics.register( 'Optic', Optic );
</details>

**Comment by veillette** [comment]
It turns out to be relatively easy to address the model for the focal points and 2F points as the sign of the focal length does all the heavy lifting for you.  For instance, in `Optic`,  the primary and secondary focal point become,

````js
    // primary focal point (F)
    this.primaryFocalPointProperty = new DerivedProperty(
      [ this.positionProperty, this.focalLengthProperty ],
      ( position, focalLength ) => position.plusXY( -focalLength, 0 ), {
        units: 'cm',
        tandem: options.tandem.createTandem( 'primaryFocalPointProperty' ),
        phetioValueType: Vector2.Vector2IO,
        phetioDocumentation: 'focal point F, at a distance -f from the optic'
      } );

    if ( this instanceof Lens ) {
      // secondary focal point (F)
      this.secondaryFocalPointProperty = new DerivedProperty(
        [ this.positionProperty, this.focalLengthProperty ],
        ( position, focalLength ) => position.plusXY( focalLength, 0 ), {
          units: 'cm',
          tandem: options.tandem.createTandem( 'secondaryFocalPointProperty' ),
          phetioValueType: Vector2.Vector2IO,
          phetioDocumentation: 'focal point F, at a distance +f from the optic'
        } );
    }
````
The complications mostly arise from the conditional instantiation of `secondaryFocalPointProperty`, which must be taken into account in `GOLabelsNode` and `GOSceneNode`. As @pixelzoom pointed out in #458, you must create then instantion conditionally some nodes, add jump points  conditionally for keyboard navigation, nodes to the scene graph are added conditionally as well labels are added conditionally. 

The same process must be followed for the 2F points.

**Comment by pixelzoom** [comment]
I'm not totally clear on what needs to be done here.  But it will change the PhET-iO API, so should be done before 1.3 release.

If I understand correctly, the "mirrors" portion of this issue has been moved to #458.

Assigning to @arouinfar to specify what changes should be made for lenses.

**Comment by pixelzoom** [comment]
I've complete the changes that @arouinfar and I discussed this morning.  Summary:

* In the Lens screen, there are no changes. The visibility of `leftFocalPointNode` and `rightFocalPointNode` are linked directly to `visibleProperties.focalPointsVisibleProperty`, while the visibility of `left2FPointNode` and `right2FPointNode` are linked directly to `visibleProperties.twoFPointsVisibleProperty`.

* In the Mirror screen, `visibleProperty` for `leftFocalPointNode`, `rightFocalPointNode`, `left2FPointNode`, and `right2FPointNode` is now derived.   I've included this comment in the code:

```ts
    /**
     * A note about visibility of focal points (F and 2F), see https://github.com/phetsims/geometric-optics/issues/457.
     * A lens has 2 focal points. But since a mirror only has one surface, it only has one focal point. Unfortunately,
     * our Optic base class is very dependent on having two F and 2F points. So rather than modify the model, we decided
     * to control the visibility of F and 2F in the view - see 'visibleProperty: new DerivedProperty(...)' below.
     * For a lens, all F and 2F points are made visible.
     * For a concave mirror, F and 2F are on the left, so only leftFocalPointNode and left2FPointNode are made visible.
     * For a convex mirror, F and 2F are on the right, so only rightFocalPointNode and right2FPointNode are visible.
     * For a flat mirror, F and 2F are at infinity, so all F and 2F points are made invisible.
     */
```

* Query parameter `mirrorXOffset` has been added. This is x-offset from the center of the screen (layout bounds). It applies only to the full version of the sim, and the default is 200.  Note that Geometric Optics: Basics puts the mirror in the center of the screen, and I don't see any reason why we need to adjust it.

* If you run with `?log`, moving the optical object will print its position to the browser console. Use this in conjunction with `?mirrorXOffset` to decide on where the mirror should be located, and where the optical objects should initially be placed. Don't forget about the "second point" for the Light scene -- the second light has its own independent position.

@arouinfar please review my changes, check the Studio tree, and let me know if you'd like to relocate the mirror and optical objects.

**Comment by pixelzoom** [comment]
I added this section to [model.md](https://github.com/phetsims/geometric-optics/blob/master/doc/model.md). @arouinfar left me know if you'd like to revise, or do so directly. 

> A lens has two focal points (F) and two 2F points, while a mirror only has one surface, and therefore
only one F point and one 2F point.  This difference is correctly reflected in the view for this simulation.
But as an implementation simplification, the model has two F points and two 2F points for both types of optics
(lens and mirror). More specifically for this simulation:
> * For a lens, F and 2F points appear on both sides of the lens.
> * For a concave mirror, F and 2F appear to the _left_ of the mirror.
> * For a convex mirror, F and 2F appear to the _right_ of the mirror.
> * For a flat mirror, F and 2F are at infinity, so are not visible in the simulation.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! The sim, PhET-iO tree, and updates to model.md all look good to me.

> Note that Geometric Optics: Basics puts the mirror in the center of the screen, and I don't see any reason why we need to adjust it.

Agreed, no changes necessary to Basics.

> Don't forget about the "second point" for the Light scene -- the second light has its own independent position.

Luckily, the Light scene only exists for Lenses, so nothing to do for mirrors. 

>  let me know if you'd like to relocate the mirror and optical objects.

I think we should shift the mirror and object positions, so I spent some time experimenting with `mirrorXOffset`. For the concave mirror, we want the image to be visible for a reasonable range. For the convex mirror, the concern is the 2F points.

`mirrorXOffset=100` with and an initial x-position of -150 for the object looks good to me. At the default focal length/ROC, the concave mirror's image and convex mirror's 2F point are both well within view.

| ROC = 180 cm (default) | ROC = 205 cm |
| --- | --- |
| <img width="957" alt="Screen Shot 2023-05-03 at 2 14 02 PM" src="https://user-images.githubusercontent.com/8419308/236039693-513f01da-8046-402f-af61-ff880a410ff8.png"> |  <img width="956" alt="Screen Shot 2023-05-03 at 2 16 07 PM" src="https://user-images.githubusercontent.com/8419308/236039701-19c8fe9a-04e7-4492-a5d3-aa1c915d81bf.png"> |
| <img width="957" alt="Screen Shot 2023-05-03 at 2 16 34 PM" src="https://user-images.githubusercontent.com/8419308/236039709-50c9f719-783d-4dfc-b9dd-75071c8d153c.png">  | <img width="960" alt="Screen Shot 2023-05-03 at 2 16 19 PM" src="https://user-images.githubusercontent.com/8419308/236039706-471c57aa-300e-4797-9e59-403a16fc97e8.png"> |

For the Mirror screen in Geometric Optics (no changes to Lens screen or Basics)
- [ ] Move the mirror to the left, `mirrorXOffset=100`
- [ ] Default `objectDistanceProperty` should be 150 cm, (equivalent x-coordinate with `log` was -150)

**Comment by pixelzoom** [comment]
Prior to making changes to the mirror and object positions, I published geometric-optics 1.2.0-dev.3:

* https://phet-dev.colorado.edu/html/geometric-optics/1.2.0-dev.3/phet/geometric-optics_all_phet.html
* https://phet-dev.colorado.edu/html/geometric-optics/1.2.0-dev.3/phet-io/

**Comment by pixelzoom** [comment]
> > Don't forget about the "second point" for the Light scene -- the second light has its own independent position.
>
> Luckily, the Light scene only exists for Lenses, so nothing to do for mirrors.

Ah, but the Arrows scene also has a second arrow.   And the arrows have a different origin (arrow tip) than the framed objects (upper-left corner of picture frame).   So the position of the arrows also needs to be adjusted.

The orginal position of framed objects was x=-130, and you moved it to x=-150.  So I also moved the first and second arrows an additional 20 units to the left, to x=-150 and x=-165 respectively.   The `mirrorXOffset` query parameter is still available, if you want to make additional changes. 

@arouinfar Please confirm that this looks OK in master.  If it's OK, assign back to me to remove the `mirrorXOffset` query parameter.

**Comment by arouinfar** [comment]
> Ah, but the Arrows scene also has a second arrow. 

I knew I was forgetting something! 

> Please confirm that this looks OK in master. If it's OK, assign back to me to remove the mirrorXOffset query parameter.

Master looks great, back to you.

**Comment by pixelzoom** [comment]
`mirrorXOffset` removed in the above commit. Closing.
