### ISSUE TITLE
GeometricOpticsRulerNode needs a dispose function 

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#46]
There are several GeometricOpticsRulers that are (possibly) created in this simulation. This can create a memory leak.

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/122974930-d5124e80-d360-11eb-8fbc-852ac5d8a8b1.png)

There are only four GeometricOpticsRulerNodes that are present at a given time. The memory footprint seems reasonable as well.

**Comment by sarchang** [comment]
Memory leak addressed.
