### ISSUE TITLE
Fix tandem name for `focalLengthModelTypeControl`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#462]
In GOPreferencesNode.ts:

```ts
    const focalLengthModelControl = new FocalLengthModelTypeControl( GOPreferences.focalLengthModelTypeProperty, {
      tandem: options.tandem.createTandem( 'focalLengthModelControl' )
    } );
```

Per PhET naming convenstions, the `const` and tandem name should both be `focalLengthModelTypeControl`.

**Comment by pixelzoom** [comment]
Done in the above commit. Studio tree shown below.  Note that the name `focalLengthModelTypeControl` now matches the linked element `focalLengthModelTypeProperty`.  @arouinfar FYI, feel free to close if this looks OK.

<img width="356" alt="screenshot_2502" src="https://user-images.githubusercontent.com/3046552/236108449-93d76699-fcde-41e4-ad76-7a9efb3b56b2.png">

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!
