### ISSUE TITLE
Examples document lists element that doesn't exist.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#466]
`geometricOptics.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.simPreferences.focalLengthModelTypeControl.visibleProperty` is listed in the examples but does not seem to exist. I suspect it should read `geometricOptics.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.simPreferences.focalLengthModelTypeControl.visibleProperty` instead, with the archetype section missing in the examples document.
For https://github.com/phetsims/qa/issues/938

**Comment by Nancy-Salpepi** [comment]
@KatieWoe I have encountered this a few times. I keep forgetting that the preferences dialog needs to be open first. Then it works. 
My eyes alway skip over that sentence, even though it is there!
<img width="1140" alt="Screenshot 2023-05-10 at 5 31 53 PM" src="https://github.com/phetsims/geometric-optics/assets/87318828/cb98e222-6419-4c5a-8b01-23810848bc8c">

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi! You are correct, the issue here is that the Preferences dialog wasn't first opened. Since the examples doc includes this reminder, there isn't really anything to do here, closing.
