### ISSUE TITLE
Zoom Factor

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#47]
The zoom factor is set to 2. 
There is one level of zooming in and one of zooming out.

The factor of two makes it convenient to draw rulers.
Should we work on make the ruler more robust such that other zoom levels (factors) be possible?

**Comment by veillette** [comment]
Assigning @sarchang to work on this issue.

**Comment by sarchang** [comment]
changed default zoom level and extended optical axis

**Comment by veillette** [comment]
Good. I created a new issue #54, to track the handling of the optical axis. Closing this issue.
