### ISSUE TITLE
Interactive highlight doesn't expand with longer screen names in nav bar

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#470]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/947, but also seen in published MSS:

In the nav bar, when a screen name is long in another locale, the interactive highlight doesn't expand to surround the entire name.  Also, the white highlight that usually appears  on either side of the screen icon when you hover is only covered by the interactive highlight on one side. 

**Steps to reproduce**
1.  add ?stringTest=dynamic to the end of the url
2. Go to either screen
3. In the Visual Tab of of the Preferences Menu, turn on Interactive highlights and exit the menu
4. Press the right arrow once
5. Hover mouse over both screen names in the nav bar

**Visuals**
<img width="88" alt="Screenshot 2023-05-24 at 1 38 43 PM" src="https://github.com/phetsims/geometric-optics/assets/87318828/802b2b06-4756-4bb1-b409-661dd19e84d6">

<img width="88" alt="Screenshot 2023-05-24 at 1 07 13 PM" src="https://github.com/phetsims/geometric-optics/assets/87318828/7b7b0dcd-500e-4e51-adb1-f84d83499254">

**Comment by pixelzoom** [comment]
This is a common-code (joist) issue, not specific to the simulation.  I'm not sure how or where it should be addressed.  But it seems like something should handle making the focus rectangle larger when a Node has focus and its bound change.  Let's start for assigning to @jonathanolson and @jessegreenberg to determine how to proceed.

**Comment by jessegreenberg** [comment]
Thanks for reporting this @Nancy-Salpepi. Generally the highlight does resize to fit the Node's bounds. But that isn't happening here because NavigationBarScreenButton is using a custom highlight that does not update.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg, good to know that it's specific to NavigationBarScreenButton, but unfortunate that NavigationBarScreenButton isn't able to use the general Node support for this.  Who do you think should address this? And would the changes need to be made in NavigationBarScreenButton.ts?

**Comment by pixelzoom** [comment]
Since this is a general issue, it will be tracked in https://github.com/phetsims/joist/issues/926.  When that issue is addressed, we'll cherry-pick the fix to geometric-optics 1.3.

**Comment by pixelzoom** [comment]
This is ready to proceed with verification and cherry-pick, see https://github.com/phetsims/joist/issues/926#issuecomment-1563554462.

**Comment by pixelzoom** [comment]
Patch is completed for geometric-optics 1.3 and geometric-optics-basics 1.3.

To verifying in the next RC, follow the steps in https://github.com/phetsims/geometric-optics/issues/470#issue-1724478680.

**Comment by KatieWoe** [comment]
On Win 11 Chrome the bottom of the highlight looks cut off now: 
![image](https://github.com/phetsims/geometric-optics/assets/41024075/df2fb46b-28fa-4074-89a1-955e037b62de)

**Comment by KatieWoe** [comment]
Other than https://github.com/phetsims/geometric-optics/issues/470#issuecomment-1574012861, which may not be an issue, this looks good on Win 11 Chrome. I'll leave it to you to decide if this is worth addressing @pixelzoom. If not this can probably be closed.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/926#issuecomment-1563411208, @jessegreenberg said:
> ... The highlight shape was changed slightly so that it does not cover up the title text when longer strings get scaled down. The bottom of the highlight is cut off a little but @amanda-phet and I think it is acceptable and the best option with limited space in the nav bar.

But it looks like the bottom of the highlight is entirely cut off on Win11 + Chrome.  @arouinfar @jessegreenberg is that acceptable?

**Comment by jessegreenberg** [comment]
The above commit is an improvement that cuts off less. This is what it looks like for me on Win 10 Chrome. 
![image](https://github.com/phetsims/geometric-optics/assets/6396244/cb3cc337-1fb4-499c-a9ca-feb7a1008314)
![image](https://github.com/phetsims/geometric-optics/assets/6396244/80703d25-4fbe-44c8-b60b-c73f53a5be0c)

@KatieWoe can you try master on Win 11?

**Comment by pixelzoom** [comment]
Noting that for default screen names, the highlight extends slightly above the navbar.  This occurs on all supported browsers for macOS.  I have not tested other platforms.  But I think this is fine, and definitely better than the previous behavior.

<img width="1536" alt="screenshot_2558" src="https://github.com/phetsims/geometric-optics/assets/3046552/f662dc0f-d8b2-4c57-854e-0f118cf453c7">

**Comment by KatieWoe** [comment]
Looks better on master to me on Win 11 Chrome too. I did notice that if a letter has a bellow the line aspect it can get covered up. 
![image](https://github.com/phetsims/geometric-optics/assets/41024075/4cebd9ac-92f8-48ce-adf6-4a7f00f96acc)

**Comment by jessegreenberg** [comment]
OK, great. If the slight letter cover up is not acceptable I can revert the change. If you like this improvement then https://github.com/phetsims/joist/commit/a1d9d683b6776d1c990a71bde6618ccbe11f54a5 can be cherry-picked into the joist release branch for geometric-optics. @arouinfar what do you prefer?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. I think the current behavior on master is an improvement over what happened in https://github.com/phetsims/geometric-optics/issues/470#issuecomment-1574012861. I recommend we keep the changes.

**Comment by pixelzoom** [comment]
My recommendation for next steps:

If this is the only issue found in 1.3.0-rc.3, then publish 1.3 with this as a known problem. This does not affect usability at all, and it does not seem worth the cost to do another RC.

If on the other hand there are other issues with 1.3.0-rc.3, then I'll cherry-pick this and the change to examples.md in https://github.com/phetsims/geometric-optics-basics/issues/40. 

@arouinfar do you agree?

**Comment by arouinfar** [comment]
QA just finished the spot check, and this was the only issue identified. @pixelzoom, I don't think this merits another RC cycle. We can pick up the fix in the 1.4 release.
