### ISSUE TITLE
Movement of Second Point with Keyboard Nav is sometimes delayed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#474]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari/Chrome/FF

**Problem description**
For https://github.com/phetsims/qa/issues/947, if I hold down the `w`, `s`, or up/down arrows for a bit longer than necessary to reach the top/bottom position for the Second Point on a framed object, there is a delay when I go to move the Second Point again. This even happens if I tab away and then return to the Second Point. 

**Steps to reproduce**
1. On either screen, check the Second Point Checkbox
2. Tab to the Second Point
3. Press and hold the Up Arrow longer than is needed to reach the highest position
4. Press and hold the Down Arrow

**Comment by pixelzoom** [comment]
Reproduced in master for the second point on framed objects (Pencil, Penguin, Star).

I do not see this for the second point (second light) when "Light" is selected from the combobox. @Nancy-Salpepi is that the case for you too?

**Comment by pixelzoom** [comment]
Attempting to drag the second point above/below its range also results in having to press the up/down arrows many times before the second point actually moved.

**Comment by pixelzoom** [comment]
Another bit of weirdness:

1. Go to the Lens screen, with Pencil selected.
2. Turn on "Second Point" checkbox
3. Tab to the second point so that it has focus.  Note that it's default position is at  the _bottom_ of its range.
4. Press the _down_ arrow button. We expect nothing to happen because the second point is at the bottom of its range. But it immediately moves to the _top_ of its range.

Something similar does NOT happen when the _up_ arrow is pressed when the second point is at the _top_ of its range.

**Comment by pixelzoom** [comment]
Unrelated to the problem, but I suspect this change should be made in SecondPointNode.ts:

```diff
-   const drag = () => {
+   const startDrag = () => {
      wasDraggedProperty.value = true;
    };

    const dragListener = new DragListener( {
      positionProperty: positionProperty,
      transform: modelViewTransform,
-     drag: drag,
+     start: startDrag,
      tandem: options.tandem.createTandem( 'dragListener' )
    } );
    this.addInputListener( dragListener );

    const keyboardDragListener = new KeyboardDragListener(
      combineOptions<KeyboardDragListenerOptions>( {}, GOConstants.KEYBOARD_DRAG_LISTENER_OPTIONS, {
        positionProperty: positionProperty,
        transform: modelViewTransform,
-       drag: drag,
+       start: startDraag,
        tandem: options.tandem.createTandem( 'keyboardDragListener' )
      } ) );
```

**Comment by pixelzoom** [comment]
Everything looks OK in SecondPointNode.ts.  The next thing to check is whether the `modelViewTransform` passed to the constructor is correct.

**Comment by pixelzoom** [comment]
While I'm at it, this documentation in SecondPoint.ts needs improvement:

```diff
- // position of the second point
+ // position of the second point in the global model coordinate frame
  public readonly positionProperty: TReadOnlyProperty<Vector2>;

  /**
   * Sets the second point-of-interest on the framed object.
-  * @param position - relative to the framed object's position
+  * @param position - in the global model coordinate frame
   */
  public setSecondPoint( position: Vector2 ): void {
```

**Comment by pixelzoom** [comment]
Fixed and cherry-picked in the above commits.

@Nancy-Salpepi please verify in master. If it's OK, change the label to "status:fixed-awaiting-deploy" and we'll test in the next RC.

**Comment by pixelzoom** [comment]
Ready for review in 1.3.0-rc.3.  Please follow the steps in https://github.com/phetsims/geometric-optics/issues/474#issue-1728088003.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3. Closing.
