### ISSUE TITLE
Should Interactive Highlights being active be stateful

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#475]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/947
The Interactive Highlights option being active is not stateful. I'm not sure if it should be or not.
From Slack:
>Chris Malley
I doubt it.  But that’s a question for Jesse, Sam, and Michael.  Go ahead and create a GO issue, and assign it to them.

**Visuals**
![interact](https://github.com/phetsims/geometric-optics/assets/41024075/f26abf09-4349-49db-bbb4-0b29dac458aa)

**Comment by jessegreenberg** [comment]
No, it should not be stateful according to https://github.com/phetsims/phet-io-sim-specific/blob/d673f4bd894b6d343ad8481e6b3530c23b18ce95/client-guide-common/client-guide/phet-io-guide.md#preferences-customization.
