### ISSUE TITLE
labels for lens and mirror should be translatable.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#48]
The label for concave label should be only one string such that it can be easily translated. 
We are currently concatenating strings, but this only work in english.

**Comment by sarchang** [comment]
@veillette I tried to use the ternary operators on this one; not sure if this is the best solution...

**Comment by veillette** [comment]
@sarchang : I think the nested ternary operators are a bit much in this situation.  It makes it harder to read, since the expression is so long.. 
It would be more readable with an if statement even though it will end up taking many more lines.

**Comment by veillette** [comment]
reassigning back to @sarchang

**Comment by sarchang** [comment]
changed to nested conditionals @veillette

**Comment by veillette** [comment]
I changed it to a mix of if statement and ternary. In my opinion, it is the most readable 
```

 let curveOpticString;

      // string associated with optic and curve
      if ( model.optic.isConvex( curve ) ) {
        curveOpticString = model.optic.isLens() ? convexLensString : convexMirrorString;
      }
      else if ( model.optic.isConcave( curve ) ) {
        curveOpticString = model.optic.isLens() ? concaveLensString : concaveMirrorString;
      }

```

**Comment by veillette** [comment]
Our work is done. Closing
