### ISSUE TITLE
Chromebook performance is laggy with "Many Rays" selected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#482]
In https://github.com/phetsims/qa/issues/947#issuecomment-1572505377, @Nancy-Salpepi reported:

> Noting that with the Chromebook, some jerkiness/lagging can be seen when holding down increment/decrement buttons with Many Rays selected. Also noting that the jerkiness happens when moving a slider with keyboard nav with Many Rays selected.  @stemilymill also sees this with her Chromebook. Not sure if it was worthy of an issue or not. 

<details>
  <summary>Video</summary>
  

https://github.com/phetsims/qa/assets/87318828/8065ab86-694c-4897-b74d-4692ee66af38

</details>

**Comment by pixelzoom** [comment]
The "Many Rays" mode is obviously drawing the most rays, so presents the biggest perform "lift".  I don't know how to speed this up.  So if not a major annoyance, I'm inclined to do nothing for this.

@Nancy-Salpepi How would you rate the serverity?  Does it impact usability significantly? Is it distracting enough to distrupt learning?

**Comment by Nancy-Salpepi** [comment]
I think it is OK. If I hit the button repeatedly with the mouse instead of holding it down, it works just fine. Same for moving the slider with keyboard nav. 
I really don't think it is worth the time.

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.  I'm going to close this as "won't fix".  @arouinfar FYI, reopen if you disagree.
