### ISSUE TITLE
 add arrows on the the rays

### ISSUE THREAD

**Issue by roczyl** [phetsims/geometric-optics#485]
Can I add arrows on the the rays?

**Comment by pixelzoom** [comment]
You currently cannot add arrows to the rays.  Can you explain why you'd like to add them, and how you'd like them to look?

**Comment by pixelzoom** [comment]
Assigning to @oliver-phet in case he is tracking user requests.

**Comment by pixelzoom** [comment]
No reply from the submitter after 8 months, so closing this issue.
