### ISSUE TITLE
Create screen icons in code

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#51]
Screen icon for Lens screen: a convex lens
for Mirror screen: a concave mirror

Should create a method for creating lens/mirror icons which should be used for the Curve Control buttons

**Comment by veillette** [comment]
In order to make this, we should create a seperate class that had the information about the shapes of the optic, i.e. the outline and the fill.

**Comment by veillette** [comment]
We have created a static method in CurveControl  that can create  a scenery Node that depends on radius, diameter, curve and type of optic. 

This is now leveraged in the curveControl class  as well as the Mirror and Lens ScreenView.

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/126678942-14fcc8ce-9051-4c5b-a9f2-1cfb072d0021.png)


I assigned preliminary sizes and colors, but I'm assigning it @arouinfar  for further design decisions.

**Comment by veillette** [comment]
Our work is done. Closing
