### ISSUE TITLE
Switch order for curve lens buttons

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#52]
The convex lens icon button should be atop the concave button for the lens screen. Mirror screen is fine.

**Comment by sarchang** [comment]
Order of curve control buttons is now correct. Lens screen starts on convex lens (top button). 
But mirror screen starts on convex mirror (bottom button). Maybe change this so that it starts on the top mirror button? @veillette

**Comment by veillette** [comment]
well done. Closing
