### ISSUE TITLE
Ruler and toolBox.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#55]
- [x] Rulers should be returned when cursor and ruler overlap with toolbox.
- [x] Ruler touch margins should be expanded. 
- [x] Add touchsnag
- [x] Vertical ruler should be taller

**Comment by sarchang** [comment]
I noticed that the font size of "cm" on the horizontal ruler decreases slightly when zooming out to the most zoomed out level.

**Comment by veillette** [comment]
in RulerNode, there is some logic to determine the max width of the string.
````
          // make sure the units label fits between the tick mark labels
          unitsLabelMaxWidth = majorTickLabelNode.left - options.unitsSpacing - unitsLabel.left;
          assert && assert( unitsLabelMaxWidth > 0, 'space for units label is negative or zero' );
          unitsLabel.maxWidth = unitsLabelMaxWidth;
````
and 
````
// Handle the case where the units label extends off the edge of the ruler.  This is kind of a corner case, but was
    // seen when testing long strings on Pendulum Lab.
    if ( unitsLabel.bounds.maxX > backgroundNode.bounds.maxX - options.unitsSpacing ) {
      unitsLabelMaxWidth = ( backgroundNode.bounds.maxX - options.unitsSpacing ) - unitsLabel.x;
      unitsLabel.scale( unitsLabelMaxWidth / unitsLabel.width );
    }
````

When the text strings  gets longer (say 160 instead of 80), there is less space left for layout the units.

**Comment by veillette** [comment]
The touch bounds screen have been increased.
![image](https://user-images.githubusercontent.com/7633344/123302771-0ae33e80-d4eb-11eb-9a1e-b48ab4c70af1.png)

**Comment by sarchang** [comment]
When I start the simulation, change the zoom level, and then drag a ruler out of the toolbox, the initial position of the ruler when I start the drag is not where my cursor is.
This issue does not happen when I click on the rulers before changing the zoom level.

**Comment by veillette** [comment]
@sarchang , you should create a new issue describing the problem with the ruler start drag

**Comment by veillette** [comment]
This issue is addressed. Tracking the problem with ruler in #56. Closing this issue
