### ISSUE TITLE
Second light source can be dragged to the right of the lens.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#58]
similar to the object, the movable source of light should have dragbounds.

**Comment by pixelzoom** [comment]
The second light source is draggable to the right of the lens, see below.  This was present in 1.0.0-dev.9 (7/30/21).  

@arouinfar Don't you think this should be fixed for the Prototype milestone?

<img width="988" alt="screenshot_1271" src="https://user-images.githubusercontent.com/3046552/134599933-bddb3297-e3a9-44e9-b55e-373ee9e4db84.png">

**Comment by pixelzoom** [comment]
9/30/21 design meeting:

Both light sources should have the same drag bounds.
