### ISSUE TITLE
Should rays from movable point animate after the object rays have already animated?

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#63]
There are two bundles of ray in the simulation. One from the object and a second one from the movable point. 

When the show/hide button is toggle the rays will animate from the object position.
However, if one checks the movable point check point. Currently the rays appear statically.
Our question is "Should the rays from movable point be animated after the object rays have already finished their animation.

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/124181331-5b2a4580-da83-11eb-8980-cd07c89b5b87.png)

**Comment by sarchang** [comment]
Keep as is; don't need to animate second one

**Comment by sarchang** [comment]
Amy answered our question.
