### ISSUE TITLE
Behavior of Guides when movable point is visible.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#64]
The flash simulation has guides that switch from the object position to the movable point position when the movable point checkbox is toggled. 

We just realized that our simulation always track the object position rather than the movable point position.

Before we change our codebase, we want to make sure that this behavior is desired.

**Comment by sarchang** [comment]
From Amy: Guides should follow the object (keep as is), but discuss at design meeting to confirm.

**Comment by veillette** [comment]
At the 7/6 design meeting, we decided that the guides should follow the behavior of the flash simulation.

**Comment by veillette** [comment]
Our work is done here. Closing
