### ISSUE TITLE
Corresponding image for movable point (tiny red dot)

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#65]
![image](https://user-images.githubusercontent.com/7633344/124185718-51a3dc00-da89-11eb-90c4-0eb69f03922d.png)

**Comment by sarchang** [comment]
From Amy: tiny red dot was probably not supposed to be there; definitely remove. But consider the possibility of adding a "ghost" of the movable point on the image that is the same size as the actual movable point to show where the movable point's rays would converge they were shown. Discuss at design meeting.

**Comment by veillette** [comment]
The discussion from the 7/6 meeting was to not have any indication of the 2nd point on the image. 
The conclusion was based on the idea that by starting on the marginal rays, it should be clear what is the effect of the second source (movable point).

**Comment by veillette** [comment]
Since we dont have a second image point to implement, we can close this issue.
