### ISSUE TITLE
Reconsider wording of "Movable Point" checkbox

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#67]
Toggling the "Movable Point" checkbox makes both a red dot or a red lamp appear, depending on which object is chosen.  The term "Movable Point" does not make sense to describe the second lamp.  Maybe "second source"?  Should the text for the checkbox change for objects vs. spotlight/screen?

**Comment by veillette** [comment]
At the 7/6 design meeting, it was decided that the text "second source" should be used throughout the sim.  Also the spacing between the icon and the text should increase.

**Comment by sarchang** [comment]
Changed the spacing:
before
![image](https://user-images.githubusercontent.com/29347882/124670156-cce20500-de70-11eb-956d-ec8e7f9a8d27.png)
after
![image](https://user-images.githubusercontent.com/29347882/124670196-dbc8b780-de70-11eb-9bf8-96df9a055743.png)
Not sure if this is enough. The spacing for both icons is controlled by one HBox `spacing` option, which is now set to 8. Not sure if it is a problem that the yellow X looks like it has a larger space than the red circle.

**Comment by veillette** [comment]
That looks good closing.
