### ISSUE TITLE
Timing of spotlight appearance for lamp/screen

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#69]
Currently, when the show/hide button is toggled for the lamp/screen, the spotlight (yellow circle) appears on the black screen when the rays converge. The spotlight should appear when the rays reach the screen.

**Comment by phet-steele** [comment]
I should note that with the current timing, the spotlight never appears at all if the screen is placed in front of the point where the light converges before the show/hide button is toggled.

![image](https://user-images.githubusercontent.com/5863899/125140114-0ca62800-e0cf-11eb-9d92-57e6bc044d0a.png)

The sim waits for the light to converge, so if the screen is dragged backwards and past the convergence point, the spotlight appropriately appears.

![image](https://user-images.githubusercontent.com/5863899/125140369-9524c880-e0cf-11eb-8e64-efbdb4aaa381.png)

I see this on Win 10 FF, for phetsims/qa/issues/667

**Comment by veillette** [comment]
This is now fixed following the work in #98. Closing
