### ISSUE TITLE
Create guides feature

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#7]
The guides exist at the top and bottom of the lens. Each guide is made of three graphical element. A disk that represents a pivot point, and two long rectangles that extend from the disk. 

The rectangle on the side of the object always point directly to the object.  The internal angle between the two rectangles is a property of the lens.

For a convex lens, the guide internal angles is determined by the following method.
- Place the object on the optical axis, at twice the focal length. The image will then be located at twice the focal length
- The internal guides should point exactly toward the object and images   
![image](https://user-images.githubusercontent.com/7633344/119529826-71d8d080-bd50-11eb-8109-a884028749d9.png)

Mathematically, the internal angle is 2 arctan(d/4f) where d is the diameter of the lens. 
This method defines the internal angle for the guides. From this point on, the internal angle is set for the lens.

For a concave lens (diverging), we can use the following procedure to set the internal angle.
- Place the object on the optical axis, at twice the focal length. The image will then be located at 1/2 the focal length
- The internal guides should point exactly toward the object and image.   

Mathematically, the internal angle is  equal to pi- arctan(d/4f)- arctan(d/f) where d is the diameter of the lens. 

Using the model view approach, there should be a module called Guide.js that would determine 
(1) the position of the fulcrum point
(2) the appropriate internal angle for the lens
(3) the angle of rotation of the guide such that it points back to the object.

The constructor for guide should depend on (1) the position of the object, (2) the optic and (3) and a config parameter , that indicate the location of the guide (top or bottom).  Since we are using axon properties throughout the simulation, it would be most appropriate to define the three previous properties as derived properties.
(You should be able to find multiple examples of derived properties in the simulation.)
Since the guides are only relevant for lenses, the guide module should exist in the subfolder Lens and should be instantiated in Lens module. You should create two such guides (one for the top guide and one for the bottom guide).

The view module should be called GuideNode.js and its constructor should depend on  the appropriate model guide , the modelviewTransform and the visibilityProperty. Two such guideNode should be instantiated is LensScreenView. 
 The guide node should create the circle and two rectangles for each guide. The modelviewtransform can be used to position the fulcrum point.  I think that  Node method rotateAround will be useful for all the rotation of the guideNode. 
As an aside, since we are using an inverted  y axis in the model but  an upright coordinate system in the view, a clockwise rotation in the model is anticlockwise in the view.

The visibility of the guides should be controlled by the property this.visibleGuidesProperty in VisibleProperties.js.

**Comment by veillette** [comment]
S

**Comment by sarchang** [comment]
Left guide follows light ray from object. Fulcrum circle and left guide both follow movement of lens.

**Comment by sarchang** [comment]
The two components of guide are now referred to as the incident and transmitted rectangles. The model has two properties: incidentAngleProperty and transmittedAngleProperty. The transmittedAngleProperty = incidentAngleProperty + internalAngleProperty. This makes it easier to abstract the rotation of the rectangles.

**Comment by sarchang** [comment]
Guides are created.
