### ISSUE TITLE
How to handle rays that go around the optic

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#70]
In the flash sim, many rays option, some rays don't pass through the optic:
![image](https://user-images.githubusercontent.com/29347882/124325716-61cbc200-db42-11eb-8ab4-14da152fc6cc.png)

When we introduced the diverging lens in the new sim, we were unsure of how to handle rays that pass through the side and top of the diverging lens.  Currently, it is set up to not display any rays that do not pass through the front and back of the lens.
![image](https://user-images.githubusercontent.com/29347882/124325860-a5263080-db42-11eb-8691-4231dc8ea5c8.png)

Should more rays be displayed?

**Comment by sarchang** [comment]
From design meeting 7/6: leave as is?

**Comment by veillette** [comment]
@sarchang, I think the decision was to implement a new strategy that deals with the rays, which would include showing a constant number of rays. For the concave lens, we would show rays that go through the first surface of the lens and propagate them as having gone through the lens at that point.

**Comment by veillette** [comment]
This is now fixed following the work in #98. Closing
