### ISSUE TITLE
How to deal with object close to the optics but very far from optical axis.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#73]
When the curvature of a mirror and lens is large and the object if very far from the axis, the object and the image can appear on the same side of the optic as illustrated in the two pictures below.

The magenta points represent the position of the object and image.

![image](https://user-images.githubusercontent.com/7633344/124605419-e025ae00-de39-11eb-8785-5b4ba1e37efb.png)

![image](https://user-images.githubusercontent.com/7633344/124605463-eb78d980-de39-11eb-999d-2031127cd857.png)

**Comment by sarchang** [comment]
From 7/6 design meeting: we could change the limits for curvature radius and diameter or prevent object from getting too close to the optic

**Comment by arouinfar** [comment]
I adjusted the mirror parameters in #261. Here's a screenshot with the max diameter (130 cm) and ROC (150 cm).  We can prevent overlap if the object is at least 40 cm away (defined center-to-center) from the mirror. 

![Screen Shot 2021-10-29 at 1 21 25 PM](https://user-images.githubusercontent.com/8419308/139491533-1c475ac2-4065-4bbc-93e0-636cf51e4c0e.png)

**Comment by pixelzoom** [comment]
Implemented in the above commit, and it applies for both lens and mirror.  @arouinfar please review, feel free to close.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom
