### ISSUE TITLE
Create optical axis

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#8]
This issue will collect  all the details associated with the optical axis.
![image](https://user-images.githubusercontent.com/7633344/119539835-abaed480-bd5a-11eb-90e6-c1d632dfe389.png)

**Comment by veillette** [comment]
Here is a first pass at requirements and details of implementation.

The optical axis is the horizontal line that goes through the middle of the optical element (mirror and lens). The optical axis is always visible and move along with the optical element.

It is most likely an overkill to create a model element for the optical axis. It will be sufficient to create a view element and instantiate it in GeometricOpticsScreenView.  The view node is part of the play area and should be added as a child to the "playAreaNode". The optical axis should have the lowest z-order in the scene graph. The constructor will depend on optic.positionProperty and the modelviewTransform. 

Ideally the optical axis  should span the  entire screen. However, since the simulation uses a zoom in out features, it can be possible to see the ends of the optical axis.
 There are three possible approaches to address it
(1) don't bother too much about it
(2) make the optical axis very long such that it extends much beyond the dev screen
(3) have the optical axis rescale itself based on the value of zoomProperty.

The color of the axis should be imported from GeometricOpticsColorProfile and the width of the optical axis should be taken from GeometricOpticsConstants.

**Comment by veillette** [comment]
This feature should be relatively easy to implement and therefore is ideal as an entry level issue to address.

**Comment by sarchang** [comment]
Still need to prevent optical axis from scaling with zoom and use the bounds of the simulation to determine line length

**Comment by sarchang** [comment]
We tried to make the bounds of the optical axis depend on the zoom level (option 3), but this proved to be complicated. We ended up extending the bounds of the optical axis far beyond the bounds of the screen view (option 2).

**Comment by sarchang** [comment]
As a result of the discussion in the design meeting on 6/8/2021, we agreed that the optical axis should scale with the playground and that our approach was sufficient.
