### ISSUE TITLE
Cueing arrows should be added to indicate that the point is draggable 

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#81]
See Atomic Interactions for an example (as well as the design document of Geometric Optics)

**Comment by veillette** [comment]
“Movable” helps cue the interaction, but we should just use cueing arrows, similar to Projectile Motion height control:

Add cueing arrows above and below the dot. Same color as dot.

![image](https://user-images.githubusercontent.com/7633344/124785453-dcb32500-df14-11eb-8fd1-deca4a94cd22.png)

**Comment by veillette** [comment]
The cueing arrows should appear after the first time that second source checkbox is checked and the representation is object. The cueing arrows should disappeared after the stop drag event.

**Comment by veillette** [comment]
If the user does not interact with the cueing arrows and change the representation to light source  or reset, the cueing arrows should be  present again when selecting any object representation.

**Comment by veillette** [comment]
Let's run the last two comments by the design-team.

**Comment by veillette** [comment]
Our approach was greenlighted by the design team on 7/13.

**Comment by veillette** [comment]
Cueing arrows have been added. Their style was borrow from the implementation in Projectile Motion.  
The visibility is tied to the end event of the drag Listener.

**Comment by sarchang** [comment]
From design meeting: looks good
