### ISSUE TITLE
The dragHandler for the second source has an offset.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#82]

**Comment by veillette** [comment]
As part of the work on #79, we noticed that there is an offset to the second source on start event off the dragListener. This is present solely on the movable source of light and  not on the movable object.

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/geometric-optics/issues/191.  https://github.com/phetsims/geometric-optics/issues/191 has more details and steps to reproduce, so closing this issue.
