### ISSUE TITLE
Tree: Manually adjust where the rays intersect the object and the image such that it is consistent with artwork

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#84]

**Comment by veillette** [comment]
The offset for the tree has been adjusted manually in relationship to the object.

**Comment by veillette** [comment]
Assigning to @sarchang for review.

**Comment by sarchang** [comment]
I slightly adjusted some values. We'll have to change all of this anyway when we receive the new artwork. Looks good; closing.
