### ISSUE TITLE
z-order of projector screen and rays

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#85]
In the Flash simulation, rays that don't pass through the screen continue on past the screen. The optical axis also passes through the screen.
![image](https://user-images.githubusercontent.com/29347882/124813670-62899d00-df22-11eb-9a90-c05aee810554.png)

Our current sim blocks all rays along the x value of the screen and is behind the optical axis.
![image](https://user-images.githubusercontent.com/29347882/124813920-a2e91b00-df22-11eb-9410-69ed71f734e8.png)

Our current sim should match the behavior in the Flash sim except that the screen should block rays completely.

**Comment by veillette** [comment]
Tagging with Metting:design to ensure that we are on the right track with this feature.

**Comment by veillette** [comment]
In the 7/13, @arouinfar confirmed that our approach is sound.

**Comment by veillette** [comment]
See #109 for a similar idea for object and target image

**Comment by pixelzoom** [comment]
@arouinfar please review and let me know what still needs to be done here.  It seems like fixing the optical axis would make things look better, and shouldn't be terribly difficult.

**Comment by arouinfar** [comment]
@pixelzoom I don't think there's any remaining work for this issue.

The desired behavior appears to be in master, namely:
1. Any portion of the spotlight that falls outside of the screen boundaries should be clipped.
2. Only the rays that hit the screen should be terminated.

![image](https://user-images.githubusercontent.com/8419308/135664233-983f94b1-f977-4108-ae50-8c4a547145ed.png)
