### ISSUE TITLE
Toggling from pencil to light to pencil causes the pencil image to increase in size

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#89]
Starting on the initial setup of the sim:
![image](https://user-images.githubusercontent.com/29347882/124963650-4f87d300-dfdd-11eb-9519-e6f9735dc6ae.png)

And then switching to light:
![image](https://user-images.githubusercontent.com/29347882/124963712-62020c80-dfdd-11eb-83ec-8d1924191cf0.png)

And then switching back to pencil causes the pencil image to be much larger than expected (but the pencil image decreases to the correct size as soon as you start dragging the pencil object:
![image](https://user-images.githubusercontent.com/29347882/124963903-9c6ba980-dfdd-11eb-9cdb-a2784cc6e334.png)

**Comment by veillette** [comment]
We need to update the scale if the value of the imageProperty changes.

**Comment by veillette** [comment]
Assigning to @sarchang  to check if it adresses the issue.

**Comment by sarchang** [comment]
Fixed; closing.
