### ISSUE TITLE
Create and add vertical and horizontal rulers 

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#9]
The ruler should be movable and span about half the screen in length. The 
Scenery-phet as a RulerNode that should be leveraged for this simulation. Pendulum Lab, BeersLaw, masses and springs and many other simulation have rulers.

The rulers should be on top of everything else (z-order wise) in the simulation. The last ruler that has been  grabbed should appear on top of the z-order of the other ruler.  

One unique aspect of this simulation is the use of zoom in and out with a ruler.  If one zoom out too much, I think that it may become somewhat useless because it will be a very short ruler.
To counteract this effect there are two (possibly more ?) approaches:
(1) Add the rulers to the play area node. The scale of the ruler will shrink in size, but the effect would be counteracted by instantiating a new ruler of longer scale, bigger font and less tick marks. 
(2) Add the rulers directly to the GeometricOpticsScreenView (instead of the play Area node). The length of the ruler would stay the same but a new ruler would be instantiated with new units spacing to reflect the change of scale

The second approach seems like the less amount of work, however, I am not sure how it will play out with the positioning in the play area.

**Comment by veillette** [comment]
Flash Horizontal rulers:
![image](https://user-images.githubusercontent.com/7633344/119545890-4b6f6100-bd61-11eb-831f-99ce8e02307a.png)

**Comment by veillette** [comment]
From the google drive document:



<b style="font-weight:normal;" id="docs-internal-guid-0174121a-7fff-aeea-92f8-fba341f5a0ed"><div dir="ltr" style="margin-left:0pt;" align="left">
Rulers always on top, but have reduced opacity (like Masses and Springs).Current size of the horizontal ruler looks good (½ dev bounds width). Vertical ruler can be shorter since.When zooming out, swap out the ruler for a different one of the appropriate scale. (Prevents the ruler from being too tiny to be useful.)
--


</div></b>

**Comment by sarchang** [comment]
1. Why is `options` greyed out in `Ruler.js`? Because of this, I had to pass in `{orientation: 'horizontal'}` to get the horizontal ruler to appear.
2. I can't seem to change the initial positions of the rulers by changing the Vector2 in the model.  Also, when I print out the position, they both seem to have the position of the vertical ruler?  But one appears horizontal and the other appears vertical.  
3. Still need to figure out how to change the z-order between the 2 rulers, since the one that user interacted with last should be on top.

**Comment by veillette** [comment]
I have addressed the positioning of the ruler.

**Comment by veillette** [comment]
The orientation of the ruler should be done in the model and pass down to the model. Review the work done to understand how you can reach the value se in the option field.

**Comment by veillette** [comment]
I also added a reset function to reset the position of the ruler.

**Comment by sarchang** [comment]
We set the opacity of the rulers.

**Comment by veillette** [comment]
We have previously discussed that the view model of the ruler should stay the same, as we scale the ruler. However, that does not answer many questions about the scaling properties of the ruler. 
We are unsure on how to proceed about to scale the ruler when zoom in/out.
In particular, we would like to know if the height of the ruler , the font, the tick marks should scale.
Should the number of ticks mark remain constant as we scale the ruler?.

**Comment by sarchang** [comment]
Rulers should not be part of the Play Area and therefore should not scale (font size, ruler height/width).  Ruler should always take up the same visual length in the simulation, even when zooming.  So when we zoom, the model length should be scaled appropriately and the numbers should change such that the major ticks are multiples of 10.  Minor ticks should be set such that they are useful and resemble a real ruler.

The ruler should have drag bounds such that it remains within the dev bounds. It can cover the control panel.

**Comment by sarchang** [comment]
Now major tick labels on rulers change based on zoom level.

**Comment by sarchang** [comment]
Still need to resolve dependencies:
1. functional dependencies of the zoom in GeometricOpticsRulerNode and GeometricOpticsScreenView (constant and Math.pow are present in both)
2. zoom factor should be able to take on a value other than exactly 2 (ex. 1.9)

**Comment by sarchang** [comment]
Ruler scales opposite of intended direction!

**Comment by sarchang** [comment]
Design meeting: The rulers are currently returned to the toolbox when any part of the ruler overlaps with the toolbox panel. Should it be this way? Or should more of the ruler be required to overlap?  Should we expand the touch margins for dragging out the rulers (they are thin)?

**Comment by sarchang** [comment]
- [ ] Rulers should be returned when cursor and ruler overlap with toolbox.
- [ ] Ruler touch margins should be expanded. 
- [ ] Add touchsnag
- [ ] Vertical ruler should be taller

**Comment by veillette** [comment]
Tracking the remaining issues in #55. Closing
