### ISSUE TITLE
Consider making "Principal" the default option on the Lens screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#91]
I was playing around with the initial dev version of this sim, and it seems it would be better if the radio buttons were rearranged slightly so that "Principal" was the first choice.

In my experience we usually use the principal rays first, in addition the focal points have more meaning with the principal ray view, so I think their importance is highlighted if that is the default suggestion. 

Worth considering bringing up at a design meeting in my opinion

**Comment by sarchang** [comment]
From Amy: Leave "marginal" as default.

**Comment by veillette** [comment]
We discussed in the 7/13 meeting the pros and cons of marginal vs principal rays.

Assigning back to @arouinfar.

**Comment by sarchang** [comment]
From my experience with student interviews on this sim, the current order (marginal, principal, many, none) is a good order and makes the most sense for students. Principal rays are very confusing for students who have never taken optics. Closing.

**Comment by arouinfar** [comment]
@ariel-phet I appreciate the suggestion, there was some internal debate between principal and marginal rays, but we ultimately decided to keep marginal rays the default option. Principal rays are certainly more useful in the setting of an optics course, but they are not as intuitive for learners. This is particularly true when moving the object far enough away from the optical axis that the rays no longer intersect the boundaries of the lens, see #93 for an example.
