### ISSUE TITLE
Consider changing background color

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#92]
I know the original geometric optics has this dark blue background, but it feels like it lacks some contrast, and could be improved upon.

Just for example, look at what openstax did when they tried performing a conversion:

https://archive.cnx.org/specials/137b787c-9c2c-4430-b4c0-c1f55e3921d2/geometric-optics/#sim-geometric-optics

I am not saying they necessarily made a great choice either, but the contrast certainly seems higher.

**Comment by sarchang** [comment]
Consider black? Might also think about changing the other colors as well (rays, optical axis, optic, buttons)
![image](https://user-images.githubusercontent.com/29347882/125002532-698fd880-e012-11eb-8975-217a8c0d6682.png)

**Comment by veillette** [comment]
Thanks @ariel-phet  for chiming in and @sarchang for the screenshot. We will bring it up a our next design meeting.

**Comment by veillette** [comment]
Brought up for discussion at the 7/13 design meeting. Assigning back to @arouinfar to make final decision. 
FYI, the background color has been hoisted to the color profile.

**Comment by arouinfar** [comment]
We will try out the gray background with white rays, but color changes will be handled in https://github.com/phetsims/geometric-optics/issues/182, so we can close this issue.
