### ISSUE TITLE
Odd looking Principal Rays

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#93]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/667. Mostly an odd visual behavior. It is, however, correct from a physics stand point, so I don't think it is a bug, but a second design pass may be desired. Specifically, the rays passing through the middle of the screen and bending or reflecting, even when the lens or mirror isn't there.
**Steps to reproduce**
1. Go to either screen with any type of mirror
2. Turn on Principal Rays
3. Drag the object up above the lens or mirror

**Visuals**
<img width="960" alt="alsooutside" src="https://user-images.githubusercontent.com/41024075/124997875-a656d200-e008-11eb-8418-5100769f86d2.png">
<img width="959" alt="rayoutsidelens" src="https://user-images.githubusercontent.com/41024075/124997877-a6ef6880-e008-11eb-8a3c-5abedc034ed8.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by veillette** [comment]
We will bring it up at our next design meeting (7/13)

**Comment by veillette** [comment]
We brought it up at the design meeting (7/13) . Assigning to @arouinfar to  make design decision if needed.

**Comment by pixelzoom** [comment]
9/30/21 design meeting:

This will be handled by implementing #140.  So closing.
