### ISSUE TITLE
Image is not correct while changing Curvature Radius

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#94]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/667. When you change the curvature Radius of a lens or mirror the image seems to change incorrectly initially. If you move the object, the image corrects itself. It may also happen with the refractive index lens settings, but I'm having a bit of a difficult time telling. I saw this most clearly using the Second Source point.
**Steps to reproduce**
1. Go to the lens screen and turn on the Second Source and some form of rays (I used Principal Rays)
2. Move the red second source dot down to the center of the pencil eraser
3. Make sure the image is visible and note where the second source rays converge
4. Move the slider for the lens curvature radius. Note that the rays no longer converge on the eraser
5. Move the object slightly. Note that the image corrects itself

**Visuals**
![movingfocus](https://user-images.githubusercontent.com/41024075/124999750-12870500-e00c-11eb-9f06-2a7efcf04845.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Also seems to happen with any virtual image.

**Comment by veillette** [comment]
I can confirm that it is happening.

**Comment by veillette** [comment]
This is now fixed although I do not understand why the previous approach did not work.

**Comment by veillette** [comment]
This is now fixed and working.
