### ISSUE TITLE
Marginal Rays Miss Mirror if Mirror Moves

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#99]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/667. Only seen on mirror screen so far. If you have marginal rays on and move the mirror, the outside rays will not follow to the margins of the new mirror position. They will stay in the same position and miss the mirror if it move far enough. So only the middle ray hits the mirror and the others go past, or at least don't hit the mirror at the edges.
**Steps to reproduce**
1. Go to mirror screen
2. Turn on Marginal Rays
3. Drag the mirror up and down

**Visuals**
![marginalnolongercaught](https://user-images.githubusercontent.com/41024075/125108991-0187d380-e0a0-11eb-836d-b809995fd23c.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html
Version: 1.0.0-dev.1 2021-07-08 19:47:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by brooklynlash** [comment]
Also seen on Win10 FF.

**Comment by veillette** [comment]
The rays are missing the position of the mirror because they are using a stale value of the mirror position.

**Comment by veillette** [comment]
The marginal rays are now receiving the correct position of the mirror.

**Comment by veillette** [comment]
Assigning to @sarchang to review.

**Comment by sarchang** [comment]
Rays move with the mirror now; closing.
